### ISSUE TITLE
CUDA Setup failed despite GPU being available. Please run the following command to get more information:

### ISSUE THREAD

**Issue by Grsz** [TimDettmers/bitsandbytes#1059]
### System Info

Ubuntu 22.04.3, Python 3.10.12, i7 14700K, RTX 4090.

### Reproduction

I'm struggling to run kohya ss, there are constant issues with bitsandbytes. No matter what I do:
 - upgrade from pip install -U bitsandbytes (from either root, or venv)
 - run ./setup.sh
 - run ./gui.sh, and start training
 - run python -m bitsandbytes from root
 - run python -m bitsandbytes from venv
I get the following output:

```
The following directories listed in your path were found to be non-existent: {PosixPath('/etc/xdg/xdg-ubuntu')}
The following directories listed in your path were found to be non-existent: {PosixPath('local/g-Z790-AERO-G'), PosixPath('@/tmp/.ICE-unix/2493,unix/g-Z790-AERO-G')}
The following directories listed in your path were found to be non-existent: {PosixPath('0'), PosixPath('1')}
The following directories listed in your path were found to be non-existent: {PosixPath('/etc/xdg/xdg-ubuntu')}
The following directories listed in your path were found to be non-existent: {PosixPath('unix'), PosixPath('path=/run/user/1000/bus,guid=d29f3ce95df599d870367a8065ca8048')}
CUDA_SETUP: WARNING! libcudart.so not found in any environmental path. Searching in backup paths...
DEBUG: Possible options found for libcudart.so: {PosixPath('/usr/local/cuda/lib64/libcudart.so')}
CUDA SETUP: PyTorch settings found: CUDA_VERSION=118, Highest Compute Capability: 8.9.
CUDA SETUP: To manually override the PyTorch CUDA version please see:https://github.com/TimDettmers/bitsandbytes/blob/main/how_to_use_nonpytorch_cuda.md
CUDA SETUP: Loading binary /media/g/New Volume/kohya_ss/venv/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cuda118.so...
libcusparse.so.11: cannot open shared object file: No such file or directory
CUDA SETUP: Something unexpected happened. Please compile from source:
git clone https://github.com/TimDettmers/bitsandbytes.git
cd bitsandbytes
CUDA_VERSION=118 make cuda11x
python setup.py install
Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 187, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/usr/lib/python3.10/runpy.py", line 146, in _get_module_details
    return _get_module_details(pkg_main_name, error)
  File "/usr/lib/python3.10/runpy.py", line 110, in _get_module_details
    __import__(pkg_name)
  File "/media/g/New Volume/kohya_ss/venv/lib/python3.10/site-packages/bitsandbytes/__init__.py", line 6, in <module>
    from . import cuda_setup, utils, research
  File "/media/g/New Volume/kohya_ss/venv/lib/python3.10/site-packages/bitsandbytes/research/__init__.py", line 1, in <module>
    from . import nn
  File "/media/g/New Volume/kohya_ss/venv/lib/python3.10/site-packages/bitsandbytes/research/nn/__init__.py", line 1, in <module>
    from .modules import LinearFP8Mixed, LinearFP8Global
  File "/media/g/New Volume/kohya_ss/venv/lib/python3.10/site-packages/bitsandbytes/research/nn/modules.py", line 8, in <module>
    from bitsandbytes.optim import GlobalOptimManager
  File "/media/g/New Volume/kohya_ss/venv/lib/python3.10/site-packages/bitsandbytes/optim/__init__.py", line 6, in <module>
    from bitsandbytes.cextension import COMPILED_WITH_CUDA
  File "/media/g/New Volume/kohya_ss/venv/lib/python3.10/site-packages/bitsandbytes/cextension.py", line 20, in <module>
    raise RuntimeError('''
RuntimeError: 
        CUDA Setup failed despite GPU being available. Please run the following command to get more information:

        python -m bitsandbytes

        Inspect the output of the command and see if you can locate CUDA libraries. You might need to add them
        to your LD_LIBRARY_PATH. If you suspect a bug, please take the information from python -m bitsandbytes
        and open an issue at: https://github.com/TimDettmers/bitsandbytes/issues
```

The same issue is on WIndows.

### Expected behavior

It shouldn't throw errors.

**Comment by SytanSD** [comment]
Same issue here for over 5 months. I have spent dozens of hours trying to fix this on my windows machine, as my job relies on me being able to use bitsandbytes. I have had to switch to using bitsandbytes-windows, but its latest version has a severe issue where LoRA training often explodes into a mess of useless weights at random, leading to large amounts of my compute being *regularly* wasted.

I have reinstalled CUDA, tried to manually install 6 different versions of bitsandbytes, used bitsandbytes-windows as well as bitsandbytes-windows-webUI. I have not been able to find any documentation on this issue, and it has been severely effecting my ability to do work for my job at a consistent and efficient rate.

If anybody has any input on what may be the cause of this, I would be massively appreciative to hear anything about this.

**Comment by Fitmavincent** [comment]
I have the same issue here. Any suggestions? 

PyTorch version:  2.2.0+cu121
CUDA version:  12.1       
Number of CUDA devices:  1

**Comment by younesbelkada** [comment]
Hi everyone! 
We recently switched to using CMake for windows installation, could you try out these commands by installing bnb from source: https://huggingface.co/docs/bitsandbytes/main/en/installation?OS+system=Windows 🙏 Hopefully this should resolve the issues
cc @wkpark @Titus-von-Koeller

**Comment by wkpark** [comment]
or you can download prebuilt binary wheels from workflows. for example: (login required)
https://github.com/TimDettmers/bitsandbytes/actions/runs/7836890878
- download `bdist_wheel_*` zip. in this zip you can find `*.whl` file.
- `pip install bitsandbytes_*.whl`

**Comment by Shivam-21-11** [comment]
I had the same issue but doing following steps helped me resolve the issue:

-  pip uninstall bitsandbytes
-  pip uninstall bitsandbytes-windows
- pip install https://github.com/jllllll/bitsandbytes-windows-webui/releases/download/wheels/bitsandbytes-0.41.1-py3-none-win_amd64.whl

**Comment by yash-lnxct** [comment]
please tell another solutions if possible. still i have same problem

**Comment by Shivam-21-11** [comment]
> please tell another solutions if possible. still i have same problem. i am using Ubuntu 22.04 and cuda 12.3

From what I encountered the error is caused due to wrong combination of version of cuda and bitsandbytes. I had to find bitsandbyte compatible with my cuda (11.6) and model (falco-7b from HuggingFace). Try to find the source package of bitsandbyte which is compatible with your cuda.

**Comment by SouthMemphis** [comment]
@Shivam-21-11  I love you
I love you so much I hope you have a good day at work and I hope you have a good night at work I love you very much and I hope you have a good time at work I love you and kiss you for all your heart and soul and I will talk to you later bye love you love you

**Comment by yash-lnxct** [comment]
Thank you @Shivam-21-11. now it is working with cuda 11.5 in my system.

**Comment by pervrosen** [comment]
Ended up here with the same reason.. But I got a "future proof" workaround for this cuda version mess similar to conda/venv mess - also cloud friendly. (well not the git+https installation below is not future proof...) Set up "nvidia container tollkit" and docker (https://docs.nvidia.com/datacenter/cloud-native/container-toolkit/latest/install-guide.html) and follow the EXAMPLE recipe below:

```
docker run --gpus all -it --rm --name ai -p8888:8888 nvidia/cuda:12.1.0-cudnn8-devel-ubuntu22.04
apt update 
apt install -y curl 
"${SHELL}" <(curl -L micro.mamba.pm/install.sh)
source ~/.bashrc 
micromamba create -n ai -q -y python=3.9 -c conda-forge
apt install -y git
git clone https://github.com/artidoro/qlora.git
cd qlora/
micromamba activate ai
pip3 install -r requirements.txt 
pip3 install ipywidgets jupyterlab
pip3 install -q -U bitsandbytes
pip3 install -q -U git+https://github.com/huggingface/transformers.git
pip3 install -q -U git+https://github.com/huggingface/peft.git
pip3 install -q -U git+https://github.com/huggingface/accelerate.git
pip3 install -q -U git+https://github.com/Dao-AILab/flash-attention.git
pip3 install -q -U datasets

python -m bitsandbytes  <--- Here we check the lib!

jupyter-lab --ip 0.0.0.0 --allow-root
```

**Comment by wkpark** [comment]
https://github.com/jllllll/bitsandbytes-windows-webui/releases/download/wheels/bitsandbytes-0.41.1-py3-none-win_amd64.whl
this wheel include almost all available cuda versions. the size of this wheel is about ~146MB!

torch for windows includes cuda libraries for example, torch-2.1.x+cu121 includes `cudart64_14.dll` and it can be installed on cuda 11.8 environment.

----
for linux, bitsandbytes have to compiled on ubuntu-20.04 to fix `GLIBC_2.xx.yy` symbol issue.

**Comment by MariaVlahova** [comment]
> I had the same issue but following steps helped me resolve the issue:
> 
> * pip uninstall bitsandbytes
> * pip uninstall bitsandbytes-windows
> * pip install https://github.com/jllllll/bitsandbytes-windows-webui/releases/download/wheels/bitsandbytes-0.41.1-py3-none-win_amd64.whl

works on windows

**Comment by Jaki342** [comment]
> I had the same issue but following steps helped me resolve the issue:
> 
> * pip uninstall bitsandbytes
> * pip uninstall bitsandbytes-windows
> * pip install https://github.com/jllllll/bitsandbytes-windows-webui/releases/download/wheels/bitsandbytes-0.41.1-py3-none-win_amd64.whl



> I had the same issue but following steps helped me resolve the issue:
> 
> * pip uninstall bitsandbytes
> * pip uninstall bitsandbytes-windows
> * pip install https://github.com/jllllll/bitsandbytes-windows-webui/releases/download/wheels/bitsandbytes-0.41.1-py3-none-win_amd64.whl

doesn't work on google collab:/.  i get this: ERROR: bitsandbytes-0.41.1-py3-none-win_amd64.whl is not a supported wheel on this platform.

**Comment by Shivam-21-11** [comment]
> > I had the same issue but following steps helped me resolve the issue:
> 
> > 
> 
> > * pip uninstall bitsandbytes
> 
> > * pip uninstall bitsandbytes-windows
> 
> > * pip install https://github.com/jllllll/bitsandbytes-windows-webui/releases/download/wheels/bitsandbytes-0.41.1-py3-none-win_amd64.whl
> 
> 
> 
> 
> 
> 
> 
> > I had the same issue but following steps helped me resolve the issue:
> 
> > 
> 
> > * pip uninstall bitsandbytes
> 
> > * pip uninstall bitsandbytes-windows
> 
> > * pip install https://github.com/jllllll/bitsandbytes-windows-webui/releases/download/wheels/bitsandbytes-0.41.1-py3-none-win_amd64.whl
> 
> 
> 
> doesn't work on google collab:/.  i get this: ERROR: bitsandbytes-0.41.1-py3-none-win_amd64.whl is not a supported wheel on this platform.

As for cloud notebooks i too had hard time fixing it. My original solution works for windows with cuda 11.2 > and <=11.8 and pytorch 2.2.x=> and  >1.2.x , As for collab try to find cuda version using `nvcc --version` and try to find bitsandbytes version compatible with it. In collab i managed to get it working by running `!pip install -q bitsandbytes` and `pip install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu118 ` and then import the necessary modules.

**Comment by mohammad-albarham** [comment]
Hi 



> https://github.com/jllllll/bitsandbytes-windows-webui/releases/download/wheels/bitsandbytes-0.41.1-py3-none-win_amd64.whl this wheel include almost all available libs of cuda versions. the size of this wheel is about ~146MB!
> 
> but we don't have to compile/packaging all available cuda libs, torch for windows includes cuda libraries, for example, torch-2.1.x+cu121 includes `cudart64_14.dll` and it can be installed on cuda 11.8 environment. so, bitsandbytes for cuda11.8 could be used under cuda 11.6 if cuda11.8 libs incuded in wheel. (or just copy cuda11.8 libs from somewhere like `conda-forge` and extract needed cuda libs into `bitsandbytes/` dir, and bitsandbytes for cuda11.8 could be used on cuda11.6 system)
> 
> and another issue for linux (I guess this issue is related in this post), bitsandbytes have to compiled on ubuntu-20.04 to fix `GLIBC_2.xx.yy` symbol issue.

Thank you for efforts.


Unfortunetly, I tried all ways to install the library on Linux 20.4

Is there any way to do that?

**Comment by nuass** [comment]
> or you can download prebuilt binary wheels from workflows. for example: (login required) https://github.com/TimDettmers/bitsandbytes/actions/runs/7836890878
> 
> * download `bdist_wheel_*` zip. in this zip you can find `*.whl` file.
> * `pip install bitsandbytes_*.whl`

https://pypi.org/project/bitsandbytes/#files

**Comment by Titus-von-Koeller** [comment]
Hey all, sorry for the struggles you've been having! Often the issues are related to the underlying CUDA installation and not bitsandbytes itself. I agree that the error traces are quite confusing (they are actually trying to help fix the setup issues) and often look the same (but the details in the output are often different):

Currently, there's very active work on improving those diagnostics to be better and clearer (just merged a big PR today). I plan significant improvements on that side for the next two releases.

BNB works for most setups, but we still have this long tail of issues where people are having a really difficult time and it's not easy to diagnose. As we're getting up to speed with maintenance (we took over not too long ago and there is a big backlog of technical debt), we'll be sure to make your life easier.

For now, this is already the case for Windows users. **Since release `0.43.0`, we have official Windows support.** You can simply install it with `pip install bitsandbytes>=0.43.0`

**Please, Windows users, install in this way and let us know if it worked without issues.**

Thanks everyone for your patience and feedback 🤗

**Comment by potatoker** [comment]
what about centOS users?  Is "pip install bitsandbytes>=0.43.0" the solution?

**Comment by potatoker** [comment]
> https://github.com/jllllll/bitsandbytes

but how can I find the compatible version bitsandbytes

**Comment by Shivam-21-11** [comment]
> > https://github.com/jllllll/bitsandbytes
> 
> but how can I find the compatible version bitsandbytes

i would suggest downgrade to cuda 11.6 and then install latest bitsandbytes this seems to work for majority of the people. Finding exclusive compatible version combination requires going through documentation.

**Comment by BlueEyesWhiteKaiju** [comment]
> > or you can download prebuilt binary wheels from workflows. for example: (login required) https://github.com/TimDettmers/bitsandbytes/actions/runs/7836890878
> > 
> > * download `bdist_wheel_*` zip. in this zip you can find `*.whl` file.
> > * `pip install bitsandbytes_*.whl`
> 
> I download this and fixed the error. https://pypi.org/project/bitsandbytes/#files

You absolute godsend, thank you.

**Comment by nardo7** [comment]
I was getting this error with version 0.42.0 in Debian with CUDA 12.4 (GCE). 
`pip uninstall bitsandbytes` and `pip install bitsandbytes` solved my issue (installing latest version of Bitsandbytes)

**Comment by dasdipanjan04** [comment]
This is such a persistent issue and even after 10 months it is not fixed.

**Comment by mwzkhalil** [comment]
Does this Issue resolved? still getting this error 
`RuntimeError: CUDA is required but not available for bitsandbytes. Please consider installing the multi-platform enabled version of bitsandbytes, which is currently a work in progress. Please check currently supported platforms and installation instructions at https://huggingface.co/docs/bitsandbytes/main/en/installation#multi-backend`

**Comment by Shivam-21-11** [comment]
> Does this Issue resolved? still getting this error 
> `RuntimeError: CUDA is required but not available for bitsandbytes. Please consider installing the multi-platform enabled version of bitsandbytes, which is currently a work in progress. Please check currently supported platforms and installation instructions at https://huggingface.co/docs/bitsandbytes/main/en/installation#multi-backend`
> 
> 

You don't have cuda installed so if you install compatible version of cuda and then install bitsandbytes it should not give error

**Comment by mwzkhalil** [comment]
thank you its work @Shivam-21-11

**Comment by korkmazemin1** [comment]
> Does this Issue resolved? still getting this error `RuntimeError: CUDA is required but not available for bitsandbytes. Please consider installing the multi-platform enabled version of bitsandbytes, which is currently a work in progress. Please check currently supported platforms and installation instructions at https://huggingface.co/docs/bitsandbytes/main/en/installation#multi-backend`

I m getting this error on google colab. Even it has cuda installed. and ı tried pip things

**Comment by Nafishsy** [comment]
> I had the same issue but following steps helped me resolve the issue:
> 
> * pip uninstall bitsandbytes
> * pip uninstall bitsandbytes-windows
> * pip install https://github.com/jllllll/bitsandbytes-windows-webui/releases/download/wheels/bitsandbytes-0.41.1-py3-none-win_amd64.whl

Thanks, I was having an issue with something else which led me to try a lot of things over past couple of weeks. this solved a lot of my issues.
