### ISSUE TITLE
Win10 + WSL2 + Ubuntu 20.04 + miniconda ：CUDA SETUP: CUDA detection failed!

### ISSUE THREAD

**Issue by donaldjohn** [TimDettmers/bitsandbytes#1150]
### System Info

Win10 + WSL2 + miniconda + Ubuntu 20.04

### Reproduction

I am using Ubuntu 20.04 in WSL2, Win10, miniConda
I installed bitsandbytes by ```conda install conda-forge::bitsandbytes```
The ```conda env config vars list``` is: 
```
BNB_CUDA_VERSION = 124
LD_LIBRARY_PATH = /usr/local/cuda-12.4
```
I set the LD_LIBRARY_PATH, bitsandbytes didn't use the toolkit I installed.

I installed multi version cudatoolkit by the fellowing command:
```bash
wget https://developer.download.nvidia.com/compute/cuda/repos/wsl-ubuntu/x86_64/cuda-wsl-ubuntu.pin
sudo mv cuda-wsl-ubuntu.pin /etc/apt/preferences.d/cuda-repository-pin-600
wget https://developer.download.nvidia.com/compute/cuda/12.4.0/local_installers/cuda-repo-wsl-ubuntu-12-4-local_12.4.0-1_amd64.deb
sudo dpkg -i cuda-repo-wsl-ubuntu-12-4-local_12.4.0-1_amd64.deb
sudo cp /var/cuda-repo-wsl-ubuntu-12-4-local/cuda-*-keyring.gpg /usr/share/keyrings/
sudo apt-get update
sudo apt-get -y install cuda-toolkit-12-4



wget https://developer.download.nvidia.com/compute/cuda/12.2.0/local_installers/cuda-repo-wsl-ubuntu-12-2-local_12.2.0-1_amd64.deb
sudo dpkg -i cuda-repo-wsl-ubuntu-12-2-local_12.2.0-1_amd64.deb
sudo cp /var/cuda-repo-wsl-ubuntu-12-2-local/cuda-*-keyring.gpg /usr/share/keyrings/
sudo apt-get update
sudo apt-get -y install cuda-toolkit-12-2



wget https://developer.download.nvidia.com/compute/cuda/12.1.0/local_installers/cuda-repo-wsl-ubuntu-12-1-local_12.1.0-1_amd64.deb
sudo dpkg -i cuda-repo-wsl-ubuntu-12-1-local_12.4.0-1_amd64.deb
sudo cp /var/cuda-repo-wsl-ubuntu-12-1-local/cuda-*-keyring.gpg /usr/share/keyrings/
sudo apt-get update
sudo apt-get -y install cuda-toolkit-12-1



wget https://developer.download.nvidia.com/compute/cuda/11.8.0/local_installers/cuda-repo-wsl-ubuntu-11-8-local_11.8.0-1_amd64.deb
sudo dpkg -i cuda-repo-wsl-ubuntu-11-8-local_11.8.0-1_amd64.deb
sudo cp /var/cuda-repo-wsl-ubuntu-11-8-local/cuda-*-keyring.gpg /usr/share/keyrings/
sudo apt-get update
sudo apt-get -y install cuda-toolkit-11-8

```

The output of ```python -m bitsandbytes```is blow:

```
/home/donadjohn/miniconda3/envs/hg1/lib/python3.11/site-packages/bitsandbytes/cuda_setup/main.py:122: UserWarning:

================================================================================
WARNING: Manual override via BNB_CUDA_VERSION env variable detected!
BNB_CUDA_VERSION=XXX can be used to load a bitsandbytes version that is different from the PyTorch CUDA version.
If this was unintended set the BNB_CUDA_VERSION variable to an empty string: export BNB_CUDA_VERSION=
If you use the manual override make sure the right libcudart.so is in your LD_LIBRARY_PATH
For example by adding the following to your .bashrc: export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:<path_to_cuda_dir/lib64
Loading: libbitsandbytes_cuda124.so
================================================================================


  warn(
False

===================================BUG REPORT===================================
/home/donadjohn/miniconda3/envs/hg1/lib/python3.11/site-packages/bitsandbytes/cuda_setup/main.py:183: UserWarning: Welcome to bitsandbytes. For bug reports, please run

python -m bitsandbytes


  warn(msg)
================================================================================
/home/donadjohn/miniconda3/envs/hg1/lib/python3.11/site-packages/bitsandbytes/cuda_setup/main.py:183: UserWarning: /home/donadjohn/miniconda3/envs/hg1 did not contain ['libcudart.so', 'libcudart.so.11.0', 'libcudart.so.12.0', 'libcudart.so.12.1', 'libcudart.so.12.2'] as expected! Searching further paths...
  warn(msg)
/home/donadjohn/miniconda3/envs/hg1/lib/python3.11/site-packages/bitsandbytes/cuda_setup/main.py:183: UserWarning: Found duplicate ['libcudart.so', 'libcudart.so.11.0', 'libcudart.so.12.0', 'libcudart.so.12.1', 'libcudart.so.12.2'] files: {PosixPath('/usr/local/cuda/lib64/libcudart.so'), PosixPath('/usr/local/cuda/lib64/libcudart.so.12.0')}.. We select the PyTorch default libcudart.so, which is {torch.version.cuda},but this might mismatch with the CUDA version that is needed for bitsandbytes.To override this behavior set the BNB_CUDA_VERSION=<version string, e.g. 122> environmental variableFor example, if you want to use the CUDA version 122BNB_CUDA_VERSION=122 python ...OR set the environmental variable in your .bashrc: export BNB_CUDA_VERSION=122In the case of a manual override, make sure you set the LD_LIBRARY_PATH, e.g.export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/local/cuda-12.2
  warn(msg)
/home/donadjohn/miniconda3/envs/hg1/lib/python3.11/site-packages/bitsandbytes/cuda_setup/main.py:183: UserWarning: /usr/local/cuda/lib64: did not contain ['libcudart.so', 'libcudart.so.11.0', 'libcudart.so.12.0', 'libcudart.so.12.1', 'libcudart.so.12.2'] as expected! Searching further paths...
  warn(msg)
The following directories listed in your path were found to be non-existent: {PosixPath('/home/donadjohn/installed_softwares/jdk-11.0.13/jre')}
The following directories listed in your path were found to be non-existent: {PosixPath('//192.168.31.242'), PosixPath('2080'), PosixPath('http')}
The following directories listed in your path were found to be non-existent: {PosixPath('//192.168.31.242'), PosixPath('2080'), PosixPath('http')}
The following directories listed in your path were found to be non-existent: {PosixPath('/home/donadjohn/installed_softwares/jdk-11.0.13/jre/lib')}
CUDA_SETUP: WARNING! libcudart.so not found in any environmental path. Searching in backup paths...
DEBUG: Possible options found for libcudart.so: {PosixPath('/usr/local/cuda/lib64/libcudart.so'), PosixPath('/usr/local/cuda/lib64/libcudart.so.12.0')}
CUDA SETUP: PyTorch settings found: CUDA_VERSION=121, Highest Compute Capability: 8.9.
CUDA SETUP: To manually override the PyTorch CUDA version please see:https://github.com/TimDettmers/bitsandbytes/blob/main/how_to_use_nonpytorch_cuda.md
CUDA SETUP: Required library version not found: libbitsandbytes_cuda121.so. Maybe you need to compile it from source?
CUDA SETUP: Defaulting to libbitsandbytes_cpu.so...

================================================ERROR=====================================
CUDA SETUP: CUDA detection failed! Possible reasons:
1. You need to manually override the PyTorch CUDA version. Please see: "https://github.com/TimDettmers/bitsandbytes/blob/main/how_to_use_nonpytorch_cuda.md
2. CUDA driver not installed
3. CUDA not installed
4. You have multiple conflicting CUDA libraries
5. Required library not pre-compiled for this bitsandbytes release!
CUDA SETUP: If you compiled from source, try again with `make CUDA_VERSION=DETECTED_CUDA_VERSION` for example, `make CUDA_VERSION=118`.
CUDA SETUP: The CUDA version for the compile might depend on your conda install. Inspect CUDA version via `conda list | grep cuda`.
================================================================================

CUDA SETUP: Something unexpected happened. Please compile from source:
git clone https://github.com/TimDettmers/bitsandbytes.git
cd bitsandbytes
CUDA_VERSION=121 make cuda12x
python setup.py install
CUDA SETUP: Setup Failed!
Traceback (most recent call last):
  File "<frozen runpy>", line 189, in _run_module_as_main
  File "<frozen runpy>", line 148, in _get_module_details
  File "<frozen runpy>", line 112, in _get_module_details
  File "/home/donadjohn/miniconda3/envs/hg1/lib/python3.11/site-packages/bitsandbytes/__init__.py", line 6, in <module>
    from . import cuda_setup, research, utils
  File "/home/donadjohn/miniconda3/envs/hg1/lib/python3.11/site-packages/bitsandbytes/research/__init__.py", line 2, in <module>
    from .autograd._functions import (
  File "/home/donadjohn/miniconda3/envs/hg1/lib/python3.11/site-packages/bitsandbytes/research/autograd/_functions.py", line 8, in <module>
    from bitsandbytes.autograd._functions import GlobalOutlierPooler, MatmulLtState
  File "/home/donadjohn/miniconda3/envs/hg1/lib/python3.11/site-packages/bitsandbytes/autograd/__init__.py", line 1, in <module>
    from ._functions import get_inverse_transform_indices, undo_layout
  File "/home/donadjohn/miniconda3/envs/hg1/lib/python3.11/site-packages/bitsandbytes/autograd/_functions.py", line 10, in <module>
    import bitsandbytes.functional as F
  File "/home/donadjohn/miniconda3/envs/hg1/lib/python3.11/site-packages/bitsandbytes/functional.py", line 17, in <module>
    from .cextension import COMPILED_WITH_CUDA, lib
  File "/home/donadjohn/miniconda3/envs/hg1/lib/python3.11/site-packages/bitsandbytes/cextension.py", line 17, in <module>
    raise RuntimeError('''
RuntimeError:
        CUDA Setup failed despite GPU being available. Please run the following command to get more information:

        python -m bitsandbytes

        Inspect the output of the command and see if you can locate CUDA libraries. You might need to add them
        to your LD_LIBRARY_PATH. If you suspect a bug, please take the information from python -m bitsandbytes
        and open an issue at: https://github.com/TimDettmers/bitsandbytes/issues
```

### Expected behavior

Anyone encountered this?

**Comment by donaldjohn** [comment]
I solved this problem, the bitsandbytes.0.43.0 from conda-forge is not work for me, 
I downgraded to 0.42.0, by ```conda install bitsandbytes=0.42.0```,  it works now!

The total steps to recover is below:

```bash
//create new conda env
conda create -n py312 python=3.12

conda install conda-forge::transformers conda-forge::accelerate conda-forge::bitsandbytes=0.42

python -m bitsandbytes
```
it should work now, the ```python -m bitsandbytes``` output is below:
```log
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
++++++++++++++++++ BUG REPORT INFORMATION ++++++++++++++++++
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

++++++++++++++++++ /usr/local CUDA PATHS +++++++++++++++++++
/usr/local/cuda-11.8/targets/x86_64-linux/lib/stubs/libcuda.so
/usr/local/cuda-11.8/targets/x86_64-linux/lib/libcudart.so
/usr/local/cuda-12.4/targets/x86_64-linux/lib/stubs/libcuda.so
/usr/local/cuda-12.4/targets/x86_64-linux/lib/libcudart.so
/usr/local/cuda-12.2/targets/x86_64-linux/lib/stubs/libcuda.so
/usr/local/cuda-12.2/targets/x86_64-linux/lib/libcudart.so

+++++++++++++++ WORKING DIRECTORY CUDA PATHS +++++++++++++++
/mnt/d/workspace/myenv/lib/python3.8/site-packages/bitsandbytes/libbitsandbytes_cuda110.so
/mnt/d/workspace/myenv/lib/python3.8/site-packages/bitsandbytes/libbitsandbytes_cuda110_nocublaslt.so
/mnt/d/workspace/myenv/lib/python3.8/site-packages/bitsandbytes/libbitsandbytes_cuda111.so
/mnt/d/workspace/myenv/lib/python3.8/site-packages/bitsandbytes/libbitsandbytes_cuda111_nocublaslt.so
/mnt/d/workspace/myenv/lib/python3.8/site-packages/bitsandbytes/libbitsandbytes_cuda114.so
/mnt/d/workspace/myenv/lib/python3.8/site-packages/bitsandbytes/libbitsandbytes_cuda114_nocublaslt.so
/mnt/d/workspace/myenv/lib/python3.8/site-packages/bitsandbytes/libbitsandbytes_cuda115.so
/mnt/d/workspace/myenv/lib/python3.8/site-packages/bitsandbytes/libbitsandbytes_cuda115_nocublaslt.so
/mnt/d/workspace/myenv/lib/python3.8/site-packages/bitsandbytes/libbitsandbytes_cuda117.so
/mnt/d/workspace/myenv/lib/python3.8/site-packages/bitsandbytes/libbitsandbytes_cuda117_nocublaslt.so
/mnt/d/workspace/myenv/lib/python3.8/site-packages/bitsandbytes/libbitsandbytes_cuda118.so
/mnt/d/workspace/myenv/lib/python3.8/site-packages/bitsandbytes/libbitsandbytes_cuda118_nocublaslt.so
/mnt/d/workspace/myenv/lib/python3.8/site-packages/bitsandbytes/libbitsandbytes_cuda120.so
/mnt/d/workspace/myenv/lib/python3.8/site-packages/bitsandbytes/libbitsandbytes_cuda120_nocublaslt.so
/mnt/d/workspace/myenv/lib/python3.8/site-packages/bitsandbytes/libbitsandbytes_cuda121.so
/mnt/d/workspace/myenv/lib/python3.8/site-packages/bitsandbytes/libbitsandbytes_cuda121_nocublaslt.so
/mnt/d/workspace/myenv/lib/python3.8/site-packages/bitsandbytes/libbitsandbytes_cuda122.so
/mnt/d/workspace/myenv/lib/python3.8/site-packages/bitsandbytes/libbitsandbytes_cuda122_nocublaslt.so
/mnt/d/workspace/myenv/lib/python3.8/site-packages/bitsandbytes/libbitsandbytes_cuda123.so
/mnt/d/workspace/myenv/lib/python3.8/site-packages/bitsandbytes/libbitsandbytes_cuda123_nocublaslt.so
/mnt/d/workspace/myenv/lib/python3.8/site-packages/torch/lib/libc10_cuda.so
/mnt/d/workspace/myenv/lib/python3.8/site-packages/torch/lib/libtorch_cuda.so
/mnt/d/workspace/myenv/lib/python3.8/site-packages/torch/lib/libtorch_cuda_linalg.so

++++++++++++++++++ LD_LIBRARY CUDA PATHS +++++++++++++++++++

++++++++++++++++++++++++++ OTHER +++++++++++++++++++++++++++
COMPILED_WITH_CUDA = True
COMPUTE_CAPABILITIES_PER_GPU = ['8.9']
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
++++++++++++++++++++++ DEBUG INFO END ++++++++++++++++++++++
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

Running a quick check that:
    + library is importable
    + CUDA function is callable


WARNING: Please be sure to sanitize sensible info from any such env vars!

SUCCESS!
Installation was successful!
```

**Comment by donaldjohn** [comment]
eh, 
The fellowing code is still now working, but in venv it works, same code, same lib version, I am giving up, I am swiching to venv from conda:
```bash

>>> from transformers import AutoModelForCausalLM
>>>
>>> model = AutoModelForCausalLM.from_pretrained(
...     "mistralai/Mistral-7B-v0.1", device_map="auto", load_in_4bit=True
... )
The `load_in_4bit` and `load_in_8bit` arguments are deprecated and will be removed in the future versions. Please, pass a `BitsAndBytesConfig` object in `quantization_config` argument instead.
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/donadjohn/miniconda3/envs/py312/lib/python3.11/site-packages/transformers/models/auto/auto_factory.py", line 563, in from_pretrained
    return model_class.from_pretrained(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/donadjohn/miniconda3/envs/py312/lib/python3.11/site-packages/transformers/modeling_utils.py", line 3049, in from_pretrained
    hf_quantizer.validate_environment(
  File "/home/donadjohn/miniconda3/envs/py312/lib/python3.11/site-packages/transformers/quantizers/quantizer_bnb_4bit.py", line 62, in validate_environment
    raise ImportError(
ImportError: Using `bitsandbytes` 8-bit quantization requires Accelerate: `pip install accelerate` and the latest version of bitsandbytes: `pip install -i https://pypi.org/simple/ bitsandbytes`

```

**Comment by donaldjohn** [comment]
OK, I downgraded python to 3.8, it works again, 
I'm impressed.

**Comment by lucas-kacz** [comment]
I had the same issue that you using an Ubuntu 22.04 machine and a conda venv. On my end, I believe that the problem was due to dependency conflicts between cuda, pytorch and bitsandbytes.

I decided to reinstall everything on a new venv using python 3.11 : 
```
conda create -y -n myenv python=3.11
pip3 install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu118
pip install transformers
pip install bitsandbytes
```
I installed the 0.43.0 version for bitsandbytes

According to the bitsandbytes documentation on HuggingFace: https://huggingface.co/docs/bitsandbytes/main/en/installation

I then followed this code snippet and changed the version to my version (118) : 
```
wget https://raw.githubusercontent.com/TimDettmers/bitsandbytes/main/install_cuda.sh
# Syntax cuda_install CUDA_VERSION INSTALL_PREFIX EXPORT_TO_BASH
#   CUDA_VERSION in {110, 111, 112, 113, 114, 115, 116, 117, 118, 120, 121, 122, 123, 124}
#   EXPORT_TO_BASH in {0, 1} with 0=False and 1=True

# For example, the following installs CUDA 11.7 to ~/local/cuda-11.7 and exports the path to your .bashrc

bash install_cuda.sh 117 ~/local 1
```

After running this my code was compiling without any issues
