### ISSUE TITLE
CUDA_SETUP: WARNING! libcudart.so not found in any environmental path

### ISSUE THREAD

**Issue by Shedarin** [TimDettmers/bitsandbytes#128]
I US **WINDOWS**, NOT _LINUX_ . I am 100% sure that the problem is not in [kohya-ss/sd-scripts.](https://github.com/kohya-ss/sd-scripts/issues/89) and not in https://github.com/derrian-distro/LoRA_Easy_Training_Scripts.  I tried to train LoRA with this script https://github.com/derrian-distro/LoRA_Easy_Training_Scripts but got an error: 

CUDA_SETUP: WARNING! libcudart.so not found in any environmental path. Searching /usr/local/cuda/lib64...
C:\Artem\ai\SD-вещи\kohya-ss-sd-scripts\sd-scripts\venv\lib\site-packages\bitsandbytes\cuda_setup\paths.py:27: UserWarning: WARNING: The following directories listed in your path were found to be non-existent: {WindowsPath('/usr/local/cuda/lib64')}
  warn(
WARNING: No libcudart.so found! Install CUDA or the cudatoolkit package (anaconda)!
CUDA SETUP: Loading binary C:\Artem\ai\SD-вещи\kohya-ss-sd-scripts\sd-scripts\venv\lib\site-packages\bitsandbytes\libbitsandbytes_cudaall.so...
Traceback (most recent call last):
  File "C:\Artem\ai\SD-вещи\kohya-ss-sd-scripts\sd-scripts\lora_train_popup.py", line 535, in <module>
    main()
  File "C:\Artem\ai\SD-вещи\kohya-ss-sd-scripts\sd-scripts\lora_train_popup.py", line 203, in main
    train_network.train(args)
  File "C:\Artem\ai\SD-вещи\kohya-ss-sd-scripts\sd-scripts\train_network.py", line 134, in train
    import bitsandbytes as bnb
  File "C:\Artem\ai\SD-вещи\kohya-ss-sd-scripts\sd-scripts\venv\lib\site-packages\bitsandbytes\__init__.py", line 6, in <module>
    from .autograd._functions import (
  File "C:\Artem\ai\SD-вещи\kohya-ss-sd-scripts\sd-scripts\venv\lib\site-packages\bitsandbytes\autograd\_functions.py", line 5, in <module>
    import bitsandbytes.functional as F
  File "C:\Artem\ai\SD-вещи\kohya-ss-sd-scripts\sd-scripts\venv\lib\site-packages\bitsandbytes\functional.py", line 13, in <module>
    from .cextension import COMPILED_WITH_CUDA, lib
  File "C:\Artem\ai\SD-вещи\kohya-ss-sd-scripts\sd-scripts\venv\lib\site-packages\bitsandbytes\cextension.py", line 43, in <module>
    lib = CUDALibrary_Singleton.get_instance().lib
  File "C:\Artem\ai\SD-вещи\kohya-ss-sd-scripts\sd-scripts\venv\lib\site-packages\bitsandbytes\cextension.py", line 39, in get_instance
    cls._instance.initialize()
  File "C:\Artem\ai\SD-вещи\kohya-ss-sd-scripts\sd-scripts\venv\lib\site-packages\bitsandbytes\cextension.py", line 33, in initialize
    self.lib = ct.cdll.LoadLibrary(str(binary_path))            # $$$
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python310\lib\ctypes\__init__.py", line 452, in LoadLibrary
    return self._dlltype(name)
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python310\lib\ctypes\__init__.py", line 374, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: [WinError 193] %1 ist keine zulässige Win32-Anwendung
Traceback (most recent call last):
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Artem\ai\SD-вещи\kohya-ss-sd-scripts\sd-scripts\venv\Scripts\accelerate.exe\__main__.py", line 7, in <module>
  File "C:\Artem\ai\SD-вещи\kohya-ss-sd-scripts\sd-scripts\venv\lib\site-packages\accelerate\commands\accelerate_cli.py", line 45, in main
    args.func(args)
  File "C:\Artem\ai\SD-вещи\kohya-ss-sd-scripts\sd-scripts\venv\lib\site-packages\accelerate\commands\launch.py", line 1104, in launch_command
    simple_launcher(args)
  File "C:\Artem\ai\SD-вещи\kohya-ss-sd-scripts\sd-scripts\venv\lib\site-packages\accelerate\commands\launch.py", line 567, in simple_launcher
    raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)
subprocess.CalledProcessError: Command '['C:\\Artem\\ai\\SD-вещи\\kohya-ss-sd-scripts\\sd-scripts\\venv\\Scripts\\python.exe', 'lora_train_popup.py']' returned non-zero exit status 1.

BUT I HAVE ALREASY downloaded CUDA, I had uninstalled CUDA 12 and downloaded version 11.6 and cuDNN v8.7.0 but it still didn't help. I also have anaconda installed.

As far as I know /usr/local/cuda/lib64 and libcudart.so are somehow related to Linux, but I have Windows

the command:
git clone https://github.com/TimDettmers/bitsandbytes.git
cd bitsandbytes
CUDA_VERSION=120 make cuda11x
python setup.py install
does not help because, command CUDA_VERSION=120 make cuda11x does not exist.

This method won't help because it's DAMN LINUX:
LD_LIBRARY_PATH=/usr/local/cuda/lib64/:$LD_LIBRARY_PATH

P.S. this method doesn't help either: https://github.com/james-things/bitsandbytes-prebuilt-all_arch

and I repeat again, I have WINDOWS, NOT LINUX

**Comment by etherealxx** [comment]
i got this too when running on colab https://colab.research.google.com/github/Linaqruf/kohya-trainer/blob/main/kohya-LoRA-dreambooth.ipynb

**Comment by abhinavkulkarni** [comment]
I also get this with the latest versions of `bitsandbytes`, `accelerate` and `transformers`. Simply trying to import bitsandbytes results in this error.

**Comment by TechniumUnlimited** [comment]
Is the library meant to work on Windows

**Comment by Northloop** [comment]
@Shedarin @etherealxx @abhinavkulkarni has anyone found anything that works for this in the last two weeks?

**Comment by etherealxx** [comment]
> @Shedarin @etherealxx @abhinavkulkarni has anyone found anything that works for this in the last two weeks?
Mine works. Tried just yesterday.

**Comment by SaltyBarnacles** [comment]
Has anyone found a fix?

**Comment by deviandice** [comment]
I fixed this by making the following modifications in WSL.
Simply replace the functions in cudaSetup/main.py replace with these, it just does an extra search at the location if you already know it. You can find the paths by using the commands
```
cd /
sudo find -iname "libcudart.so" #  
sudo find -iname "libcuda.so"

```
def check_cuda_result(cuda, result_val):
    # 3. Check for CUDA errors
    if result_val != 0:
        error_str = ctypes.c_char_p()
        cuda.cuGetErrorString(result_val, ctypes.byref(error_str))
        print(f"CUDA exception! Error code: {error_str.value.decode()}")

def get_cuda_version(cuda, cudart_path):
    # https://docs.nvidia.com/cuda/cuda-runtime-api/group__CUDART____VERSION.html#group__CUDART____VERSION
    try:
        cudart = ctypes.CDLL(cudart_path)
		try:
            cuda = ctypes.CDLL("path to libcudart.so") #  Change the path to be the exact location of libcudart.so
    	except OSError:
        	# TODO: shouldn't we error or at least warn here?
        	print(f'ERROR: libcudart.so could not be read from path: {cudart_path}!')
        	return None

    version = ctypes.c_int()
    check_cuda_result(cuda, cudart.cudaRuntimeGetVersion(ctypes.byref(version)))
    version = int(version.value)
    major = version//1000
    minor = (version-(major*1000))//10

    if major < 11:
       print('CUDA SETUP: CUDA version lower than 11 are currenlty not supported for LLM.int8(). You will be only to use 8-bit optimizers and quantization routines!!')

    return f'{major}{minor}'

def get_cuda_lib_handle():
    # 1. find libcuda.so library (GPU driver) (/usr/lib)
    try:
        cuda = ctypes.CDLL("libcuda.so")
    except OSError:
        # 2. try looking in alternate path (/usr/lib/wsl/lib/libcuda.so)
        try:
            cuda = ctypes.CDLL("path to libcuda.so") #  Change the path to be the exact location of libcuda.so
        except OSError:
            # TODO: shouldn't we error or at least warn here?
            print('CUDA SETUP: WARNING! libcuda.so not found! Do you have a CUDA driver installed? If you are on a cluster, make sure you are on a CUDA machine!')
            return None
    check_cuda_result(cuda, cuda.cuInit(0))

    return cuda
```

**Comment by wdhameli0** [comment]
i fixed this by replacing 'libcuda.so' to 'libbitsandbytes_cuda118.so' in main.py of cuda_setup.

**Comment by LLLYF** [comment]
> 我通过在cuda_setup main.py 中将“libcuda.so”替换为“libbitsandbytes_cuda118.so”来解决此问

Excuse me sir , could please tell me how to check the name that own myself.

**Comment by wdhameli0** [comment]
> > 我通过在cuda_setup main.py 中将“libcuda.so”替换为“libbitsandbytes_cuda118.so”来解决此问
> 
> Excuse me sir , could please tell me how to check the name that own myself.

You could check .../Python/Lib/site-packages/bitsandbytes, in this directory, you can find the "libbitsandbytes_cuda(XXX).so". Then get into /cuda_setup, open the main.py.  Find "def get_cuda_lib_handle() , replacing libcuda.so to libbitsandbytes_cuda(XXX).so

**Comment by LLLYF** [comment]
> > > 我通过在cuda_setup main.py 中将“libcuda.so”替换为“libbitsandbytes_cuda118.so”来解决此问
> > 
> > 
> > Excuse me sir , could please tell me how to check the name that own myself.
> 
> You could check .../Python/Lib/site-packages/bitsandbytes, in this directory, you can find the "libbitsandbytes_cuda(XXX).so". Then get into /cuda_setup, open the main.py. Find "def get_cuda_lib_handle() , replacing libcuda.so to libbitsandbytes_cuda(XXX).so

Thanks sir! I just got them, and I change the name like "libbitsandbytes_cuda117.so", 'libbitsandbytes_cuda118.so', 'libbitsandbytes_cuda120.so' but it does not work. My cuda is 12.1

**Comment by wdhameli0** [comment]
> > > > 我通过在cuda_setup main.py 中将“libcuda.so”替换为“libbitsandbytes_cuda118.so”来解决此问
> > > 
> > > 
> > > Excuse me sir , could please tell me how to check the name that own myself.
> > 
> > 
> > You could check .../Python/Lib/site-packages/bitsandbytes, in this directory, you can find the "libbitsandbytes_cuda(XXX).so". Then get into /cuda_setup, open the main.py. Find "def get_cuda_lib_handle() , replacing libcuda.so to libbitsandbytes_cuda(XXX).so
> 
> Thanks sir! I just got them, and I change the name like "libbitsandbytes_cuda117.so", 'libbitsandbytes_cuda118.so', 'libbitsandbytes_cuda120.so' but it does not work. My cuda is 12.1

I found this problem while using stable diffusion webui. My cuda is 12.1 too, but in stable diffusion webui ,it's
![33](https://user-images.githubusercontent.com/69758712/234812188-5b1f217f-fbdc-4de3-a421-c30d27b1daff.png)

**Comment by wdhameli0** [comment]
> > > > 我通过在cuda_setup main.py 中将“libcuda.so”替换为“libbitsandbytes_cuda118.so”来解决此问
> > > 
> > > 
> > > Excuse me sir , could please tell me how to check the name that own myself.
> > 
> > 
> > You could check .../Python/Lib/site-packages/bitsandbytes, in this directory, you can find the "libbitsandbytes_cuda(XXX).so". Then get into /cuda_setup, open the main.py. Find "def get_cuda_lib_handle() , replacing libcuda.so to libbitsandbytes_cuda(XXX).so
> 
> Thanks sir! I just got them, and I change the name like "libbitsandbytes_cuda117.so", 'libbitsandbytes_cuda118.so', 'libbitsandbytes_cuda120.so' but it does not work. My cuda is 12.1

after replacing 'libcuda.so' to 'libbitsandbytes_cuda118.so', 
![44](https://user-images.githubusercontent.com/69758712/234813018-5a3f325c-bb44-4455-9b63-49c9845a6bd9.png)

**Comment by LLLYF** [comment]
> > > > > 我通过在cuda_setup main.py 中将“libcuda.so”替换为“libbitsandbytes_cuda118.so”来解决此问
> > > > 
> > > > 
> > > > Excuse me sir , could please tell me how to check the name that own myself.
> > > 
> > > 
> > > You could check .../Python/Lib/site-packages/bitsandbytes, in this directory, you can find the "libbitsandbytes_cuda(XXX).so". Then get into /cuda_setup, open the main.py. Find "def get_cuda_lib_handle() , replacing libcuda.so to libbitsandbytes_cuda(XXX).so
> > 
> > 
> > Thanks sir! I just got them, and I change the name like "libbitsandbytes_cuda117.so", 'libbitsandbytes_cuda118.so', 'libbitsandbytes_cuda120.so' but it does not work. My cuda is 12.1
> 
> I found this problem while using stable diffusion webui. My cuda is 12.1 too, but in stable diffusion webui ,it's ![33](https://user-images.githubusercontent.com/69758712/234812188-5b1f217f-fbdc-4de3-a421-c30d27b1daff.png)



> > > > > 我通过在cuda_setup main.py 中将“libcuda.so”替换为“libbitsandbytes_cuda118.so”来解决此问
> > > > 
> > > > 
> > > > Excuse me sir , could please tell me how to check the name that own myself.
> > > 
> > > 
> > > You could check .../Python/Lib/site-packages/bitsandbytes, in this directory, you can find the "libbitsandbytes_cuda(XXX).so". Then get into /cuda_setup, open the main.py. Find "def get_cuda_lib_handle() , replacing libcuda.so to libbitsandbytes_cuda(XXX).so
> > 
> > 
> > Thanks sir! I just got them, and I change the name like "libbitsandbytes_cuda117.so", 'libbitsandbytes_cuda118.so', 'libbitsandbytes_cuda120.so' but it does not work. My cuda is 12.1
> 
> after replacing 'libcuda.so' to 'libbitsandbytes_cuda118.so', ![44](https://user-images.githubusercontent.com/69758712/234813018-5a3f325c-bb44-4455-9b63-49c9845a6bd9.png)

Stable diffusion should not change these files... While I change them as you did, the same problem was came out.

> > > > > 我通过在cuda_setup main.py 中将“libcuda.so”替换为“libbitsandbytes_cuda118.so”来解决此问
> > > > 
> > > > 
> > > > Excuse me sir , could please tell me how to check the name that own myself.
> > > 
> > > 
> > > You could check .../Python/Lib/site-packages/bitsandbytes, in this directory, you can find the "libbitsandbytes_cuda(XXX).so". Then get into /cuda_setup, open the main.py. Find "def get_cuda_lib_handle() , replacing libcuda.so to libbitsandbytes_cuda(XXX).so
> > 
> > 
> > Thanks sir! I just got them, and I change the name like "libbitsandbytes_cuda117.so", 'libbitsandbytes_cuda118.so', 'libbitsandbytes_cuda120.so' but it does not work. My cuda is 12.1
> 
> after replacing 'libcuda.so' to 'libbitsandbytes_cuda118.so', ![44](https://user-images.githubusercontent.com/69758712/234813018-5a3f325c-bb44-4455-9b63-49c9845a6bd9.png)

Stable diffusion should not change these files... While I change them as you did, the same problem was came out.

**Comment by Cebtenzzre** [comment]
I am on Arch Linux, and I am not using anaconda. I have libcudart.so in `/opt/cuda/targets/x86_64-linux/lib`, but bitsandbytes searches LD_LIBRARY_PATH even though the path is only added via `/etc/ld.so.conf.d/cuda.conf`. Why can't it fall back to a simple `ctypes.CDLL('libcudart.so')`, which works fine?

**Comment by bruce2233** [comment]
Same error. I have sovled by the following commands.
```bash
git clone https://github.com/TimDettmers/bitsandbytes.git
cd bitsandbytes
CUDA_VERSION=118 make cuda11x
python setup.py install
```
Hope Helpful

**Comment by crash1011** [comment]
Hi all, I also have this issue in the Windows native environment.

As far as as I'm concerned: WSL is a Linux env inside Windows and not Windows proper.

The linux CLI commands (curl;cd;make) above are addressing a Linux/WSL issue not the Windows native issue. 

Hoping that might steer things in the right direction.

**Comment by 1NoobPlayer** [comment]
> Same error. I have sovled by the following commands.
> 
> ```shell
> git clone https://github.com/TimDettmers/bitsandbytes.git
> cd bitsandbytes
> CUDA_VERSION=118 make cuda11x
> python setup.py install
> ```
> 
> Hope Helpful

Thanks! But where do we execute this command?

**Comment by lata22** [comment]
So Ihave a similar issue and then reading the readme.md from this repo I found that WINDOWS IS NOT SUPPORTED AT THE MOMENT XD, (and yes I´m using windows 11)
https://github.com/TimDettmers/bitsandbytes#requirements--installation

**Comment by batman9234** [comment]
> So Ihave a similar issue and then reading the readme.md from this repo I found that WINDOWS IS NOT SUPPORTED AT THE MOMENT XD, (and yes I´m using windows 11) https://github.com/TimDettmers/bitsandbytes#requirements--installation

I tried this in windows system with cuda 11.7, still broken LMAO

**Comment by bones0** [comment]
Yes, still broken. Not sure what the implications are. I have several problems with the current version of the stablediffusion webui commit 5ef669de080814067961f28357256e8fe27544f4 (HEAD -> master, tag: v1.6.0, origin/release_candidate, origin/master, origin/HEAD). One of them is trying to train anything on model 2.x or sd-xl inevitably ends in a disaster but also ending up with all-black images and all sorts of warnings. Some issues with half() which should be fixed by using --no-half, but 12GB of VRAM can't hold the sd-xl in full so it's not fixable in my case. And the NAN-issue which goes away by disabling the check which, however, does not fix anything the check is meant to prevent. Not sure what is related to bitsandbytes just not supporting Windows and what not but Windows support would indeed be appreciated ;) In the meantime I'll see if I can set up dualboot and get it running in there (personally I prefer that over WSL; I am old-fashioned ;)

**Comment by bones0** [comment]
There is a fix for the webui-problem at https://github.com/AUTOMATIC1111/stable-diffusion-webui/issues/12948

> [lamarsha](https://github.com/lamarsha) commented [on Sep 1](https://github.com/AUTOMATIC1111/stable-diffusion-webui/issues/12948#issuecomment-1702504848)
> I got this same error when I was trying 1.6 RC - ran the below and seems to have fixed
> 
> pip install bitsandbytes-windows

So the webui-users (like me) can proceed.

**Comment by swumagic** [comment]
Bitsandbytes was not supported windows before, but my method can support windows.（yuhuang）
1  open folder J:\StableDiffusion\sdwebui，Click the address bar of the folder and enter CMD
or WIN+R, CMD  。enter，cd /d J:\StableDiffusion\sdwebui
2  J:\StableDiffusion\sdwebui\py310\python.exe -m pip uninstall bitsandbytes

3 J:\StableDiffusion\sdwebui\py310\python.exe -m pip uninstall bitsandbytes-windows

4 J:\StableDiffusion\sdwebui\py310\python.exe -m pip install https://github.com/jllllll/bitsandbytes-windows-webui/releases/download/wheels/bitsandbytes-0.41.1-py3-none-win_amd64.whl

Replace your SD venv directory file（python.exe Folder） here（J:\StableDiffusion\sdwebui\py310）

**Comment by DragonHawkAlpha** [comment]
I giot around this issue using:
venv\scripts\activate
Running setup.bat
Option 3 -> installing specific bitsandbytes
Option 3 -> Force install of 0.41.1
(I am using CUDA 11.8 -> 118)

**Comment by swumagic** [comment]
CUDA SETUP: PyTorch settings found: CUDA_VERSION=118
YOUR CUDA_VERSION=118+2.01,Roll back to this version, and the[sd_dreambooth_extension] plug-in library replaces this 10.31 version

[sd_dreambooth_extension]=https://github.com/d8ahazard/sd_dreambooth_extension/commit/d8e01e1fd13dd4b6afadbb0382875f905ee5f429.

Bitsandbytes was not supported windows before, but my method can support windows.（yuhuang）
1  open folder J:\StableDiffusion\sdwebui，Click the address bar of the folder and enter CMD
or WIN+R, CMD  。enter，cd /d J:\StableDiffusion\sdwebui
2  J:\StableDiffusion\sdwebui\py310\python.exe -m pip uninstall bitsandbytes

3 J:\StableDiffusion\sdwebui\py310\python.exe -m pip uninstall bitsandbytes-windows

4 J:\StableDiffusion\sdwebui\py310\python.exe -m pip install https://github.com/jllllll/bitsandbytes-windows-webui/releases/download/wheels/bitsandbytes-0.41.1-py3-none-win_amd64.whl

Replace your SD venv directory file（python.exe Folder） here（J:\StableDiffusion\sdwebui\py310）

OR you are  Linux distribution (Ubuntu, MacOS, etc.)system ,AND CUDA Version: 11.X.

Bitsandbytes can support ubuntu.（yuhuang）
1  open folder J:\StableDiffusion\sdwebui，Click the address bar of the folder and enter CMD
or WIN+R, CMD  。enter，cd /d J:\StableDiffusion\sdwebui
2  J:\StableDiffusion\sdwebui\py310\python.exe -m pip uninstall bitsandbytes

3 J:\StableDiffusion\sdwebui\py310\python.exe -m pip uninstall bitsandbytes-windows

4 J:\StableDiffusion\sdwebui\py310\python.exe -m pip install https://github.com/TimDettmers/bitsandbytes/releases/download/0.41.0/bitsandbytes-0.41.0-py3-none-any.whl

Replace your SD venv directory file（python.exe Folder） here（J:\StableDiffusion\sdwebui\py310）



hypothesis your SD IN pc(WINDOWS):C:\Users\muneer\stable-diffusion-webui

1 打开文件夹C:\Users\muneer\stable-diffusion-webui，点击文件夹地址栏输入CMD

或 WIN+R，输入， CMD ，输入，cd /d C:\Users\muneer\stable-diffusion-webui

2 输入，C:\Users\muneer\stable-diffusion-webui\venv\Scripts\python.exe -m pip uninstall bitsandbytes

3 输入， C:\Users\muneer\stable-diffusion-webui\venv\Scripts\python.exe -m pip uninstall bitsandbytes-windows

4 输入，C:\Users\muneer\stable-diffusion-webui\venv\Scripts\python.exe -m pip install [https://github.com/jllllll/bitsandbytes-windows-webui/releases/download/wheels /bitsandbytes-0.41.1-py3-none-win_amd64.whl](https://github.com/jllllll/bitsandbytes-windows-webui/releases/download/wheels/bitsandbytes-0.41.1-py3-none-win_amd64.whl)

**Comment by allo-** [comment]
I still have the issue with Ubuntu 22.04.
