### ISSUE TITLE
CUDA error when run bitsandbytes on V100

### ISSUE THREAD

**Issue by PeiqinSun** [TimDettmers/bitsandbytes#205]
I compiled from the source code on V100, and encountered an error message:
```
CUDA error: CUBLAS_STATUS_INVALID_VALUE when calling `cublasGemmEx( handle, opa, opb, m, n, k, &falpha, a, CUDA_R_16F, lda, b, CUDA_R_16F, ldb, &fbeta, c, CUDA_R_16F, ldc, CUDA_R_32F, CUBLAS_GEMM_DFALT_TENSOR_OP)
```
This detail is
```
  File "/data/envs/alpaca/lib/python3.7/site-packages/bitsandbytes-0.37.1-py3.7.egg/bitsandbytes/nn/modules.py", line 242, in forward
    out = bnb.matmul(x, self.weight, bias=self.bias, state=self.state)
  File "/data/envs/alpaca/lib/python3.7/site-packages/bitsandbytes-0.37.1-py3.7.egg/bitsandbytes/autograd/_functions.py", line 488, in matmul
    return MatMul8bitLt.apply(A, B, out, bias, state)
  File "/data/envs/alpaca/lib/python3.7/site-packages/bitsandbytes-0.37.1-py3.7.egg/bitsandbytes/autograd/_functions.py", line 390, in forward
    output = torch.nn.functional.linear(A_wo_outliers, state.CB.to(A.dtype))
RuntimeError: CUDA error: CUBLAS_STATUS_INVALID_VALUE when calling `cublasGemmEx( handle, opa, opb, m, n, k, &falpha, a, CUDA_R_16F, lda, b, CUDA_R_16F, ldb, &fbeta, c, CUDA_R_16F, ldc, CUDA_R_32F, CUBLAS_GEMM_DFALT_TENSOR_OP)`
```
Has anyone encountered this bug?

**Comment by TimDettmers** [comment]
I think this is an issue where you have multiple CUDA versions installed. Can you please provide the output of `python -m bitsandbytes`.

**Comment by PeiqinSun** [comment]
The issue has been resolved through install CUDA11.7

Tim Dettmers ***@***.***> 于2023年3月22日周三 07:32写道：
