### ISSUE TITLE
Load_in_8bit=True error

### ISSUE THREAD

**Issue by Jeevi10** [TimDettmers/bitsandbytes#259]
===================================BUG REPORT===================================
Welcome to bitsandbytes. For bug reports, please submit your error trace to: https://github.com/TimDettmers/bitsandbytes/issues
================================================================================
binary_path: C:\Users\jalagurajah\Anaconda3\envs\ASR_PEFt\lib\site-packages\bitsandbytes\cuda_setup\libbitsandbytes_cuda116.dll
CUDA SETUP: Loading binary C:\Users\jalagurajah\Anaconda3\envs\ASR_PEFt\lib\site-packages\bitsandbytes\cuda_setup\libbitsandbytes_cuda116.dll...
Loading model...
Error no kernel image is available for execution on the device at line 479 in file D:\ai\tool\bitsandbytes\csrc\ops.cu

**Comment by whitesay** [comment]
Have you solve this problem? I met the same problem

**Comment by Jeevi10** [comment]
I tried few solutions it seemed worked for me, I am using windows server 2022.

Pip install bitsandbytes-cuda116
if you are using windows pip install bitandbyts-windows
Ensure the correct version of CUDA is installed: Make sure you have installed CUDA 11.6 Toolkit (https://developer.nvidia.com/cuda-toolkit-archive) on your system, and the CUDA paths are set correctly in your environment variables.
I hope this helps

**Comment by whitesay** [comment]
已收到您的信件！

**Comment by whitesay** [comment]
已收到您的信件！

**Comment by whitesay** [comment]
已收到您的信件！

**Comment by Titus-von-Koeller** [comment]
Dear all,

Since the current release (last week, 8th of March) we now have official support for Windows 🎉 (which we did not have before) via

```
pip install bitsandbytes>=0.43.0
```

We're closing all old Windows issues and are asking everyone to try installing with this new version as outlined above and validate the install with `python -m bitsandbytes` which should spit out a bunch of stuff and then `SUCCESS`. Please let us know if everything worked correctly in [this new umbrella / catch-all issue](https://github.com/TimDettmers/bitsandbytes/issues/1131). Thanks 🤗
