### ISSUE TITLE
 Could not find the quantized model

### ISSUE THREAD

**Issue by sunkwolf** [TimDettmers/bitsandbytes#263]
I got this problem

```
Starting the web UI...
Warning: --cai-chat is deprecated. Use --chat instead.

===================================BUG REPORT===================================
Welcome to bitsandbytes. For bug reports, please submit your error trace to: https://github.com/TimDettmers/bitsandbytes/issues
================================================================================
CUDA SETUP: CUDA runtime path found: D:\oobabooga-windows\installer_files\env\bin\cudart64_110.dll
CUDA SETUP: Highest compute capability among GPUs detected: 7.5
CUDA SETUP: Detected CUDA version 117
CUDA SETUP: Loading binary D:\oobabooga-windows\installer_files\env\lib\site-packages\bitsandbytes\libbitsandbytes_cuda117.dll...
The following models are available:

1. facebook_opt-6.7b
2. vicuna-13b-GPTQ-4bit-128g

Which one do you want to load? 1-2

1

Loading facebook_opt-6.7b...
Could not find the quantized model in .pt or .safetensors format, exiting...
Presione una tecla para continuar . . .
```

**Comment by egormly** [comment]
same here.

**Comment by vallabhnatu** [comment]
I fixed it by removing the `--wbits 4 --groupsize 128` arguments required by Vicuna. It seems they are not compatible with other models.

**Comment by sunkwolf** [comment]
> I fixed it by removing the `--wbits 4 --groupsize 128` arguments required by Vicuna. It seems they are not compatible with other models.

Thx It works, but when you wana use Vicuda how dit you set it ?

**Comment by vallabhnatu** [comment]
> Thx It works, but when you wana use Vicuda how dit you set it ?

Unfortunately, I am getting out of memory issues even with all the optimizations. So, I cannot run it. These flags are required for the model though. What you can do is create a copy of the start-webui.bat file with these arguments. This bat file will only be used for launching Vicuna and the original one for launching other models.

**Comment by Ai-feier** [comment]
removing the --wbits 4 --groupsize 128 arguments required by Vicuna. 

I want to know how to do it.
