### ISSUE TITLE
CUDA Setup failed on cuda 12.1 docker

### ISSUE THREAD

**Issue by dz1iang** [TimDettmers/bitsandbytes#288]
will support  cuda 12.1 at recent，when use ngc pytorch:23.03-py3 env，get CUDA Setup failed

===================================BUG REPORT===================================
Welcome to bitsandbytes. For bug reports, please submit your error trace to: https://github.com/TimDettmers/bitsandbytes/issues
================================================================================
/usr/local/lib/python3.8/dist-packages/bitsandbytes/cuda_setup/main.py:136: UserWarning: WARNING: The following directories listed in your path were found to be non-existent: {PosixPath('/usr/local/nvidia/lib'), PosixPath('/usr/local/nvidia/lib64')}
  warn(msg)
CUDA SETUP: CUDA runtime path found: /usr/local/cuda-11/lib64/libcudart.so
CUDA SETUP: Highest compute capability among GPUs detected: 8.0
CUDA SETUP: Detected CUDA version 118
CUDA SETUP: Loading binary /usr/local/lib/python3.8/dist-packages/bitsandbytes/libbitsandbytes_cuda118.so...
libcusparse.so.11: cannot open shared object file: No such file or directory
CUDA SETUP: CUDA runtime path found: /usr/local/cuda-11/lib64/libcudart.so
CUDA SETUP: Highest compute capability among GPUs detected: 8.0
CUDA SETUP: Detected CUDA version 118
CUDA SETUP: Loading binary /usr/local/lib/python3.8/dist-packages/bitsandbytes/libbitsandbytes_cuda118.so...
libcusparse.so.11: cannot open shared object file: No such file or directory
CUDA SETUP: CUDA runtime path found: /usr/local/cuda-11/lib64/libcudart.so
CUDA SETUP: Highest compute capability among GPUs detected: 8.0
CUDA SETUP: Detected CUDA version 118
CUDA SETUP: Loading binary /usr/local/lib/python3.8/dist-packages/bitsandbytes/libbitsandbytes_cuda118.so...
libcusparse.so.11: cannot open shared object file: No such file or directory
CUDA SETUP: Something unexpected happened. Please compile from source:
git clone git@github.com:TimDettmers/bitsandbytes.git
cd bitsandbytes
CUDA_VERSION=118 make cuda11x
python setup.py install
Traceback (most recent call last):
  File "train_alpaca.py", line 12, in <module>
    from peft import (
  File "/usr/local/lib/python3.8/dist-packages/peft/__init__.py", line 22, in <module>
    from .mapping import MODEL_TYPE_TO_PEFT_MODEL_MAPPING, PEFT_TYPE_TO_CONFIG_MAPPING, get_peft_config, get_peft_model
  File "/usr/local/lib/python3.8/dist-packages/peft/mapping.py", line 16, in <module>
    from .peft_model import (
  File "/usr/local/lib/python3.8/dist-packages/peft/peft_model.py", line 31, in <module>
    from .tuners import AdaLoraModel, LoraModel, PrefixEncoder, PromptEmbedding, PromptEncoder
  File "/usr/local/lib/python3.8/dist-packages/peft/tuners/__init__.py", line 20, in <module>
    from .lora import LoraConfig, LoraModel
  File "/usr/local/lib/python3.8/dist-packages/peft/tuners/lora.py", line 39, in <module>
    import bitsandbytes as bnb
  File "/usr/local/lib/python3.8/dist-packages/bitsandbytes/__init__.py", line 7, in <module>
    from .autograd._functions import (
  File "/usr/local/lib/python3.8/dist-packages/bitsandbytes/autograd/__init__.py", line 1, in <module>
    from ._functions import undo_layout, get_inverse_transform_indices
  File "/usr/local/lib/python3.8/dist-packages/bitsandbytes/autograd/_functions.py", line 9, in <module>
    import bitsandbytes.functional as F
  File "/usr/local/lib/python3.8/dist-packages/bitsandbytes/functional.py", line 17, in <module>
    from .cextension import COMPILED_WITH_CUDA, lib
  File "/usr/local/lib/python3.8/dist-packages/bitsandbytes/cextension.py", line 22, in <module>
    raise RuntimeError('''
RuntimeError:
        CUDA Setup failed despite GPU being available. Inspect the CUDA SETUP outputs above to fix your environment!
        If you cannot find any issues and suspect a bug, please open an issue with detals about your environment:
        https://github.com/TimDettmers/bitsandbytes/issues

**Comment by TimDettmers** [comment]
Can you please upgrade to `pip install -U bitsandbytes`. If it still does not work, please report the output of `python -m bitsandbytes`. The output of that would be super helpful to fix your docker issue and fix docker issues for everyone else. Thank you!

**Comment by dz1iang** [comment]
hi， use pip install -U bitsandbytes to update，got the errro 
> 

===================================BUG REPORT===================================
Welcome to bitsandbytes. For bug reports, please run

python -m bitsandbytes

 and submit this information together with your error trace to: https://github.com/TimDettmers/bitsandbytes/issues
================================================================================
bin /usr/local/lib/python3.8/dist-packages/bitsandbytes/libbitsandbytes_cuda118.so
/usr/local/lib/python3.8/dist-packages/bitsandbytes/cuda_setup/main.py:145: UserWarning: WARNING: The following directories listed in your path were found to be non-existent: {PosixPath('/usr/local/nvidia/lib64'), PosixPath('/usr/local/nvidia/lib')}
  warn(msg)
CUDA SETUP: CUDA runtime path found: /usr/local/cuda-11/lib64/libcudart.so.11.0
CUDA SETUP: Highest compute capability among GPUs detected: 8.0
CUDA SETUP: Detected CUDA version 118
CUDA SETUP: Loading binary /usr/local/lib/python3.8/dist-packages/bitsandbytes/libbitsandbytes_cuda118.so...
libcusparse.so.11: cannot open shared object file: No such file or directory
CUDA SETUP: Something unexpected happened. Please compile from source:
git clone git@github.com:TimDettmers/bitsandbytes.git
cd bitsandbytes
CUDA_VERSION=118 make cuda11x
python setup.py install
Traceback (most recent call last):
  File "train_alpaca_torch_2.py", line 12, in <module>
    from peft import (
  File "/usr/local/lib/python3.8/dist-packages/peft/__init__.py", line 22, in <module>
    from .mapping import MODEL_TYPE_TO_PEFT_MODEL_MAPPING, PEFT_TYPE_TO_CONFIG_MAPPING, get_peft_config, get_peft_model
  File "/usr/local/lib/python3.8/dist-packages/peft/mapping.py", line 16, in <module>
    from .peft_model import (
  File "/usr/local/lib/python3.8/dist-packages/peft/peft_model.py", line 31, in <module>
    from .tuners import AdaLoraModel, LoraModel, PrefixEncoder, PromptEmbedding, PromptEncoder
  File "/usr/local/lib/python3.8/dist-packages/peft/tuners/__init__.py", line 20, in <module>
    from .lora import LoraConfig, LoraModel
  File "/usr/local/lib/python3.8/dist-packages/peft/tuners/lora.py", line 39, in <module>
    import bitsandbytes as bnb
  File "/usr/local/lib/python3.8/dist-packages/bitsandbytes/__init__.py", line 7, in <module>
    from .autograd._functions import (
  File "/usr/local/lib/python3.8/dist-packages/bitsandbytes/autograd/__init__.py", line 1, in <module>
    from ._functions import undo_layout, get_inverse_transform_indices
  File "/usr/local/lib/python3.8/dist-packages/bitsandbytes/autograd/_functions.py", line 9, in <module>
    import bitsandbytes.functional as F
  File "/usr/local/lib/python3.8/dist-packages/bitsandbytes/functional.py", line 17, in <module>
    from .cextension import COMPILED_WITH_CUDA, lib
  File "/usr/local/lib/python3.8/dist-packages/bitsandbytes/cextension.py", line 20, in <module>
    raise RuntimeError('''
RuntimeError:
        CUDA Setup failed despite GPU being available. Inspect the CUDA SETUP outputs above to fix your environment!
        If you cannot find any issues and suspect a bug, please open an issue with detals about your environment:
        https://github.com/TimDettmers/bitsandbytes/issues

**Comment by LLLYF** [comment]
> hi， use pip install -U bitsandbytes to update，got the errro
> 
> > 
> 
> ===================================BUG REPORT=================================== Welcome to bitsandbytes. For bug reports, please run
> 
> python -m bitsandbytes
> 
> # and submit this information together with your error trace to: https://github.com/TimDettmers/bitsandbytes/issues
> bin /usr/local/lib/python3.8/dist-packages/bitsandbytes/libbitsandbytes_cuda118.so /usr/local/lib/python3.8/dist-packages/bitsandbytes/cuda_setup/main.py:145: UserWarning: WARNING: The following directories listed in your path were found to be non-existent: {PosixPath('/usr/local/nvidia/lib64'), PosixPath('/usr/local/nvidia/lib')} warn(msg) CUDA SETUP: CUDA runtime path found: /usr/local/cuda-11/lib64/libcudart.so.11.0 CUDA SETUP: Highest compute capability among GPUs detected: 8.0 CUDA SETUP: Detected CUDA version 118 CUDA SETUP: Loading binary /usr/local/lib/python3.8/dist-packages/bitsandbytes/libbitsandbytes_cuda118.so... libcusparse.so.11: cannot open shared object file: No such file or directory CUDA SETUP: Something unexpected happened. Please compile from source: git clone [git@github.com](mailto:git@github.com):TimDettmers/bitsandbytes.git cd bitsandbytes CUDA_VERSION=118 make cuda11x python setup.py install Traceback (most recent call last): File "train_alpaca_torch_2.py", line 12, in from peft import ( File "/usr/local/lib/python3.8/dist-packages/peft/**init**.py", line 22, in from .mapping import MODEL_TYPE_TO_PEFT_MODEL_MAPPING, PEFT_TYPE_TO_CONFIG_MAPPING, get_peft_config, get_peft_model File "/usr/local/lib/python3.8/dist-packages/peft/mapping.py", line 16, in from .peft_model import ( File "/usr/local/lib/python3.8/dist-packages/peft/peft_model.py", line 31, in from .tuners import AdaLoraModel, LoraModel, PrefixEncoder, PromptEmbedding, PromptEncoder File "/usr/local/lib/python3.8/dist-packages/peft/tuners/**init**.py", line 20, in from .lora import LoraConfig, LoraModel File "/usr/local/lib/python3.8/dist-packages/peft/tuners/lora.py", line 39, in import bitsandbytes as bnb File "/usr/local/lib/python3.8/dist-packages/bitsandbytes/**init**.py", line 7, in from .autograd._functions import ( File "/usr/local/lib/python3.8/dist-packages/bitsandbytes/autograd/**init**.py", line 1, in from ._functions import undo_layout, get_inverse_transform_indices File "/usr/local/lib/python3.8/dist-packages/bitsandbytes/autograd/_functions.py", line 9, in import bitsandbytes.functional as F File "/usr/local/lib/python3.8/dist-packages/bitsandbytes/functional.py", line 17, in from .cextension import COMPILED_WITH_CUDA, lib File "/usr/local/lib/python3.8/dist-packages/bitsandbytes/cextension.py", line 20, in raise RuntimeError(''' RuntimeError: CUDA Setup failed despite GPU being available. Inspect the CUDA SETUP outputs above to fix your environment! If you cannot find any issues and suspect a bug, please open an issue with detals about your environment: https://github.com/TimDettmers/bitsandbytes/issues

I have the same problem, is it the problem about windows?

**Comment by twang2218** [comment]
I got the same problem.

At first, **bitsandbytes** cannot find the `libcudart.so`, after digging into the issue, I solved the problem by set `LD_LIBRARY_PATH` to the location deep in the conda path.

```bash
export LD_LIBRARY_PATH=/root/miniconda/envs/vicuna/lib/python3.10/site-packages/nvidia/cuda_runtime/lib
```

And then I got this error message:

```
libcusparse.so.11: cannot open shared object file: No such file or directory
```

Then I installed the `nvidia-cusparse-cu11` for `libcusparse.so`:

```bash
$ pip install nvidia-cusparse-cu11
Collecting nvidia-cusparse-cu11
  Downloading nvidia_cusparse_cu11-11.7.5.86-py3-none-manylinux1_x86_64.whl (204.1 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 204.1/204.1 MB 12.0 MB/s eta 0:00:00
Installing collected packages: nvidia-cusparse-cu11
Successfully installed nvidia-cusparse-cu11-11.7.5.86
```

I still get the error by `python -m bitsandbytes`, so I extend the `LD_LIBRARY_PATH` to include the actual location for `libcusparse.so`.

```bash
$ find ~ | grep libcusparse
/root/miniconda/envs/vicuna/lib/python3.10/site-packages/nvidia/cusparse/lib/libcusparse.so.11
```

Add the path to `LD_LIBRARY_PATH`

```bash
export LD_LIBRARY_PATH=/root/miniconda/envs/vicuna/lib/python3.10/site-packages/nvidia/cuda_runtime/lib:/root/miniconda/envs/vicuna/lib/python3.10/site-packages/nvidia/cusparse/lib
```

After that, the error has gone.

```js
$ python -m bitsandbytes
...
CUDA SETUP: CUDA runtime path found: /root/miniconda/envs/vicuna/lib/python3.10/site-packages/nvidia/cuda_runtime/lib/libcudart.so.11.0
CUDA SETUP: Highest compute capability among GPUs detected: 8.6
CUDA SETUP: Detected CUDA version 117
CUDA SETUP: Loading binary /root/miniconda/envs/vicuna/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cuda117.so...
...
++++++++++++++++++ LD_LIBRARY CUDA PATHS +++++++++++++++++++
 /root/miniconda/envs/vicuna/lib/python3.10/site-packages/nvidia/cuda_runtime/lib CUDA PATHS

 /root/miniconda/envs/vicuna/lib/python3.10/site-packages/nvidia/cusparse/lib CUDA PATHS


++++++++++++++++++++++++++ OTHER +++++++++++++++++++++++++++
COMPILED_WITH_CUDA = True
COMPUTE_CAPABILITIES_PER_GPU = ['8.6']
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
++++++++++++++++++++++ DEBUG INFO END ++++++++++++++++++++++
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

Running a quick check that:
    + library is importable
    + CUDA function is callable


WARNING: Please be sure to sanitize sensible info from any such env vars!

SUCCESS!
Installation was successful!
```

So, my suggestion to the `bitsandbytes` project is that the during the search for the CUDA in the path, it might be good to search in all the subdirectories under the path.

https://github.com/TimDettmers/bitsandbytes/blob/main/bitsandbytes/cuda_setup/main.py#L193-L199
```python
def get_cuda_runtime_lib_paths(candidate_paths: Set[Path]) -> Set[Path]:
    paths = set()
    for libname in CUDA_RUNTIME_LIBS:
        for path in candidate_paths:
            if (path / libname).is_file():
                paths.add(path / libname)
    return paths
```

Only search `path / libname` may not find the installed binary library.

In my case, `libcudart.so.11.0` is not under `$CONDA_PREFIX/lib`, which is `/root/miniconda/envs/vicuna/lib`, it's in the deeper location, `/root/miniconda/envs/vicuna/lib/python3.10/site-packages/nvidia/cuda_runtime/lib`, it is the same for `libcusparse.so.11`, which is under `/root/miniconda/envs/vicuna/lib/python3.10/site-packages/nvidia/cusparse/lib`.

**Comment by swumagic** [comment]
Bitsandbytes was not supported windows before, but my method can support windows.（yuhuang）
1  open folder J:\StableDiffusion\sdwebui，Click the address bar of the folder and enter CMD
or WIN+R, CMD  。enter，cd /d J:\StableDiffusion\sdwebui
2  J:\StableDiffusion\sdwebui\py310\python.exe -m pip uninstall bitsandbytes

3 J:\StableDiffusion\sdwebui\py310\python.exe -m pip uninstall bitsandbytes-windows

4 J:\StableDiffusion\sdwebui\py310\python.exe -m pip install https://github.com/jllllll/bitsandbytes-windows-webui/releases/download/wheels/bitsandbytes-0.41.1-py3-none-win_amd64.whl

Replace your SD venv directory file（python.exe Folder） here（J:\StableDiffusion\sdwebui\py310）
