### ISSUE TITLE
CUDA Setup failed despite GPU being available. Inspect the CUDA SETUP outputs above to fix your environment!         If you cannot find any issues and suspect a bug, please open an issue with detals about your environment:

### ISSUE THREAD

**Issue by BasimBashir** [TimDettmers/bitsandbytes#305]
**Found this error while running the code cell in anaconda/jupyter notebook cell:**

===================================BUG REPORT===================================
Welcome to bitsandbytes. For bug reports, please submit your error trace to: https://github.com/TimDettmers/bitsandbytes/issues
================================================================================
CUDA_SETUP: WARNING! libcudart.so not found in any environmental path. Searching /usr/local/cuda/lib64...
CUDA SETUP: WARNING! libcuda.so not found! Do you have a CUDA driver installed? If you are on a cluster, make sure you are on a CUDA machine!
CUDA SETUP: Loading binary C:\Users\hp\anaconda3\lib\site-packages\bitsandbytes\libbitsandbytes_cpu.so...
argument of type 'WindowsPath' is not iterable
CUDA_SETUP: WARNING! libcudart.so not found in any environmental path. Searching /usr/local/cuda/lib64...
CUDA SETUP: WARNING! libcuda.so not found! Do you have a CUDA driver installed? If you are on a cluster, make sure you are on a CUDA machine!
CUDA SETUP: Loading binary C:\Users\hp\anaconda3\lib\site-packages\bitsandbytes\libbitsandbytes_cpu.so...
argument of type 'WindowsPath' is not iterable
CUDA_SETUP: WARNING! libcudart.so not found in any environmental path. Searching /usr/local/cuda/lib64...
CUDA SETUP: WARNING! libcuda.so not found! Do you have a CUDA driver installed? If you are on a cluster, make sure you are on a CUDA machine!
CUDA SETUP: Loading binary C:\Users\hp\anaconda3\lib\site-packages\bitsandbytes\libbitsandbytes_cpu.so...
argument of type 'WindowsPath' is not iterable
CUDA SETUP: Problem: The main issue seems to be that the main CUDA library was not detected.
CUDA SETUP: Solution 1): Your paths are probably not up-to-date. You can update them via: sudo ldconfig.
CUDA SETUP: Solution 2): If you do not have sudo rights, you can do the following:
CUDA SETUP: Solution 2a): Find the cuda library via: find / -name libcuda.so 2>/dev/null
CUDA SETUP: Solution 2b): Once the library is found add it to the LD_LIBRARY_PATH: export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:FOUND_PATH_FROM_2a
CUDA SETUP: Solution 2c): For a permanent solution add the export from 2b into your .bashrc file, located at ~/.bashrc
C:\Users\hp\anaconda3\lib\site-packages\bitsandbytes\cuda_setup\main.py:136: UserWarning: WARNING: The following directories listed in your path were found to be non-existent: {WindowsPath('C')}
  warn(msg)
C:\Users\hp\anaconda3\lib\site-packages\bitsandbytes\cuda_setup\main.py:136: UserWarning: C:\Users\hp\anaconda3 did not contain libcudart.so as expected! Searching further paths...
  warn(msg)
C:\Users\hp\anaconda3\lib\site-packages\bitsandbytes\cuda_setup\main.py:136: UserWarning: WARNING: The following directories listed in your path were found to be non-existent: {WindowsPath('/matplotlib_inline.backend_inline'), WindowsPath('module')}
  warn(msg)
C:\Users\hp\anaconda3\lib\site-packages\bitsandbytes\cuda_setup\main.py:136: UserWarning: WARNING: The following directories listed in your path were found to be non-existent: {WindowsPath('/usr/local/cuda/lib64')}
  warn(msg)
C:\Users\hp\anaconda3\lib\site-packages\bitsandbytes\cuda_setup\main.py:136: UserWarning: WARNING: No libcudart.so found! Install CUDA or the cudatoolkit package (anaconda)!
  warn(msg)
C:\Users\hp\anaconda3\lib\site-packages\bitsandbytes\cuda_setup\main.py:136: UserWarning: WARNING: No GPU detected! Check your CUDA paths. Proceeding to load CPU-only library...
  warn(msg)
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
~\AppData\Local\Temp\ipykernel_6552\728833551.py in <module>
      6 from datasets import load_dataset
      7 import datasets
----> 8 from peft import LoraConfig, get_peft_model, prepare_model_for_int8_training
      9 from torch.utils.data import IterableDataset
     10 from tqdm import tqdm

~\Desktop\Invictus Internship Projects\CallBot\ChatGPT-Decoded-GPT2-FAQ-Bot-RLHF-PPO-main\peft\src\peft\__init__.py in <module>
     20 __version__ = "0.3.0.dev0"
     21 
---> 22 from .mapping import MODEL_TYPE_TO_PEFT_MODEL_MAPPING, PEFT_TYPE_TO_CONFIG_MAPPING, get_peft_config, get_peft_model
     23 from .peft_model import (
     24     PeftModel,

~\Desktop\Invictus Internship Projects\CallBot\ChatGPT-Decoded-GPT2-FAQ-Bot-RLHF-PPO-main\peft\src\peft\mapping.py in <module>
     14 # limitations under the License.
     15 
---> 16 from .peft_model import (
     17     PeftModel,
     18     PeftModelForCausalLM,

~\Desktop\Invictus Internship Projects\CallBot\ChatGPT-Decoded-GPT2-FAQ-Bot-RLHF-PPO-main\peft\src\peft\peft_model.py in <module>
     29 from transformers.utils import PushToHubMixin
     30 
---> 31 from .tuners import AdaLoraModel, LoraModel, PrefixEncoder, PromptEmbedding, PromptEncoder
     32 from .utils import (
     33     TRANSFORMERS_MODELS_TO_PREFIX_TUNING_POSTPROCESS_MAPPING,

~\Desktop\Invictus Internship Projects\CallBot\ChatGPT-Decoded-GPT2-FAQ-Bot-RLHF-PPO-main\peft\src\peft\tuners\__init__.py in <module>
     18 # limitations under the License.
     19 
---> 20 from .lora import LoraConfig, LoraModel
     21 from .adalora import AdaLoraConfig, AdaLoraModel
     22 from .p_tuning import PromptEncoder, PromptEncoderConfig, PromptEncoderReparameterizationType

~\Desktop\Invictus Internship Projects\CallBot\ChatGPT-Decoded-GPT2-FAQ-Bot-RLHF-PPO-main\peft\src\peft\tuners\lora.py in <module>
     37 
     38 if is_bnb_available():
---> 39     import bitsandbytes as bnb
     40 
     41 

~\anaconda3\lib\site-packages\bitsandbytes\__init__.py in <module>
      5 
      6 from . import cuda_setup, utils
----> 7 from .autograd._functions import (
      8     MatmulLtState,
      9     bmm_cublas,

~\anaconda3\lib\site-packages\bitsandbytes\autograd\__init__.py in <module>
----> 1 from ._functions import undo_layout, get_inverse_transform_indices

~\anaconda3\lib\site-packages\bitsandbytes\autograd\_functions.py in <module>
      7 import torch
      8 
----> 9 import bitsandbytes.functional as F
     10 
     11 

~\anaconda3\lib\site-packages\bitsandbytes\functional.py in <module>
     15 from torch import Tensor
     16 
---> 17 from .cextension import COMPILED_WITH_CUDA, lib
     18 
     19 

~\anaconda3\lib\site-packages\bitsandbytes\cextension.py in <module>
     20         CUDASetup.get_instance().generate_instructions()
     21         CUDASetup.get_instance().print_log_stack()
---> 22         raise RuntimeError('''
     23         CUDA Setup failed despite GPU being available. Inspect the CUDA SETUP outputs above to fix your environment!
     24         If you cannot find any issues and suspect a bug, please open an issue with detals about your environment:

RuntimeError: 
        CUDA Setup failed despite GPU being available. Inspect the CUDA SETUP outputs above to fix your environment!
        If you cannot find any issues and suspect a bug, please open an issue with detals about your environment:
        https://github.com/TimDettmers/bitsandbytes/issues

i have pytorch installed with cuda enabled 
already have trained several models on gpu 
My GPU specs:

Wed Apr 12 11:33:20 2023       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 527.27       Driver Version: 527.27       CUDA Version: 12.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name            TCC/WDDM | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Quadro M2000M      WDDM  | 00000000:01:00.0 Off |                  N/A |
| N/A    0C    P8    N/A /  N/A |      0MiB /  4096MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|  No running processes found                                                 |
+-----------------------------------------------------------------------------+

Kindly help me debug this issue....... Thanks in advance.
​

**Comment by donote** [comment]
![image](https://user-images.githubusercontent.com/12215169/231418455-6f695130-7356-4d70-839b-f70f1d2824c1.png)

I also encountered the same problem

**Comment by clxyder** [comment]
Try adding the following to your `.bashrc`:

```
CUDA_HOME="/usr/local/cuda"
export PATH="${CUDA_HOME}/bin${PATH:+:$PATH}"
export LD_LIBRARY_PATH="/usr/local/cuda/lib64${LD_LIBRARY_PATH:+:$LD_LIBRARY_PATH}"
export LD_LIBRARY_PATH="/usr/lib/wsl/lib${LD_LIBRARY_PATH:+:$LD_LIBRARY_PATH}"
```

If I recall correctly, this is what helped me fix that issue.

**Comment by TimDettmers** [comment]
Thank you for your report on this issues. Please install the newest version of bitsandbytes with `pip install -U bitsandbytes`. If that does not solve your error, please provide the output of `python -m bitsandbytes` so I can help you. Thank you!

**Comment by blavania** [comment]
@TimDettmers Got same error as @donote above, here's the output of `python -m bitsandbytes`:

```
bin /root/miniconda3/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cpu.so
/root/miniconda3/lib/python3.10/site-packages/bitsandbytes/cextension.py:33: UserWarning: The installed version of bitsandbytes was compiled without GPU support. 8-bit optimizers, 8-bit multiplication, and GPU quantization are unavailable.
  warn("The installed version of bitsandbytes was compiled without GPU support. "
/root/miniconda3/lib/python3.10/site-packages/bitsandbytes/cuda_setup/main.py:145: UserWarning: /root/miniconda3 did not contain ['libcudart.so', 'libcudart.so.11.0', 'libcudart.so.12.0'] as expected! Searching further paths...
  warn(msg)
CUDA_SETUP: WARNING! libcudart.so not found in any environmental path. Searching in backup paths...
/root/miniconda3/lib/python3.10/site-packages/bitsandbytes/cuda_setup/main.py:145: UserWarning: WARNING: The following directories listed in your path were found to be non-existent: {PosixPath('/usr/local/cuda/lib64')}
  warn(msg)
/root/miniconda3/lib/python3.10/site-packages/bitsandbytes/cuda_setup/main.py:145: UserWarning: WARNING: No libcudart.so found! Install CUDA or the cudatoolkit package (anaconda)!
  warn(msg)
CUDA SETUP: Highest compute capability among GPUs detected: 6.1
CUDA SETUP: Detected CUDA version 117
/root/miniconda3/lib/python3.10/site-packages/bitsandbytes/cuda_setup/main.py:145: UserWarning: WARNING: Compute capability < 7.5 detected! Only slow 8-bit matmul is supported for your GPU!
  warn(msg)
CUDA SETUP: Loading binary /root/miniconda3/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cpu.so...
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
++++++++++++++++++ BUG REPORT INFORMATION ++++++++++++++++++
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

+++++++++++++++++++ ANACONDA CUDA PATHS ++++++++++++++++++++
/root/miniconda3/lib/python3.10/site-packages/torch/lib/libtorch_cuda_linalg.so
/root/miniconda3/lib/python3.10/site-packages/torch/lib/libc10_cuda.so
/root/miniconda3/lib/python3.10/site-packages/torch/lib/libtorch_cuda.so
/root/miniconda3/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cuda117.so
/root/miniconda3/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cuda121_nocublaslt.so
/root/miniconda3/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cuda115.so
/root/miniconda3/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cuda118.so
/root/miniconda3/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cuda114_nocublaslt.so
/root/miniconda3/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cuda113_nocublaslt.so
/root/miniconda3/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cuda114.so
/root/miniconda3/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cuda118_nocublaslt.so
/root/miniconda3/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cuda112.so
/root/miniconda3/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cuda111.so
/root/miniconda3/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cuda112_nocublaslt.so
/root/miniconda3/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cuda111_nocublaslt.so
/root/miniconda3/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cuda116.so
/root/miniconda3/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cuda113.so
/root/miniconda3/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cuda110.so
/root/miniconda3/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cuda110_nocublaslt.so
/root/miniconda3/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cuda116_nocublaslt.so
/root/miniconda3/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cuda115_nocublaslt.so
/root/miniconda3/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cuda102_nocublaslt.so
/root/miniconda3/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cuda121.so
/root/miniconda3/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cuda120_nocublaslt.so
/root/miniconda3/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cuda117_nocublaslt.so
/root/miniconda3/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cuda120.so
/root/miniconda3/envs/webui/lib/python3.10/site-packages/bitsandbytes-0.37.2-py3.10.egg/bitsandbytes/libbitsandbytes_cuda117.so
/root/miniconda3/envs/webui/lib/python3.10/site-packages/torch/lib/libtorch_cuda_linalg.so
/root/miniconda3/envs/webui/lib/python3.10/site-packages/torch/lib/libc10_cuda.so
/root/miniconda3/envs/webui/lib/python3.10/site-packages/torch/lib/libtorch_cuda.so
/root/miniconda3/envs/webui/lib/python3.10/site-packages/quant_cuda-0.0.0-py3.10-linux-x86_64.egg/quant_cuda.cpython-310-x86_64-linux-gnu.so
/root/miniconda3/envs/webui/lib/libcudart.so
/root/miniconda3/envs/webui/pkgs/cuda-toolkit/targets/x86_64-linux/lib/stubs/libcuda.so
/root/miniconda3/envs/webui/pkgs/cuda-toolkit/targets/x86_64-linux/lib/libcudart.so
/root/miniconda3/envs/webui/pkgs/cuda-toolkit/nsight-compute-2022.2.0/target/linux-desktop-glibc_2_11_3-x64/libcuda-injection.so
/root/miniconda3/envs/webui/pkgs/cuda-toolkit/nsight-compute-2022.2.0/target/linux-desktop-t210-a64/libcuda-injection.so
/root/miniconda3/envs/webui/pkgs/cuda-toolkit/nsight-compute-2022.2.0/target/linux-desktop-glibc_2_19_0-ppc64le/libcuda-injection.so

++++++++++++++++++ /usr/local CUDA PATHS +++++++++++++++++++


+++++++++++++++ WORKING DIRECTORY CUDA PATHS +++++++++++++++
/root/fast_txtgen/webui/text-generation-webui/repositories/GPTQ-for-LLaMa/build/lib.linux-x86_64-cpython-310/quant_cuda.cpython-310-x86_64-linux-gnu.so
/root/fast_txtgen/webui/bitsandbytes/bitsandbytes/libbitsandbytes_cuda117.so
/root/fast_txtgen/webui/bitsandbytes/build/lib/bitsandbytes/libbitsandbytes_cuda117.so

++++++++++++++++++ LD_LIBRARY CUDA PATHS +++++++++++++++++++
```

**Comment by TimDettmers** [comment]
CUDA_SETUP should look at `$CONDA_PREFIX/lib` for binaries, and one binary is found there. Did you activate the conda environment with `conda activate webui`?

**Comment by donote** [comment]
![image](https://user-images.githubusercontent.com/12215169/231629146-26778960-5647-4d6f-9dff-1e7840b5edaf.png)
Then i compile from source like this command, it's report error as the attach image.
```
git clone https://github.com/timdettmers/bitsandbytes.git
cd bitsandbytes

# CUDA_VERSIONS in {110, 111, 112, 113, 114, 115, 116, 117, 118, 119, 120, 120}
# make argument in {cuda110, cuda11x, cuda12x}
# if you do not know what CUDA you have, try looking at the output of: python -m bitsandbytes
CUDA_VERSION=117 make cuda11x
```

**Comment by donote** [comment]
and i add CUDA_HOME in front of the command, then output info like this, and finally it's looks like success.
![image](https://user-images.githubusercontent.com/12215169/231631559-f0d9aeda-06ad-4706-ad3c-2657f79d0859.png)

but then i use ```python -m bitsandbytes``` for checking, it failed again.
![image](https://user-images.githubusercontent.com/12215169/231631880-ee20a820-fa3e-4127-b3f1-dd0cc0fd9313.png)

**Comment by donote** [comment]
Hi I have resolute this problem. Uninstall all CUDA in the pc, and reinstall it, and reinstall conda, and reboot the pc.
then I install bitsandbytes just using:
```pip install bitsandbytes```
it's ok

**Comment by mrhan1993** [comment]
> Try adding the following to your `.bashrc`:
> 
> ```
> CUDA_HOME="/usr/local/cuda"
> export PATH="${CUDA_HOME}/bin${PATH:+:$PATH}"
> export LD_LIBRARY_PATH="/usr/local/cuda/lib64${LD_LIBRARY_PATH:+:$LD_LIBRARY_PATH}"
> export LD_LIBRARY_PATH="/usr/lib/wsl/lib${LD_LIBRARY_PATH:+:$LD_LIBRARY_PATH}"
> ```
> 
> If I recall correctly, this is what helped me fix that issue.

it's work for me

**Comment by mawenju203** [comment]
system：win10

![image](https://github.com/TimDettmers/bitsandbytes/assets/30227934/844d634c-885d-4bee-a64c-2194f64eddaf)

I also encountered the same problem；

**Comment by 13990008036** [comment]
Guys, I have completely resolved this issue on Ubuntu because the path in the virtual environment is not saved in the. bashrc file, but in the installation folder of Conda. We just need to delete the Conda installation folder first, then reinstall Conda, recreate the virtual environment, enter the following command to `export LD_ LIBRARY_ PATH=$LD_ LIBRARY_ PATH:/usr/local/cuda-11.7/lib64`

**Comment by yfangZhang** [comment]
![image](https://github.com/TimDettmers/bitsandbytes/assets/65322222/baff393a-f401-4c5d-a266-0c8b6852f452)
I meet the same problem.this is my  the output of python -m bitsandbytes

**Comment by swumagic** [comment]
Bitsandbytes was not supported windows before, but my method can support windows.（yuhuang）
1  open folder J:\StableDiffusion\sdwebui，Click the address bar of the folder and enter CMD
or WIN+R, CMD  。enter，cd /d J:\StableDiffusion\sdwebui
2  J:\StableDiffusion\sdwebui\py310\python.exe -m pip uninstall bitsandbytes

3 J:\StableDiffusion\sdwebui\py310\python.exe -m pip uninstall bitsandbytes-windows

4 J:\StableDiffusion\sdwebui\py310\python.exe -m pip install https://github.com/jllllll/bitsandbytes-windows-webui/releases/download/wheels/bitsandbytes-0.41.1-py3-none-win_amd64.whl

Replace your SD venv directory file（python.exe Folder） here（J:\StableDiffusion\sdwebui\py310）

**Comment by swumagic** [comment]
OR you are  Linux distribution (Ubuntu, MacOS, etc.)system ,AND CUDA Version: 11.X.

Bitsandbytes can support ubuntu.（yuhuang）
1  open folder J:\StableDiffusion\sdwebui，Click the address bar of the folder and enter CMD
or WIN+R, CMD  。enter，cd /d J:\StableDiffusion\sdwebui
2  J:\StableDiffusion\sdwebui\py310\python.exe -m pip uninstall bitsandbytes

3 J:\StableDiffusion\sdwebui\py310\python.exe -m pip uninstall bitsandbytes-windows

4 J:\StableDiffusion\sdwebui\py310\python.exe -m pip install https://github.com/TimDettmers/bitsandbytes/releases/download/0.41.0/bitsandbytes-0.41.0-py3-none-any.whl

Replace your SD venv directory file（python.exe Folder） here（J:\StableDiffusion\sdwebui\py310）

**Comment by MuhammadShifa** [comment]
Try this: it's worked for me in Window 10.
```
pip uninstall bitsandbytes
pip install https://github.com/jllllll/bitsandbytes-windows-webui/releases/download/wheels/bitsandbytes-0.41.0-py3-none-win_amd64.whl
```

**Comment by ZekonXK12** [comment]
> Try this: it's worked for me in Window 10.
> 
> ```
> pip uninstall bitsandbytes
> pip install https://github.com/jllllll/bitsandbytes-windows-webui/releases/download/wheels/bitsandbytes-0.41.0-py3-none-win_amd64.whl
> ```

Thanks a lot! Finally resolved by your help.

**Comment by younesbelkada** [comment]
We should be now supporting windows since we rely on CMake, could you try out the installation instructions on Windows from the official documentation: https://huggingface.co/docs/bitsandbytes/main/en/installation 

```bash
git clone https://github.com/TimDettmers/bitsandbytes.git && cd bitsandbytes/
pip install -r requirements-dev.txt
cmake -DCOMPUTE_BACKEND=cuda -S .
cmake --build . --config Release
python -m build --wheel
```

**Comment by Titus-von-Koeller** [comment]
Since the main issue is showing an issue that is related to Windows not being supported before, I'll be closing this issue as explained below:

---

Dear all,

Since the current release (last week, 8th of March) we now have official support for Windows 🎉 (which we did not have before) via

```
pip install bitsandbytes>=0.43.0
```

We're closing all old Windows issues and are asking everyone to try installing with this new version as outlined above and validate the install with `python -m bitsandbytes` which should spit out a bunch of stuff and then `SUCCESS`. Please let us know if everything worked correctly in [this new umbrella / catch-all issue](https://github.com/TimDettmers/bitsandbytes/issues/1131). Thanks 🤗

**Comment by skr3178** [comment]
In addition 
`apt-get install libcusparse11`

> Try adding the following to your `.bashrc`:
> 
> ```
> CUDA_HOME="/usr/local/cuda"
> export PATH="${CUDA_HOME}/bin${PATH:+:$PATH}"
> export LD_LIBRARY_PATH="/usr/local/cuda/lib64${LD_LIBRARY_PATH:+:$LD_LIBRARY_PATH}"
> export LD_LIBRARY_PATH="/usr/lib/wsl/lib${LD_LIBRARY_PATH:+:$LD_LIBRARY_PATH}"
> ```
> 
> If I recall correctly, this is what helped me fix that issue.
