### ISSUE TITLE
windows run minigpt4 error..

### ISSUE THREAD

**Issue by evan-me** [TimDettmers/bitsandbytes#325]
(minigpt4) C:\python workspace\MiniGPT-4>python -m bitsandbytes

===================================BUG REPORT===================================
Welcome to bitsandbytes. For bug reports, please run

python -m bitsandbytes

 and submit this information together with your error trace to: https://github.com/TimDettmers/bitsandbytes/issues
================================================================================
bin C:\Users\Evan-\.conda\envs\minigpt4\lib\site-packages\bitsandbytes\libbitsandbytes_cpu.so
C:\Users\Evan-\.conda\envs\minigpt4\lib\site-packages\bitsandbytes\cuda_setup\main.py:145: UserWarning: WARNING: The following directories listed in your path were found to be non-existent: {WindowsPath('C')}
  warn(msg)
C:\Users\Evan-\.conda\envs\minigpt4\lib\site-packages\bitsandbytes\cuda_setup\main.py:145: UserWarning: C:\Users\Evan-\.conda\envs\minigpt4 did not contain ['libcudart.so', 'libcudart.so.11.0', 'libcudart.so.12.0'] as expected! Searching further paths...
  warn(msg)
CUDA_SETUP: WARNING! libcudart.so not found in any environmental path. Searching in backup paths...
C:\Users\Evan-\.conda\envs\minigpt4\lib\site-packages\bitsandbytes\cuda_setup\main.py:145: UserWarning: WARNING: The following directories listed in your path were found to be non-existent: {WindowsPath('/usr/local/cuda/lib64')}
  warn(msg)
CUDA SETUP: WARNING! libcuda.so not found! Do you have a CUDA driver installed? If you are on a cluster, make sure you are on a CUDA machine!
C:\Users\Evan-\.conda\envs\minigpt4\lib\site-packages\bitsandbytes\cuda_setup\main.py:145: UserWarning: WARNING: No libcudart.so found! Install CUDA or the cudatoolkit package (anaconda)!
  warn(msg)
C:\Users\Evan-\.conda\envs\minigpt4\lib\site-packages\bitsandbytes\cuda_setup\main.py:145: UserWarning: WARNING: No GPU detected! Check your CUDA paths. Proceeding to load CPU-only library...
  warn(msg)
CUDA SETUP: Loading binary C:\Users\Evan-\.conda\envs\minigpt4\lib\site-packages\bitsandbytes\libbitsandbytes_cpu.so...
argument of type 'WindowsPath' is not iterable
CUDA SETUP: Problem: The main issue seems to be that the main CUDA library was not detected.
CUDA SETUP: Solution 1): Your paths are probably not up-to-date. You can update them via: sudo ldconfig.
CUDA SETUP: Solution 2): If you do not have sudo rights, you can do the following:
CUDA SETUP: Solution 2a): Find the cuda library via: find / -name libcuda.so 2>/dev/null
CUDA SETUP: Solution 2b): Once the library is found add it to the LD_LIBRARY_PATH: export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:FOUND_PATH_FROM_2a
CUDA SETUP: Solution 2c): For a permanent solution add the export from 2b into your .bashrc file, located at ~/.bashrc
Traceback (most recent call last):
  File "C:\Users\Evan-\.conda\envs\minigpt4\lib\runpy.py", line 188, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "C:\Users\Evan-\.conda\envs\minigpt4\lib\runpy.py", line 147, in _get_module_details
    return _get_module_details(pkg_main_name, error)
  File "C:\Users\Evan-\.conda\envs\minigpt4\lib\runpy.py", line 111, in _get_module_details
    __import__(pkg_name)
  File "C:\Users\Evan-\.conda\envs\minigpt4\lib\site-packages\bitsandbytes\__init__.py", line 6, in <module>
    from . import cuda_setup, utils, research
  File "C:\Users\Evan-\.conda\envs\minigpt4\lib\site-packages\bitsandbytes\research\__init__.py", line 1, in <module>
    from . import nn
  File "C:\Users\Evan-\.conda\envs\minigpt4\lib\site-packages\bitsandbytes\research\nn\__init__.py", line 1, in <module>
    from .modules import LinearFP8Mixed, LinearFP8Global
  File "C:\Users\Evan-\.conda\envs\minigpt4\lib\site-packages\bitsandbytes\research\nn\modules.py", line 8, in <module>
    from bitsandbytes.optim import GlobalOptimManager
  File "C:\Users\Evan-\.conda\envs\minigpt4\lib\site-packages\bitsandbytes\optim\__init__.py", line 6, in <module>
    from bitsandbytes.cextension import COMPILED_WITH_CUDA
  File "C:\Users\Evan-\.conda\envs\minigpt4\lib\site-packages\bitsandbytes\cextension.py", line 20, in <module>
    raise RuntimeError('''
RuntimeError:
        CUDA Setup failed despite GPU being available. Please run the following command to get more information:

        python -m bitsandbytes

        Inspect the output of the command and see if you can locate CUDA libraries. You might need to add them
        to your LD_LIBRARY_PATH. If you suspect a bug, please take the information from python -m bitsandbytes
        and open an issue at: https://github.com/TimDettmers/bitsandbytes/issues

**Comment by dangelo352** [comment]
i got the same issue

**Comment by xuyamu2023** [comment]
me either.

**Comment by mayyalove** [comment]
same issue

**Comment by aboycandoeverythingforgirl** [comment]
I have the same problem, can someone solve it?

**Comment by quartets** [comment]
I am also running MiniGPT-4 on Windows, and here is the error when I start the python demo.py program:

--------------------
C:\Users\Administrator\MiniGPT-4>python demo.py --cfg-path eval_configs/minigpt4_eval.yaml  --gpu-id 0
Initializing Chat
Loading VIT
Loading VIT Done
Loading Q-Former
Loading Q-Former Done
Loading LLAMA

===================================BUG REPORT===================================
Welcome to bitsandbytes. For bug reports, please submit your error trace to: https://github.com/TimDettmers/bitsandbytes/issues
================================================================================
binary_path: C:\Users\Administrator\MiniGPT-4\bitsandbytes-windows\bitsandbytes\cuda_setup\libbitsandbytes_cuda116.dll
CUDA SETUP: Loading binary C:\Users\Administrator\MiniGPT-4\bitsandbytes-windows\bitsandbytes\cuda_setup\libbitsandbytes_cuda116.dll...
Loading checkpoint shards:   0%|                                             | 0/2 [00:00<?, ?it/s]Error no kernel image is available for execution on the device at line 479 in file D:\ai\tool\bitsandbytes\csrc\ops.cu

------------------------
I am running it on Windows Server 2019 with a Nvidia V100 graphic card with 32GB of VRAM.
Nvidia driver: NVIDIA-SMI 518.03       Driver Version: 518.03       CUDA Version: 11.7
CUDA: Build cuda_11.7.r11.7/compiler.31294372_0
>>> torch.__version__
'1.13.1+cu117'
>>> torchvision.__version__
'0.14.1+cu117'
>>> torch.cuda.is_available()
True
>>> torch.zeros(1).cuda()
tensor([0.], device='cuda:0')

The cuda path had been set alright.

Anyone who has a clue or solved same error, please share your insight. 

Thanks.

**Comment by quartets** [comment]
My problem solved. It was the non-proper installation of bitsandbytes package.

I did an uninstall and then:

**Comment by quartets** [comment]
pip install https://github.com/acpopescu/bitsandbytes/releases/download/v0.37.2-win.1/bitsandbytes-0.37.2-py3-none-any.whl

Then the MiniGPT-4 can start without any futher error message.

Thanks to the redit post by @Oobabooga. 
https://www.reddit.com/r/Oobabooga/comments/12eniem/bitsandbytes_now_for_windows_8bit_cuda_functions/

**Comment by swumagic** [comment]
Bitsandbytes was not supported windows before, but my method can support windows.（yuhuang）
1  open folder J:\StableDiffusion\sdwebui，Click the address bar of the folder and enter CMD
or WIN+R, CMD  。enter，cd /d J:\StableDiffusion\sdwebui
2  J:\StableDiffusion\sdwebui\py310\python.exe -m pip uninstall bitsandbytes

3 J:\StableDiffusion\sdwebui\py310\python.exe -m pip uninstall bitsandbytes-windows

4 J:\StableDiffusion\sdwebui\py310\python.exe -m pip install https://github.com/jllllll/bitsandbytes-windows-webui/releases/download/wheels/bitsandbytes-0.41.1-py3-none-win_amd64.whl

Replace your SD venv directory file（python.exe Folder） here（J:\StableDiffusion\sdwebui\py310）
