### ISSUE TITLE
WSL CUDA install on Windows 10: GPU not detected

### ISSUE THREAD

**Issue by ksylvan** [TimDettmers/bitsandbytes#336]
# nvidia-smi output

```text
Sun Apr 23 01:54:14 2023
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 530.30.04              Driver Version: 531.29       CUDA Version: 12.1     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                  Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf            Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  NVIDIA GeForce RTX 4090         On | 00000000:01:00.0  On |                  Off |
|  0%   41C    P8               21W / 450W|    971MiB / 24564MiB |      1%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+----------------------+

+---------------------------------------------------------------------------------------+
| Processes:                                                                            |
|  GPU   GI   CI        PID   Type   Process name                            GPU Memory |
|        ID   ID                                                             Usage      |
|=======================================================================================|
|    0   N/A  N/A        27      G   /Xwayland                                 N/A      |
+---------------------------------------------------------------------------------------+
```

# Output of bitsandbytes startup

Followed the instructions in <https://github.com/oobabooga/text-generation-webui> `README.md` for the WSL
Conda install.

```
$ python -m bitsandbytes

===================================BUG REPORT===================================
Welcome to bitsandbytes. For bug reports, please run

python -m bitsandbytes

 and submit this information together with your error trace to: https://github.com/TimDettmers/bitsandbytes/issues
================================================================================
bin /home/kayvan/.miniconda3/envs/textgen/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cpu.so
/home/kayvan/.miniconda3/envs/textgen/lib/python3.10/site-packages/bitsandbytes/cextension.py:33: UserWarning: The installed version of bitsandbytes was compiled without GPU support. 8-bit optimizers, 8-bit multiplication, and GPU quantization are unavailable.
  warn("The installed version of bitsandbytes was compiled without GPU support. "
CUDA SETUP: WARNING! libcuda.so not found! Do you have a CUDA driver installed? If you are on a cluster, make sure you are on a CUDA machine!
CUDA SETUP: CUDA runtime path found: /home/kayvan/.miniconda3/envs/textgen/lib/libcudart.so.11.0
/home/kayvan/.miniconda3/envs/textgen/lib/python3.10/site-packages/bitsandbytes/cuda_setup/main.py:145: UserWarning: WARNING: No GPU detected! Check your CUDA paths. Proceeding to load CPU-only library...
  warn(msg)
CUDA SETUP: Loading binary /home/kayvan/.miniconda3/envs/textgen/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cpu.so...
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
++++++++++++++++++ BUG REPORT INFORMATION ++++++++++++++++++
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

+++++++++++++++++++ ANACONDA CUDA PATHS ++++++++++++++++++++
/home/kayvan/.miniconda3/envs/textgen/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cuda116_nocublaslt.so
/home/kayvan/.miniconda3/envs/textgen/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cuda113_nocublaslt.so
/home/kayvan/.miniconda3/envs/textgen/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cuda113.so
/home/kayvan/.miniconda3/envs/textgen/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cuda120_nocublaslt.so
/home/kayvan/.miniconda3/envs/textgen/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cuda118.so
/home/kayvan/.miniconda3/envs/textgen/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cuda112_nocublaslt.so
/home/kayvan/.miniconda3/envs/textgen/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cuda111_nocublaslt.so
/home/kayvan/.miniconda3/envs/textgen/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cuda102_nocublaslt.so
/home/kayvan/.miniconda3/envs/textgen/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cuda116.so
/home/kayvan/.miniconda3/envs/textgen/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cuda112.so
/home/kayvan/.miniconda3/envs/textgen/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cuda117_nocublaslt.so
/home/kayvan/.miniconda3/envs/textgen/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cuda121_nocublaslt.so
/home/kayvan/.miniconda3/envs/textgen/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cuda114.so
/home/kayvan/.miniconda3/envs/textgen/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cuda121.so
/home/kayvan/.miniconda3/envs/textgen/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cuda110_nocublaslt.so
/home/kayvan/.miniconda3/envs/textgen/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cuda110.so
/home/kayvan/.miniconda3/envs/textgen/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cuda115.so
/home/kayvan/.miniconda3/envs/textgen/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cuda118_nocublaslt.so
/home/kayvan/.miniconda3/envs/textgen/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cuda111.so
/home/kayvan/.miniconda3/envs/textgen/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cuda117.so
/home/kayvan/.miniconda3/envs/textgen/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cuda115_nocublaslt.so
/home/kayvan/.miniconda3/envs/textgen/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cuda114_nocublaslt.so
/home/kayvan/.miniconda3/envs/textgen/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cuda120.so
/home/kayvan/.miniconda3/envs/textgen/lib/python3.10/site-packages/torch/lib/libc10_cuda.so
/home/kayvan/.miniconda3/envs/textgen/lib/python3.10/site-packages/torch/lib/libtorch_cuda_linalg.so
/home/kayvan/.miniconda3/envs/textgen/lib/python3.10/site-packages/torch/lib/libtorch_cuda.so

++++++++++++++++++ /usr/local CUDA PATHS +++++++++++++++++++
/usr/local/cuda-12.1/targets/x86_64-linux/lib/libcudart.so
/usr/local/cuda-12.1/targets/x86_64-linux/lib/stubs/libcuda.so

+++++++++++++++ WORKING DIRECTORY CUDA PATHS +++++++++++++++


++++++++++++++++++ LD_LIBRARY CUDA PATHS +++++++++++++++++++
Traceback (most recent call last):
  File "/home/kayvan/.miniconda3/envs/textgen/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/kayvan/.miniconda3/envs/textgen/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/kayvan/.miniconda3/envs/textgen/lib/python3.10/site-packages/bitsandbytes/__main__.py", line 95, in <module>
    generate_bug_report_information()
  File "/home/kayvan/.miniconda3/envs/textgen/lib/python3.10/site-packages/bitsandbytes/__main__.py", line 66, in generate_bug_report_information
    lib_path = os.environ['LD_LIBRARY_PATH'].strip()
  File "/home/kayvan/.miniconda3/envs/textgen/lib/python3.10/os.py", line 680, in __getitem__
    raise KeyError(key) from None
KeyError: 'LD_LIBRARY_PATH'
```

I took extensive notes about each step of what I was doing:

# Started from scratch:

```sh
wsl --unregister ubuntu
```

And now re-install ubuntu:

```sh
wsl --install ubuntu
```

Go through the process of setting your username and password in the Linux system.

Set up /etc/sudoers.d/username

```sh
echo "username ALL=(ALL) NOPASSWD: ALL" | sudo tee /etc/sudoers.d/username
```

This is just for convenience, so the following sudo commands won't need a password.

```sh
sudo apt update && sudo apt -y upgrade
```

# Installing Conda

Now, installing Conda following the instructions here: <https://educe-ubc.github.io/conda.html>

```sh
curl -sL "https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh" > "Miniconda3.sh"
bash Miniconda3.sh
```

In the run, putting the base environment in `~/.minidonda3`, and saying `yes` to the
"Do you wish the installer to initialize Miniconda3" question and letting it modify `~/.bashrc`

Then logging out and running `bash` in Windows Powershell to get back to the terminal
with the conda environment. Continuing with the Miniconda install instructions:

```sh
cd $HOME
conda update conda
rm Miniconda3.sh
conda install wget
```

# Install build tools

```sh
sudo apt install -y build-essential
```

# Install CUDA libraries and tools

Start at <https://developer.nvidia.com/downloads> and click on `CUDA Toolkit` and click on `Download now`
and select `Linux`, `x86_64`, and `WSL-Ubuntu` - for installer type, choose `deb (network)`

Follow the steps there to set up the CUDA repository of packages.

```sh
wget https://developer.download.nvidia.com/compute/cuda/repos/wsl-ubuntu/x86_64/cuda-keyring_1.0-1_all.deb
sudo dpkg -i cuda-keyring_1.0-1_all.deb
sudo apt-get update && sudo apt-get -y upgrade
```

Now, install CUDA, following this tutorial:
<https://docs.nvidia.com/cuda/wsl-user-guide/index.html#getting-started-with-cuda-on-wsl>

```sh
sudo apt install -y cuda-toolkit-12
```

Add the following line to your `~/.bashrc` then exit and restart the WSL bash session. This is
so tools like `nvcc` can be found.

# Create a new Conda environment

```sh
conda create -n textgen python=3.10.9
conda activate textgen
pip install --upgrade pip
```

# Install Pytorch

Using the instructions here <https://pytorch.org/get-started/locally/> with the following
preferences:

- PyTorch Build: Stable (2.0.0)
- Your OS: Linux
- Package: Conda
- Language: Python
- Compute Platform: CUDA 11.8

```sh
conda install pytorch torchvision torchaudio pytorch-cuda=11.8 -c pytorch -c nvidia
```

Verify that Torch was installed:

```python
(textgen) kayvan@DESKTOP-8HJQF90:/mnt/c/Users/kayva/src/text-generation-webui$ python
Python 3.10.9 (main, Mar  8 2023, 10:47:38) [GCC 11.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import torch
>>> x = torch.rand(5, 3)
>>> print(x)
tensor([[0.2400, 0.4834, 0.5810],
        [0.8527, 0.7630, 0.2072],
        [0.9497, 0.7169, 0.4882],
        [0.8173, 0.9703, 0.5957],
        [0.0450, 0.8247, 0.9210]])
>>> torch.cuda.is_available()
True
>>>
```

# Install requirements via pip

If you haven't done so, clone the repo:

```sh
git clone https://github.com/oobabooga/text-generation-webui
```

Then go to the directory and install the requirements. Make sure you are in the `textgen` conda
environment.

```sh
cd text-generation-webui
pip install -r requirements.txt
```

**Comment by cleverblue** [comment]
modify fuction 

def get_compute_capabilities(cuda):
    """
    1. find libcuda.so library (GPU driver) (/usr/lib)
       init_device -> init variables -> call function by reference
    2. call extern C function to determine CC
       (https://docs.nvidia.com/cuda/cuda-driver-api/group__CUDA__DEVICE__DEPRECATED.html)
    3. Check for CUDA errors
       https://stackoverflow.com/questions/14038589/what-is-the-canonical-way-to-check-for-errors-using-the-cuda-runtime-api
    # bits taken from https://gist.github.com/f0k/63a664160d016a491b2cbea15913d549
    """

    nGpus = ct.c_int()
    cc_major = ct.c_int()
    cc_minor = ct.c_int()
    
    device = ct.c_int()

    check_cuda_result(cuda, cuda.cuDeviceGetCount(ct.byref(nGpus)))
    ccs = []
    print('get_compute_capabilities>=1',nGpus,device,cc_major,cc_minor)
    for i in range(nGpus.value+1):
        print('range....',i)
        check_cuda_result(cuda, cuda.cuDeviceGet(ct.byref(device), i))
        ref_major = ct.byref(cc_major)
        ref_minor = ct.byref(cc_minor)
        # 2. call extern C function to determine CC
        check_cuda_result(cuda, cuda.cuDeviceComputeCapability(ref_major, ref_minor, device))
        ccs.append(f"{torch.cuda.get_device_capability(device=device)[0]}.{torch.cuda.get_device_capability(device=device)[1]}")

    return ccs

**Comment by ksylvan** [comment]
Thanks @cleverblue for pointing me to the right solution.

**Comment by eucdee** [comment]
you closed it, is your guide fixing it? 
btw nice guide, i wish i found it 20h earlier xD
i wrote my own [guide](https://github.com/oobabooga/text-generation-webui/discussions/1797)
next time i make sure to check closed issues first :D

you forgot to tell what line to add the after
`add the following line to your ~/.bashrc then exit and restart the WSL bash session`

maybe you can verify my paths are correct.

**Comment by ksylvan** [comment]
Yes, my problem was fixed by my guide. @eucdee 

Your paths seem fine, the one that's important is `/usr/lib/wsl/lib` - in fact, that is *all* I need in LD_LIBRARY_PATH for things to work correctly.

**Comment by swumagic** [comment]
Bitsandbytes was not supported windows before, but my method can support windows.（yuhuang）
1  open folder J:\StableDiffusion\sdwebui，Click the address bar of the folder and enter CMD
or WIN+R, CMD  。enter，cd /d J:\StableDiffusion\sdwebui
2  J:\StableDiffusion\sdwebui\py310\python.exe -m pip uninstall bitsandbytes

3 J:\StableDiffusion\sdwebui\py310\python.exe -m pip uninstall bitsandbytes-windows

4 J:\StableDiffusion\sdwebui\py310\python.exe -m pip install https://github.com/jllllll/bitsandbytes-windows-webui/releases/download/wheels/bitsandbytes-0.41.1-py3-none-win_amd64.whl

Replace your SD venv directory file（python.exe Folder） here（J:\StableDiffusion\sdwebui\py310）

**Comment by swumagic** [comment]
OR you are  Linux distribution (Ubuntu, MacOS, etc.)system ,AND CUDA Version: 11.X.

Bitsandbytes can support ubuntu.（yuhuang）
1  open folder J:\StableDiffusion\sdwebui，Click the address bar of the folder and enter CMD
or WIN+R, CMD  。enter，cd /d J:\StableDiffusion\sdwebui
2  J:\StableDiffusion\sdwebui\py310\python.exe -m pip uninstall bitsandbytes

3 J:\StableDiffusion\sdwebui\py310\python.exe -m pip uninstall bitsandbytes-windows

4 J:\StableDiffusion\sdwebui\py310\python.exe -m pip install https://github.com/TimDettmers/bitsandbytes/releases/download/0.41.0/bitsandbytes-0.41.0-py3-none-any.whl

Replace your SD venv directory file（python.exe Folder） here（J:\StableDiffusion\sdwebui\py310）
