### ISSUE TITLE
cuda 122 - not compatible with current bitsandbbytes

### ISSUE THREAD

**Issue by krishna0125** [TimDettmers/bitsandbytes#551]
===================================BUG REPORT===================================
Welcome to bitsandbytes. For bug reports, please run

python -m bitsandbytes

 and submit this information together with your error trace to: https://github.com/TimDettmers/bitsandbytes/issues
================================================================================
bin /datadrive/anaconda3/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cuda122.so
False
CUDA_SETUP: WARNING! libcudart.so not found in any environmental path. Searching in backup paths...
CUDA SETUP: CUDA runtime path found: /usr/local/cuda/lib64/libcudart.so
CUDA SETUP: Highest compute capability among GPUs detected: 8.0
CUDA SETUP: Detected CUDA version 122
CUDA SETUP: Required library version not found: libbitsandbytes_cuda122.so. Maybe you need to compile it from source?
CUDA SETUP: Defaulting to libbitsandbytes_cpu.so...

how to compile it from source?

**Comment by nkeilar** [comment]
Did you find a solution @krishna0125

**Comment by krishna0125** [comment]
I did change my version of cuda to 12.0.1
then it worked.

**Comment by mattiasarro** [comment]
On ubuntu, you can install cuda 12.0 like this:

```
sudo apt-get install linux-headers-$(uname -r)
sudo apt-key del 7fa2af80
wget https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2204/x86_64/cuda-keyring_1.1-1_all.deb
sudo dpkg -i cuda-keyring_1.1-1_all.deb

sudo apt-get update
sudo apt-get install cuda-12-0 nvidia-gds

export PATH=/usr/local/cuda-12.0/bin${PATH:+:${PATH}}
export LD_LIBRARY_PATH=/usr/local/cuda-12.0/lib64${LD_LIBRARY_PATH:+:${LD_LIBRARY_PATH}}
```

nvidia-smi will still say CUDA Version: 12.2, but that's the maximum available version rather the one that will be used.

**Comment by X-McKay** [comment]
How do you specify an option abstract method in a baseclass

**Comment by matthewfranglen** [comment]
bitsandbytes 0.40.0.post4 includes libbitsandbytes_cuda122.so so I believe this ticket should be closed.

**Comment by TimDettmers** [comment]
@matthewfranglen is right: bitsandbytes did not support CUDA 12.2 until version 0.40.0.post4.

Upgrading via `pip install -U bitsandbytes` should resolve this issue. I will close this issue. Please reopen if upgrading does not resolve the error.

**Comment by Serdcoff** [comment]
I think you can find solution on https://docs.nvidia.com/cuda/cuda-installation-guide-linux/index.html
If you have 12.2 - do step by step install of CUDA and I think it will work. Had a same problem with bitsandbytes

**Comment by swumagic** [comment]
OR you are  Linux distribution (Ubuntu, MacOS, etc.)system ,AND CUDA Version: 11.X.

Bitsandbytes can support ubuntu.（yuhuang）
1  open folder J:\StableDiffusion\sdwebui，Click the address bar of the folder and enter CMD
or WIN+R, CMD  。enter，cd /d J:\StableDiffusion\sdwebui
2  J:\StableDiffusion\sdwebui\py310\python.exe -m pip uninstall bitsandbytes

3 J:\StableDiffusion\sdwebui\py310\python.exe -m pip uninstall bitsandbytes-windows

4 J:\StableDiffusion\sdwebui\py310\python.exe -m pip install https://github.com/TimDettmers/bitsandbytes/releases/download/0.41.0/bitsandbytes-0.41.0-py3-none-any.whl

Replace your SD venv directory file（python.exe Folder） here（J:\StableDiffusion\sdwebui\py310）

**Comment by swumagic** [comment]
OR you are  Linux distribution (Ubuntu, MacOS, etc.)system ,AND CUDA Version: 11.X.

Bitsandbytes can support ubuntu.（yuhuang）
1  open folder J:\StableDiffusion\sdwebui，Click the address bar of the folder and enter CMD
or WIN+R, CMD  。enter，cd /d J:\StableDiffusion\sdwebui
2  J:\StableDiffusion\sdwebui\py310\python.exe -m pip uninstall bitsandbytes

3 J:\StableDiffusion\sdwebui\py310\python.exe -m pip uninstall bitsandbytes-windows

4 J:\StableDiffusion\sdwebui\py310\python.exe -m pip install https://github.com/TimDettmers/bitsandbytes/releases/download/0.41.0/bitsandbytes-0.41.0-py3-none-any.whl

Replace your SD venv directory file（python.exe Folder） here（J:\StableDiffusion\sdwebui\py310）
