### ISSUE TITLE
RuntimeErrors: No executable batch size found, reached zero. & CUDA out of memory

### ISSUE THREAD

**Issue by christopher-w-murphy** [TimDettmers/bitsandbytes#554]
I’ve gotten this error — RuntimeError: No executable batch size found, reached zero. — running on both an AWS EC2 g5.2xlarge instance with CUDA 11.8, and a HuggingFace Nvidia A10G - small space with CUDA 11.3. I’ve tried bitsandbytes versions 0.37.2, 0.38.1, and 0.39.0. This happens with the 8-bit versions of the AdamW and Lion (v >= 0.38.0) optimizers. The trainer tries to auto-find the batch size, but it keeps cutting the batch size in half until it falls below one. Thanks for any help you can provide!

Below is the traceback and bug report for a run on a HuggingFace space.

Traceback (most recent call last):
  File "/home/user/.pyenv/versions/3.9.16/lib/python3.9/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 565, in _run_script
    exec(code, module.__dict__)
  File "/home/user/app/app.py", line 61, in <module>
    main()
  File "/home/user/app/app.py", line 56, in main
    app(session_state)
  File "/home/user/app/src/application/app_fine_tune_flan_t5.py", line 107, in app
    trainer.train()
  File "/home/user/.pyenv/versions/3.9.16/lib/python3.9/site-packages/transformers/trainer.py", line 1664, in train
    return inner_training_loop(
  File "/home/user/.pyenv/versions/3.9.16/lib/python3.9/site-packages/accelerate/utils/memory.py", line 122, in decorator
    raise RuntimeError("No executable batch size found, reached zero.")
RuntimeError: No executable batch size found, reached zero.

===================================BUG REPORT===================================
Welcome to bitsandbytes. For bug reports, please run

python -m bitsandbytes

 and submit this information together with your error trace to: https://github.com/TimDettmers/bitsandbytes/issues
================================================================================
bin /home/user/.pyenv/versions/3.9.16/lib/python3.9/site-packages/bitsandbytes/libbitsandbytes_cuda113.so
/home/user/.pyenv/versions/3.9.16/lib/python3.9/site-packages/bitsandbytes/cuda_setup/main.py:149: UserWarning: WARNING: The following directories listed in your path were found to be non-existent: {PosixPath('/usr/local/nvidia/lib'), PosixPath('/usr/local/nvidia/lib64')}
  warn(msg)
/home/user/.pyenv/versions/3.9.16/lib/python3.9/site-packages/bitsandbytes/cuda_setup/main.py:149: UserWarning: /usr/local/nvidia/lib:/usr/local/nvidia/lib64 did not contain ['libcudart.so', 'libcudart.so.11.0', 'libcudart.so.12.0'] as expected! Searching further paths...
  warn(msg)
/home/user/.pyenv/versions/3.9.16/lib/python3.9/site-packages/bitsandbytes/cuda_setup/main.py:149: UserWarning: WARNING: The following directories listed in your path were found to be non-existent: {PosixPath('chriswmurphy/llm-lion-finetuning')}
  warn(msg)
/home/user/.pyenv/versions/3.9.16/lib/python3.9/site-packages/bitsandbytes/cuda_setup/main.py:149: UserWarning: WARNING: The following directories listed in your path were found to be non-existent: {PosixPath('Europe/Paris')}
  warn(msg)
/home/user/.pyenv/versions/3.9.16/lib/python3.9/site-packages/bitsandbytes/cuda_setup/main.py:149: UserWarning: WARNING: The following directories listed in your path were found to be non-existent: {PosixPath('https'), PosixPath('//chriswmurphy-llm-lion-finetuning.hf.space')}
  warn(msg)
/home/user/.pyenv/versions/3.9.16/lib/python3.9/site-packages/bitsandbytes/cuda_setup/main.py:149: UserWarning: WARNING: The following directories listed in your path were found to be non-existent: {PosixPath('/usr/lib/pyenv/hooks'), PosixPath('/etc/pyenv.d'), PosixPath('/usr/local/etc/pyenv.d')}
  warn(msg)
/home/user/.pyenv/versions/3.9.16/lib/python3.9/site-packages/bitsandbytes/cuda_setup/main.py:149: UserWarning: WARNING: The following directories listed in your path were found to be non-existent: {PosixPath('//172.20.0.1'), PosixPath('tcp'), PosixPath('443')}
  warn(msg)
CUDA_SETUP: WARNING! libcudart.so not found in any environmental path. Searching in backup paths...
CUDA SETUP: CUDA runtime path found: /usr/local/cuda/lib64/libcudart.so
CUDA SETUP: Highest compute capability among GPUs detected: 8.6
CUDA SETUP: Detected CUDA version 113
CUDA SETUP: Loading binary /home/user/.pyenv/versions/3.9.16/lib/python3.9/site-packages/bitsandbytes/libbitsandbytes_cuda113.so...
/home/user/.pyenv/versions/3.9.16/lib/python3.9/site-packages/bitsandbytes/cuda_setup/main.py:149: UserWarning: Found duplicate ['libcudart.so', 'libcudart.so.11.0', 'libcudart.so.12.0'] files: {PosixPath('/usr/local/cuda/lib64/libcudart.so'), PosixPath('/usr/local/cuda/lib64/libcudart.so.11.0')}.. We'll flip a coin and try one of these, in order to fail forward.
Either way, this might cause trouble in the future:
If you get `CUDA error: invalid device function` errors, the above might be the cause and the solution is to make sure only one ['libcudart.so', 'libcudart.so.11.0', 'libcudart.so.12.0'] in the paths that we search based on your env.
  warn(msg)

**Comment by christopher-w-murphy** [comment]
Update: If I explictly set the batch size, instead of using `auto_find_batch_size`, it works as expected. As a practical matter, this resolves my issue. On the other hand, if someone needs to auto-find the batch size, they would still face this issue.

**Comment by christopher-w-murphy** [comment]
The above update was for AdamW8bit optimizer from bitsandbytes==0.37.1. 

When I instead use the Lion8bit optimizer from bitsandbytes==0.38.1 I get the dreaded `RuntimeError: CUDA out of memory` exception. The strange thing is training successfully runs to completion. The runtime error is thrown when I tried to push the model to Huggingface hub.

I then tried setting `os.environ["PYTORCH_CUDA_ALLOC_CONF"] = "max_split_size_mb:256, garbage_collection_threshold:0.95"` and I ran `torch.cuda.empty_cache()` after training but before pushing to the hub only to receive the same error (with slightly different numeric values).

app({"optim_name": args.optim_name, "model_size": args.model_size, "n_epochs": args.n_epochs, "limit_samples": args.limit_samples})
  File "/home/ec2-user/llm-lion-finetuning/src/application/app_fine_tune_flan_t5.py", line 119, in app
    trainer.model.push_to_hub(output_dir)
  File "/opt/conda/envs/pytorch/lib/python3.10/site-packages/transformers/utils/hub.py", line 781, in push_to_hub
    self.save_pretrained(work_dir, max_shard_size=max_shard_size)
  File "/opt/conda/envs/pytorch/lib/python3.10/site-packages/peft/peft_model.py", line 102, in save_pretrained
    output_state_dict = get_peft_model_state_dict(self, kwargs.get("state_dict", None))
  File "/opt/conda/envs/pytorch/lib/python3.10/site-packages/peft/utils/save_and_load.py", line 31, in get_peft_model_state_dict
    state_dict = model.state_dict()
  File "/opt/conda/envs/pytorch/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1818, in state_dict
    module.state_dict(destination=destination, prefix=prefix + name + '.', keep_vars=keep_vars)
  File "/opt/conda/envs/pytorch/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1818, in state_dict
    module.state_dict(destination=destination, prefix=prefix + name + '.', keep_vars=keep_vars)
  File "/opt/conda/envs/pytorch/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1818, in state_dict
    module.state_dict(destination=destination, prefix=prefix + name + '.', keep_vars=keep_vars)
  [Previous line repeated 6 more times]
  File "/opt/conda/envs/pytorch/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1815, in state_dict
    self._save_to_state_dict(destination, prefix, keep_vars)
  File "/opt/conda/envs/pytorch/lib/python3.10/site-packages/bitsandbytes/nn/modules.py", line 268, in _save_to_state_dict
    self.weight.data = undo_layout(self.state.CxB, self.state.tile_indices)
  File "/opt/conda/envs/pytorch/lib/python3.10/site-packages/bitsandbytes/autograd/_functions.py", line 96, in undo_layout
    outputs = torch.empty_like(tensor)  # note: not using .index_copy because it was slower on cuda
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 40.00 MiB (GPU 0; 22.19 GiB total capacity; 20.60 GiB already allocated; 14.50 MiB free; 21.11 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF

**Comment by christopher-w-murphy** [comment]
I believe this issue was ultimately the same as #324, which I just saw was fixed, so I'm closing this issue.
