### ISSUE TITLE
 python -m bitsandbytes

### ISSUE THREAD

**Issue by ghezalahmad** [TimDettmers/bitsandbytes#573]
python -m bitsandbytes

===================================BUG REPORT===================================
Welcome to bitsandbytes. For bug reports, please run

python -m bitsandbytes

 and submit this information together with your error trace to: https://github.com/TimDettmers/bitsandbytes/issues
================================================================================
bin /home/gzia/miniconda3/envs/falcon/lib/python3.11/site-packages/bitsandbytes/libbitsandbytes_cuda112.so
/home/gzia/miniconda3/envs/falcon/lib/python3.11/site-packages/bitsandbytes/cuda_setup/main.py:149: UserWarning: Found duplicate ['libcudart.so', 'libcudart.so.11.0', 'libcudart.so.12.0'] files: {PosixPath('/home/gzia/miniconda3/envs/falcon/lib/libcudart.so'), PosixPath('/home/gzia/miniconda3/envs/falcon/lib/libcudart.so.11.0')}.. We'll flip a coin and try one of these, in order to fail forward.
Either way, this might cause trouble in the future:
If you get `CUDA error: invalid device function` errors, the above might be the cause and the solution is to make sure only one ['libcudart.so', 'libcudart.so.11.0', 'libcudart.so.12.0'] in the paths that we search based on your env.
  warn(msg)
CUDA SETUP: CUDA runtime path found: /home/gzia/miniconda3/envs/falcon/lib/libcudart.so
CUDA SETUP: Highest compute capability among GPUs detected: 8.6
CUDA SETUP: Detected CUDA version 112
CUDA SETUP: Loading binary /home/gzia/miniconda3/envs/falcon/lib/python3.11/site-packages/bitsandbytes/libbitsandbytes_cuda112.so...
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
++++++++++++++++++ BUG REPORT INFORMATION ++++++++++++++++++
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

+++++++++++++++++++ ANACONDA CUDA PATHS ++++++++++++++++++++
/home/gzia/miniconda3/envs/falcon/lib/python3.11/site-packages/torch/lib/libtorch_cuda_linalg.so
/home/gzia/miniconda3/envs/falcon/lib/python3.11/site-packages/torch/lib/libc10_cuda.so
/home/gzia/miniconda3/envs/falcon/lib/python3.11/site-packages/torch/lib/libtorch_cuda.so
/home/gzia/miniconda3/envs/falcon/lib/python3.11/site-packages/bitsandbytes/libbitsandbytes_cuda110_nocublaslt.so
/home/gzia/miniconda3/envs/falcon/lib/python3.11/site-packages/bitsandbytes/libbitsandbytes_cuda118_nocublaslt.so
/home/gzia/miniconda3/envs/falcon/lib/python3.11/site-packages/bitsandbytes/libbitsandbytes_cuda113.so
/home/gzia/miniconda3/envs/falcon/lib/python3.11/site-packages/bitsandbytes/libbitsandbytes_cuda115_nocublaslt.so
/home/gzia/miniconda3/envs/falcon/lib/python3.11/site-packages/bitsandbytes/libbitsandbytes_cuda118.so
/home/gzia/miniconda3/envs/falcon/lib/python3.11/site-packages/bitsandbytes/libbitsandbytes_cuda113_nocublaslt.so
/home/gzia/miniconda3/envs/falcon/lib/python3.11/site-packages/bitsandbytes/libbitsandbytes_cuda117_nocublaslt.so
/home/gzia/miniconda3/envs/falcon/lib/python3.11/site-packages/bitsandbytes/libbitsandbytes_cuda110.so
/home/gzia/miniconda3/envs/falcon/lib/python3.11/site-packages/bitsandbytes/libbitsandbytes_cuda120_nocublaslt.so
/home/gzia/miniconda3/envs/falcon/lib/python3.11/site-packages/bitsandbytes/libbitsandbytes_cuda111_nocublaslt.so
/home/gzia/miniconda3/envs/falcon/lib/python3.11/site-packages/bitsandbytes/libbitsandbytes_cuda112.so
/home/gzia/miniconda3/envs/falcon/lib/python3.11/site-packages/bitsandbytes/libbitsandbytes_cuda115.so
/home/gzia/miniconda3/envs/falcon/lib/python3.11/site-packages/bitsandbytes/libbitsandbytes_cuda121_nocublaslt.so
/home/gzia/miniconda3/envs/falcon/lib/python3.11/site-packages/bitsandbytes/libbitsandbytes_cuda116.so
/home/gzia/miniconda3/envs/falcon/lib/python3.11/site-packages/bitsandbytes/libbitsandbytes_cuda121.so
/home/gzia/miniconda3/envs/falcon/lib/python3.11/site-packages/bitsandbytes/libbitsandbytes_cuda112_nocublaslt.so
/home/gzia/miniconda3/envs/falcon/lib/python3.11/site-packages/bitsandbytes/libbitsandbytes_cuda120.so
/home/gzia/miniconda3/envs/falcon/lib/python3.11/site-packages/bitsandbytes/libbitsandbytes_cuda116_nocublaslt.so
/home/gzia/miniconda3/envs/falcon/lib/python3.11/site-packages/bitsandbytes/libbitsandbytes_cuda114.so
/home/gzia/miniconda3/envs/falcon/lib/python3.11/site-packages/bitsandbytes/libbitsandbytes_cuda117.so
/home/gzia/miniconda3/envs/falcon/lib/python3.11/site-packages/bitsandbytes/libbitsandbytes_cuda114_nocublaslt.so
/home/gzia/miniconda3/envs/falcon/lib/python3.11/site-packages/bitsandbytes/libbitsandbytes_cuda111.so
/home/gzia/miniconda3/envs/falcon/lib/libcudart.so

++++++++++++++++++ /usr/local CUDA PATHS +++++++++++++++++++

Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/home/gzia/miniconda3/envs/falcon/lib/python3.11/site-packages/bitsandbytes/__main__.py", line 95, in <module>
    generate_bug_report_information()
  File "/home/gzia/miniconda3/envs/falcon/lib/python3.11/site-packages/bitsandbytes/__main__.py", line 60, in generate_bug_report_information
    paths = find_file_recursive(os.getcwd(), '*cuda*so')
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gzia/miniconda3/envs/falcon/lib/python3.11/site-packages/bitsandbytes/__main__.py", line 37, in find_file_recursive
    raise RuntimeError('Something when wrong when trying to find file. Maybe you do not have a linux system?')
RuntimeError: Something when wrong when trying to find file. Maybe you do not have a linux system?

**Comment by jb-01** [comment]
This worked for me: `pip install --upgrade bitsandbytes`

**Comment by TimDettmers** [comment]
It seems you have no CUDA installed. CUDA is a requirement for bitsandbytes. Is there some CUDA version installed somewhere on your system?

**Comment by TimDettmers** [comment]
Upgrading via `pip install -U bitsandbytes` should resolve this issue. I will close this issue. Please reopen if upgrading does not resolve the error.
