### ISSUE TITLE
遇到BUG，求大佬看看这么解决

### ISSUE THREAD

**Issue by hhuop1** [TimDettmers/bitsandbytes#574]
CUDA SETUP: Loading binary D:\ai Photo\lora Text\lora-scripts-gui\python\lib\site-packages\bitsandbytes\libbitsandbytes_cuda116.dll...
use 8-bit AdamW optimizer | {}
override steps. steps for 10 epochs is / 指定エポックまでのステップ数: 900
Traceback (most recent call last):
  File "D:\ai Photo\lora Text\lora-scripts-gui\sd-scripts\train_network.py", line 873, in <module>
    train(args)
  File "D:\ai Photo\lora Text\lora-scripts-gui\sd-scripts\train_network.py", line 301, in train
    unet, text_encoder, network, optimizer, train_dataloader, lr_scheduler = accelerator.prepare(
  File "D:\ai Photo\lora Text\lora-scripts-gui\python\lib\site-packages\accelerate\accelerator.py", line 876, in prepare
    result = tuple(
  File "D:\ai Photo\lora Text\lora-scripts-gui\python\lib\site-packages\accelerate\accelerator.py", line 877, in <genexpr>
    self._prepare_one(obj, first_pass=True, device_placement=d) for obj, d in zip(args, device_placement)
  File "D:\ai Photo\lora Text\lora-scripts-gui\python\lib\site-packages\accelerate\accelerator.py", line 741, in _prepare_one
    return self.prepare_model(obj, device_placement=device_placement)
  File "D:\ai Photo\lora Text\lora-scripts-gui\python\lib\site-packages\accelerate\accelerator.py", line 912, in prepare_model
    model = model.to(self.device)
  File "D:\ai Photo\lora Text\lora-scripts-gui\python\lib\site-packages\transformers\modeling_utils.py", line 1749, in to
    return super().to(*args, **kwargs)
  File "D:\ai Photo\lora Text\lora-scripts-gui\python\lib\site-packages\torch\nn\modules\module.py", line 1145, in to
    return self._apply(convert)
  File "D:\ai Photo\lora Text\lora-scripts-gui\python\lib\site-packages\torch\nn\modules\module.py", line 797, in _apply
    module._apply(fn)
  File "D:\ai Photo\lora Text\lora-scripts-gui\python\lib\site-packages\torch\nn\modules\module.py", line 797, in _apply
    module._apply(fn)
  File "D:\ai Photo\lora Text\lora-scripts-gui\python\lib\site-packages\torch\nn\modules\module.py", line 797, in _apply
    module._apply(fn)
  [Previous line repeated 3 more times]
  File "D:\ai Photo\lora Text\lora-scripts-gui\python\lib\site-packages\torch\nn\modules\module.py", line 820, in _apply
    param_applied = fn(param)
  File "D:\ai Photo\lora Text\lora-scripts-gui\python\lib\site-packages\torch\nn\modules\module.py", line 1143, in convert
    return t.to(device, dtype if t.is_floating_point() or t.is_complex() else None, non_blocking)
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 20.00 MiB (GPU 0; 4.00 GiB total capacity; 3.40 GiB already allocated; 0 bytes free; 3.46 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
Traceback (most recent call last):
  File "D:\ai Photo\lora Text\lora-scripts-gui\python\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "D:\ai Photo\lora Text\lora-scripts-gui\python\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "D:\ai Photo\lora Text\lora-scripts-gui\python\lib\site-packages\accelerate\commands\launch.py", line 1114, in <module>
    main()
  File "D:\ai Photo\lora Text\lora-scripts-gui\python\lib\site-packages\accelerate\commands\launch.py", line 1110, in main
    launch_command(args)
  File "D:\ai Photo\lora Text\lora-scripts-gui\python\lib\site-packages\accelerate\commands\launch.py", line 1104, in launch_command
    simple_launcher(args)
  File "D:\ai Photo\lora Text\lora-scripts-gui\python\lib\site-packages\accelerate\commands\launch.py", line 567, in simple_launcher
    raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)
subprocess.CalledProcessError: Command '['D:\\ai Photo\\lora Text\\lora-scripts-gui\\python\\python.exe', './sd-scripts/train_network.py', '--config_file', 'D:\\ai Photo\\lora Text\\lora-scripts-gui\\toml\\autosave\\20230710-233222.toml']' returned non-zero exit status 1.
Training failed / 训练失败

**Comment by TimDettmers** [comment]
Your network is too large to fit on your GPU (4GB). You need to use a smaller batch size or a smaller model.

**Comment by asdfsa1314** [comment]
I solved it, the general plan is as follows
because cuda is 12.1
so , torch install 
```
pip install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu118
```
Need to be guaranteed torch installed is success
use below shell checkout torch install:
```
import torch
torch.cuda.is_available()

#cat "True" is success 
```
about bitsandbytes
I use below shell
```
pip install https://github.com/jllllll/bitsandbytes-windows-webui/raw/main/bitsandbytes-0.39.0-py3-none-any.whl
```
However, there is a problem with this bag. Although he is a bag under Windows, there are some hard codes in the code
int the win platorm ,use below shell show us error
```
python -m bitsandbytes
```

so, the problem 
```
# site-packages\bitsandbytes\__main__.py 
# 90 line
def print_debug_info() -> None:
    print(
        "\nAbove we output some debug information. Please provide this info when "
        f"creating an issue via {PACKAGE_GITHUB_URL}/issues/new/choose ...\n"
    )


#generate_bug_report_information() 
# this method comments, he checks the environment, but uses the "find" (a program instruction below the unix environment) to retrieve the file, so it will report an error.


from . import COMPILED_WITH_CUDA, PACKAGE_GITHUB_URL
from .cuda_setup.env_vars import to_be_ignored
from .cuda_setup.main import get_compute_capabilities, get_cuda_lib_handle

# 102 line

```

I hope this can help with me a question
