### ISSUE TITLE
WARNING: No libcudart.so found!

### ISSUE THREAD

**Issue by dingpeng0201** [TimDettmers/bitsandbytes#577]
CUDA_SETUP: WARNING! libcudart.so not found in any environmental path. Searching /usr/local/cuda/lib64...
C:\Users\user\AppData\Local\Programs\Python\Python310\lib\site-packages\bitsandbytes\cuda_setup\paths.py:27: UserWarning: WARNING: The following directories listed in your path were found to be non-existent: {WindowsPath('/usr/local/cuda/lib64')}
  warn(
WARNING: No libcudart.so found! Install CUDA or the cudatoolkit package (anaconda)!
CUDA SETUP: Loading binary C:\Users\user\AppData\Local\Programs\Python\Python310\lib\site-packages\bitsandbytes\libbitsandbytes_cpu.so...
Traceback (most recent call last):
  File "C:\Users\user\Desktop\lora\sd-scripts\train_network.py", line 873, in <module>
    train(args)
  File "C:\Users\user\Desktop\lora\sd-scripts\train_network.py", line 262, in train
    optimizer_name, optimizer_args, optimizer = train_util.get_optimizer(args, trainable_params)
  File "C:\Users\user\Desktop\lora\sd-scripts\library\train_util.py", line 2699, in get_optimizer
    import bitsandbytes as bnb
  File "C:\Users\user\AppData\Local\Programs\Python\Python310\lib\site-packages\bitsandbytes\__init__.py", line 6, in <module>
    from .autograd._functions import (
  File "C:\Users\user\AppData\Local\Programs\Python\Python310\lib\site-packages\bitsandbytes\autograd\_functions.py", line 5, in <module>
    import bitsandbytes.functional as F
  File "C:\Users\user\AppData\Local\Programs\Python\Python310\lib\site-packages\bitsandbytes\functional.py", line 13, in <module>
    from .cextension import COMPILED_WITH_CUDA, lib
  File "C:\Users\user\AppData\Local\Programs\Python\Python310\lib\site-packages\bitsandbytes\cextension.py", line 41, in <module>
    lib = CUDALibrary_Singleton.get_instance().lib
  File "C:\Users\user\AppData\Local\Programs\Python\Python310\lib\site-packages\bitsandbytes\cextension.py", line 37, in get_instance
    cls._instance.initialize()
  File "C:\Users\user\AppData\Local\Programs\Python\Python310\lib\site-packages\bitsandbytes\cextension.py", line 31, in initialize
    self.lib = ct.cdll.LoadLibrary(binary_path)
  File "C:\Users\user\AppData\Local\Programs\Python\Python310\lib\ctypes\__init__.py", line 452, in LoadLibrary
    return self._dlltype(name)
  File "C:\Users\user\AppData\Local\Programs\Python\Python310\lib\ctypes\__init__.py", line 364, in __init__
    if '/' in name or '\\' in name:
TypeError: argument of type 'WindowsPath' is not iterable
Traceback (most recent call last):
  File "C:\Users\user\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\user\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\user\AppData\Local\Programs\Python\Python310\Scripts\accelerate.exe\__main__.py", line 7, in <module>
  File "C:\Users\user\AppData\Local\Programs\Python\Python310\lib\site-packages\accelerate\commands\accelerate_cli.py", line 45, in main
    args.func(args)
  File "C:\Users\user\AppData\Local\Programs\Python\Python310\lib\site-packages\accelerate\commands\launch.py", line 1104, in launch_command
    simple_launcher(args)
  File "C:\Users\user\AppData\Local\Programs\Python\Python310\lib\site-packages\accelerate\commands\launch.py", line 567, in simple_launcher
    raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)
subprocess.CalledProcessError: Command '['C:\\Users\\user\\AppData\\Local\\Programs\\Python\\Python310\\python.exe', 'train_network.py', '--pretrained_model_name_or_path=C:\\Users\\user\\Desktop\\webUI\\stable-diffusion-webui\\models\\Stable-diffusion\\MeinaPastelV2-baked_VAE-pruned.safetensors', '--output_dir=C:\\Users\\user\\Desktop\\lora\\notebooks\\TrainingData\\outputs', '--output_name=Shota_MPastel', '--dataset_config=C:\\Users\\user\\Desktop\\lora\\notebooks\\TrainingData\\datasetconfig.toml', '--train_batch_size=1', '--max_train_epochs=10', '--resolution=768,768', '--optimizer_type=AdamW8bit', '--learning_rate=1e-4', '--network_dim=128', '--network_alpha=64', '--enable_bucket', '--bucket_no_upscale', '--lr_scheduler=cosine_with_restarts', '--lr_scheduler_num_cycles=4', '--lr_warmup_steps=500', '--keep_tokens=1', '--shuffle_caption', '--caption_dropout_rate=0.05', '--save_model_as=safetensors', '--clip_skip=2', '--seed=42', '--color_aug', '--xformers', '--mixed_precision=fp16', '--network_module=networks.lora', '--persistent_data_loader_workers']' returned non-zero exit status 1.

I have installed CUDA 11.6 in windows environment and PATH is passed.
PS C:\Users\user\Desktop\lora\sd-scripts> nvcc --version
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2021 NVIDIA Corporation
Built on Fri_Dec_17_18:28:54_Pacific_Standard_Time_2021
Cuda compilation tools, release 11.6, V11.6.55
Build cuda_11.6.r11.6/compiler.30794723_0

**Comment by marco-ve** [comment]
Same. I really appreciate the work being done in this repo, but people have been having issues getting bitsandbytes to work with gpu when gpu is clearly available in the environment for almost a year now, and it seems like nobody cares?

Maybe fixing the way that bitsandbytes checks for cuda availability in an environment (e.g. docker) should be given some priority, so people can actually reliably deploy this library.

**Comment by asdfsa1314** [comment]
l think  that is dll path problem，check your path

**Comment by asdfsa1314** [comment]
the code check dll or so cant load below:
```python
import ctype as ct
ct.cdll.LoadLibrary('your dll')
```

**Comment by marco-ve** [comment]
So I'm using Docker on Ubuntu to run my environments. What I ended up having to do was run a conda environment inside the docker container in order for bitsandbytes to properly detect libcudart.so and run the CUDA setup without errors.

I've never had to do this with any other GPU dependent package, but at least it seems to work now.

**Comment by TimDettmers** [comment]
Conda automatically detected the CUDA libraries, but Windows CUDA installs are currently not supported. Read #30 for more information

**Comment by swumagic** [comment]
Bitsandbytes was not supported windows before, but my method can support windows.（yuhuang）
1  open folder J:\StableDiffusion\sdwebui，Click the address bar of the folder and enter CMD
or WIN+R, CMD  。enter，cd /d J:\StableDiffusion\sdwebui
2  J:\StableDiffusion\sdwebui\py310\python.exe -m pip uninstall bitsandbytes

3 J:\StableDiffusion\sdwebui\py310\python.exe -m pip uninstall bitsandbytes-windows

4 J:\StableDiffusion\sdwebui\py310\python.exe -m pip install https://github.com/jllllll/bitsandbytes-windows-webui/releases/download/wheels/bitsandbytes-0.41.1-py3-none-win_amd64.whl

Replace your SD venv directory file（python.exe Folder） here（J:\StableDiffusion\sdwebui\py310）
