### ISSUE TITLE
python -m bitsandbytes

### ISSUE THREAD

**Issue by ez2rok** [TimDettmers/bitsandbytes#586]
# My Error

I got an error when I ran `from llm.training import LLMTolkien` where `LLMTolkien` is a class that uses bitsandbytes. The error I got was:

CUDA SETUP: CUDA runtime path found: [/home/ethan/mambaforge/envs/llm_potter/lib/libcudart.so](https://vscode-remote+ssh-002dremote-002baeolus.vscode-resource.vscode-cdn.net/home/ethan/mambaforge/envs/llm_potter/lib/libcudart.so)
CUDA SETUP: Highest compute capability among GPUs detected: 8.6
CUDA SETUP: Detected CUDA version 118
CUDA SETUP: Required library version not found: libbitsandbytes_cuda118.so. Maybe you need to compile it from source?
CUDA SETUP: Defaulting to libbitsandbytes_cpu.so...

================================================ERROR=====================================
CUDA SETUP: CUDA detection failed! Possible reasons:
1. CUDA driver not installed
2. CUDA not installed
3. You have multiple conflicting CUDA libraries
4. Required library not pre-compiled for this bitsandbytes release!
CUDA SETUP: If you compiled from source, try again with `make CUDA_VERSION=DETECTED_CUDA_VERSION` for example, `make CUDA_VERSION=113`.
CUDA SETUP: The CUDA version for the compile might depend on your conda install. Inspect CUDA version via `conda list | grep cuda`.
================================================================================

CUDA SETUP: Something unexpected happened. Please compile from source:
git clone git@github.com:TimDettmers[/bitsandbytes.git](https://vscode-remote+ssh-002dremote-002baeolus.vscode-resource.vscode-cdn.net/bitsandbytes.git)
cd bitsandbytes
CUDA_VERSION=118 make cuda11x
python setup.py install
CUDA SETUP: Setup Failed!
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
Cell In[20], line 4
      2 from llm import config as config_llm
      3 from llm.prepare_dataset import prepare_dataset
----> 4 from llm.training import LLMTolkien

File [~/llm-potter/llm/training.py:8](https://vscode-remote+ssh-002dremote-002baeolus.vscode-resource.vscode-cdn.net/home/ethan/llm-potter/~/llm-potter/llm/training.py:8)
      6 from torch import cuda
      7 from datasets import load_dataset
----> 8 from peft import LoraConfig, PeftModel, PeftConfig, get_peft_model
      9 from transformers import AutoModelForCausalLM, AutoTokenizer, Trainer, TrainingArguments, DataCollatorForLanguageModeling
     11 # import llm.config as config

File [~/mambaforge/envs/llm_potter/lib/python3.11/site-packages/peft/__init__.py:22](https://vscode-remote+ssh-002dremote-002baeolus.vscode-resource.vscode-cdn.net/home/ethan/llm-potter/~/mambaforge/envs/llm_potter/lib/python3.11/site-packages/peft/__init__.py:22)
      1 # flake8: noqa
      2 # There's no way to ignore "F401 '...' imported but unused" warnings in this
      3 # module, but to preserve other warnings. So, don't check this module at all.
   (...)
     17 # See the License for the specific language governing permissions and
     18 # limitations under the License.
     20 __version__ = "0.3.0"
---> 22 from .mapping import MODEL_TYPE_TO_PEFT_MODEL_MAPPING, PEFT_TYPE_TO_CONFIG_MAPPING, get_peft_config, get_peft_model
     23 from .peft_model import (
     24     PeftModel,
     25     PeftModelForCausalLM,
   (...)
     28     PeftModelForTokenClassification,
     29 )
     30 from .tuners import (
     31     AdaptionPromptConfig,
     32     AdaptionPromptModel,
   (...)
     44     PromptTuningInit,
     45 )

File [~/mambaforge/envs/llm_potter/lib/python3.11/site-packages/peft/mapping.py:16](https://vscode-remote+ssh-002dremote-002baeolus.vscode-resource.vscode-cdn.net/home/ethan/llm-potter/~/mambaforge/envs/llm_potter/lib/python3.11/site-packages/peft/mapping.py:16)
      1 # coding=utf-8
      2 # Copyright 2023-present the HuggingFace Inc. team.
      3 #
   (...)
     13 # See the License for the specific language governing permissions and
     14 # limitations under the License.
---> 16 from .peft_model import (
     17     PeftModel,
     18     PeftModelForCausalLM,
     19     PeftModelForSeq2SeqLM,
     20     PeftModelForSequenceClassification,
     21     PeftModelForTokenClassification,
     22 )
     23 from .tuners import (
     24     AdaLoraConfig,
     25     AdaptionPromptConfig,
   (...)
     29     PromptTuningConfig,
     30 )
     31 from .utils import PromptLearningConfig

File [~/mambaforge/envs/llm_potter/lib/python3.11/site-packages/peft/peft_model.py:31](https://vscode-remote+ssh-002dremote-002baeolus.vscode-resource.vscode-cdn.net/home/ethan/llm-potter/~/mambaforge/envs/llm_potter/lib/python3.11/site-packages/peft/peft_model.py:31)
     28 from transformers.modeling_outputs import SequenceClassifierOutput, TokenClassifierOutput
     29 from transformers.utils import PushToHubMixin
---> 31 from .tuners import (
     32     AdaLoraModel,
     33     AdaptionPromptModel,
     34     LoraModel,
     35     PrefixEncoder,
     36     PromptEmbedding,
     37     PromptEncoder,
     38 )
     39 from .utils import (
     40     TRANSFORMERS_MODELS_TO_PREFIX_TUNING_POSTPROCESS_MAPPING,
     41     WEIGHTS_NAME,
   (...)
     50     shift_tokens_right,
     51 )
     54 PEFT_TYPE_TO_MODEL_MAPPING = {
     55     PeftType.LORA: LoraModel,
     56     PeftType.PROMPT_TUNING: PromptEmbedding,
   (...)
     60     PeftType.ADAPTION_PROMPT: AdaptionPromptModel,
     61 }

File [~/mambaforge/envs/llm_potter/lib/python3.11/site-packages/peft/tuners/__init__.py:21](https://vscode-remote+ssh-002dremote-002baeolus.vscode-resource.vscode-cdn.net/home/ethan/llm-potter/~/mambaforge/envs/llm_potter/lib/python3.11/site-packages/peft/tuners/__init__.py:21)
      1 # flake8: noqa
      2 # There's no way to ignore "F401 '...' imported but unused" warnings in this
      3 # module, but to preserve other warnings. So, don't check this module at all
   (...)
     17 # See the License for the specific language governing permissions and
     18 # limitations under the License.
     20 from .adaption_prompt import AdaptionPromptConfig, AdaptionPromptModel
---> 21 from .lora import LoraConfig, LoraModel
     22 from .adalora import AdaLoraConfig, AdaLoraModel
     23 from .p_tuning import PromptEncoder, PromptEncoderConfig, PromptEncoderReparameterizationType

File [~/mambaforge/envs/llm_potter/lib/python3.11/site-packages/peft/tuners/lora.py:40](https://vscode-remote+ssh-002dremote-002baeolus.vscode-resource.vscode-cdn.net/home/ethan/llm-potter/~/mambaforge/envs/llm_potter/lib/python3.11/site-packages/peft/tuners/lora.py:40)
     28 from ..utils import (
     29     TRANSFORMERS_MODELS_TO_LORA_TARGET_MODULES_MAPPING,
     30     ModulesToSaveWrapper,
   (...)
     35     transpose,
     36 )
     39 if is_bnb_available():
---> 40     import bitsandbytes as bnb
     43 @dataclass
     44 class LoraConfig(PeftConfig):
     45     """
     46     This is the configuration class to store the configuration of a [`LoraModel`].
     47 
   (...)
     57             and saved in the final checkpoint.
     58     """

File [~/mambaforge/envs/llm_potter/lib/python3.11/site-packages/bitsandbytes/__init__.py:6](https://vscode-remote+ssh-002dremote-002baeolus.vscode-resource.vscode-cdn.net/home/ethan/llm-potter/~/mambaforge/envs/llm_potter/lib/python3.11/site-packages/bitsandbytes/__init__.py:6)
      1 # Copyright (c) Facebook, Inc. and its affiliates.
      2 #
      3 # This source code is licensed under the MIT license found in the
      4 # LICENSE file in the root directory of this source tree.
----> 6 from . import cuda_setup, utils, research
      7 from .autograd._functions import (
      8     MatmulLtState,
      9     bmm_cublas,
   (...)
     13     matmul_4bit
     14 )
     15 from .cextension import COMPILED_WITH_CUDA

File [~/mambaforge/envs/llm_potter/lib/python3.11/site-packages/bitsandbytes/research/__init__.py:1](https://vscode-remote+ssh-002dremote-002baeolus.vscode-resource.vscode-cdn.net/home/ethan/llm-potter/~/mambaforge/envs/llm_potter/lib/python3.11/site-packages/bitsandbytes/research/__init__.py:1)
----> 1 from . import nn
      2 from .autograd._functions import (
      3     switchback_bnb,
      4     matmul_fp8_global,
      5     matmul_fp8_mixed,
      6 )

File [~/mambaforge/envs/llm_potter/lib/python3.11/site-packages/bitsandbytes/research/nn/__init__.py:1](https://vscode-remote+ssh-002dremote-002baeolus.vscode-resource.vscode-cdn.net/home/ethan/llm-potter/~/mambaforge/envs/llm_potter/lib/python3.11/site-packages/bitsandbytes/research/nn/__init__.py:1)
----> 1 from .modules import LinearFP8Mixed, LinearFP8Global

File [~/mambaforge/envs/llm_potter/lib/python3.11/site-packages/bitsandbytes/research/nn/modules.py:8](https://vscode-remote+ssh-002dremote-002baeolus.vscode-resource.vscode-cdn.net/home/ethan/llm-potter/~/mambaforge/envs/llm_potter/lib/python3.11/site-packages/bitsandbytes/research/nn/modules.py:8)
      5 from torch import Tensor, device, dtype, nn
      7 import bitsandbytes as bnb
----> 8 from bitsandbytes.optim import GlobalOptimManager
      9 from bitsandbytes.utils import OutlierTracer, find_outlier_dims
     11 T = TypeVar("T", bound="torch.nn.Module")

File [~/mambaforge/envs/llm_potter/lib/python3.11/site-packages/bitsandbytes/optim/__init__.py:6](https://vscode-remote+ssh-002dremote-002baeolus.vscode-resource.vscode-cdn.net/home/ethan/llm-potter/~/mambaforge/envs/llm_potter/lib/python3.11/site-packages/bitsandbytes/optim/__init__.py:6)
      1 # Copyright (c) Facebook, Inc. and its affiliates.
      2 #
      3 # This source code is licensed under the MIT license found in the
      4 # LICENSE file in the root directory of this source tree.
----> 6 from bitsandbytes.cextension import COMPILED_WITH_CUDA
      8 from .adagrad import Adagrad, Adagrad8bit, Adagrad32bit
      9 from .adam import Adam, Adam8bit, Adam32bit, PagedAdam, PagedAdam8bit, PagedAdam32bit

File [~/mambaforge/envs/llm_potter/lib/python3.11/site-packages/bitsandbytes/cextension.py:20](https://vscode-remote+ssh-002dremote-002baeolus.vscode-resource.vscode-cdn.net/home/ethan/llm-potter/~/mambaforge/envs/llm_potter/lib/python3.11/site-packages/bitsandbytes/cextension.py:20)
     18     CUDASetup.get_instance().generate_instructions()
     19     CUDASetup.get_instance().print_log_stack()
---> 20     raise RuntimeError('''
     21     CUDA Setup failed despite GPU being available. Please run the following command to get more information:
     22 
     23     python -m bitsandbytes
     24 
     25     Inspect the output of the command and see if you can locate CUDA libraries. You might need to add them
     26     to your LD_LIBRARY_PATH. If you suspect a bug, please take the information from python -m bitsandbytes
     27     and open an issue at: https://github.com/TimDettmers/bitsandbytes/issues''')
     28 lib.cadam32bit_grad_fp32 # runs on an error if the library could not be found -> COMPILED_WITH_CUDA=False
     29 lib.get_context.restype = ct.c_void_p

RuntimeError: 
        CUDA Setup failed despite GPU being available. Please run the following command to get more information:

        python -m bitsandbytes

        Inspect the output of the command and see if you can locate CUDA libraries. You might need to add them
        to your LD_LIBRARY_PATH. If you suspect a bug, please take the information from python -m bitsandbytes
        and open an issue at: https://github.com/TimDettmers/bitsandbytes/issues

# `python -m bitsandbytes`

So I ran `python -m bitsandbytes` and received the following output:

===================================BUG REPORT===================================
Welcome to bitsandbytes. For bug reports, please run

python -m bitsandbytes

 and submit this information together with your error trace to: https://github.com/TimDettmers/bitsandbytes/issues
================================================================================
bin /home/ethan/mambaforge/envs/llm_potter/lib/python3.11/site-packages/bitsandbytes/libbitsandbytes_cuda118.so
False
/home/ethan/mambaforge/envs/llm_potter/lib/python3.11/site-packages/bitsandbytes/cuda_setup/main.py:149: UserWarning: Found duplicate ['libcudart.so', 'libcudart.so.11.0', 'libcudart.so.12.0'] files: {PosixPath('/home/ethan/mambaforge/envs/llm_potter/lib/libcudart.so.11.0'), PosixPath('/home/ethan/mambaforge/envs/llm_potter/lib/libcudart.so')}.. We'll flip a coin and try one of these, in order to fail forward.
Either way, this might cause trouble in the future:
If you get `CUDA error: invalid device function` errors, the above might be the cause and the solution is to make sure only one ['libcudart.so', 'libcudart.so.11.0', 'libcudart.so.12.0'] in the paths that we search based on your env.
  warn(msg)
CUDA SETUP: CUDA runtime path found: /home/ethan/mambaforge/envs/llm_potter/lib/libcudart.so.11.0
CUDA SETUP: Highest compute capability among GPUs detected: 8.6
CUDA SETUP: Detected CUDA version 118
CUDA SETUP: Required library version not found: libbitsandbytes_cuda118.so. Maybe you need to compile it from source?
CUDA SETUP: Defaulting to libbitsandbytes_cpu.so...

================================================ERROR=====================================
CUDA SETUP: CUDA detection failed! Possible reasons:
1. CUDA driver not installed
2. CUDA not installed
3. You have multiple conflicting CUDA libraries
4. Required library not pre-compiled for this bitsandbytes release!
CUDA SETUP: If you compiled from source, try again with `make CUDA_VERSION=DETECTED_CUDA_VERSION` for example, `make CUDA_VERSION=113`.
CUDA SETUP: The CUDA version for the compile might depend on your conda install. Inspect CUDA version via `conda list | grep cuda`.
================================================================================

CUDA SETUP: Something unexpected happened. Please compile from source:
git clone git@github.com:TimDettmers/bitsandbytes.git
cd bitsandbytes
CUDA_VERSION=118 make cuda11x
python setup.py install
CUDA SETUP: Setup Failed!
Traceback (most recent call last):
  File "<frozen runpy>", line 189, in _run_module_as_main
  File "<frozen runpy>", line 148, in _get_module_details
  File "<frozen runpy>", line 112, in _get_module_details
  File "/home/ethan/mambaforge/envs/llm_potter/lib/python3.11/site-packages/bitsandbytes/__init__.py", line 6, in <module>
    from . import cuda_setup, utils, research
  File "/home/ethan/mambaforge/envs/llm_potter/lib/python3.11/site-packages/bitsandbytes/research/__init__.py", line 1, in <module>
    from . import nn
  File "/home/ethan/mambaforge/envs/llm_potter/lib/python3.11/site-packages/bitsandbytes/research/nn/__init__.py", line 1, in <module>
    from .modules import LinearFP8Mixed, LinearFP8Global
  File "/home/ethan/mambaforge/envs/llm_potter/lib/python3.11/site-packages/bitsandbytes/research/nn/modules.py", line 8, in <module>
    from bitsandbytes.optim import GlobalOptimManager
  File "/home/ethan/mambaforge/envs/llm_potter/lib/python3.11/site-packages/bitsandbytes/optim/__init__.py", line 6, in <module>
    from bitsandbytes.cextension import COMPILED_WITH_CUDA
  File "/home/ethan/mambaforge/envs/llm_potter/lib/python3.11/site-packages/bitsandbytes/cextension.py", line 20, in <module>
    raise RuntimeError('''
RuntimeError: 
        CUDA Setup failed despite GPU being available. Please run the following command to get more information:

        python -m bitsandbytes

        Inspect the output of the command and see if you can locate CUDA libraries. You might need to add them
        to your LD_LIBRARY_PATH. If you suspect a bug, please take the information from python -m bitsandbytes
        and open an issue at: https://github.com/TimDettmers/bitsandbytes/issues

**Comment by ez2rok** [comment]
If relevant, here is my output from `nvidia-smi`:
```
Thu Jul 13 17:17:30 2023       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 470.199.02   Driver Version: 470.199.02   CUDA Version: 11.4     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  NVIDIA GeForce ...  Off  | 00000000:01:00.0 Off |                  N/A |
| 30%   57C    P2   126W / 350W |  22712MiB / 24265MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
|   1  NVIDIA GeForce ...  Off  | 00000000:21:00.0 Off |                  N/A |
|  0%   41C    P8    34W / 350W |      8MiB / 24268MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|    0   N/A  N/A      1646      G   /usr/lib/xorg/Xorg                  9MiB |
|    0   N/A  N/A      1837      G   /usr/bin/gnome-shell                6MiB |
|    0   N/A  N/A    167736      C   python                           2395MiB |
|    0   N/A  N/A    184629      C   ...onda3/envs/dna/bin/python    20297MiB |
|    1   N/A  N/A      1646      G   /usr/lib/xorg/Xorg                  4MiB |
+-----------------------------------------------------------------------------+
```

**Comment by ez2rok** [comment]
And the output of `conda list | grep cuda` is
```
cuda-version              11.8                 h70ddcb2_2    conda-forge
cudatoolkit               11.8.0              h37601d7_11    conda-forge
libhwloc                  2.9.1           nocuda_h7313eea_6    conda-forge
pytorch                   2.0.0           cuda112py311h13fee9e_200    conda-forge
```

**Comment by TimDettmers** [comment]
Please try upgrading to the lastest bitsandbytes version and try again. Please update me here.

**Comment by xiangchi-yuan** [comment]
upgrading to the lastest bitsandbytes version works for me
