### ISSUE TITLE
NameError: name 'str2optimizer8bit_blockwise' is not defined

### ISSUE THREAD

**Issue by utopictown** [TimDettmers/bitsandbytes#62]
i got this error when running dreambooth training from [here](https://github.com/huggingface/diffusers/tree/main/examples/dreambooth)

```
chiron    | /usr/local/lib/python3.9/site-packages/bitsandbytes/cuda_setup/paths.py:27: UserWarning: WARNING: The following directories listed in your path were found to be non-existent: {PosixPath('https'), PosixPath('//github.com/pypa/get-pip/raw/5eaac1050023df1f5c98b173b248c260023f2278/public/get-pip.py')}
chiron    |   warn(
chiron    | CUDA_SETUP: WARNING! libcudart.so not found in any environmental path. Searching /usr/local/cuda/lib64...
chiron    | /usr/local/lib/python3.9/site-packages/bitsandbytes/cuda_setup/paths.py:27: UserWarning: WARNING: The following directories listed in your path were found to be non-existent: {PosixPath('/usr/local/cuda/lib64')}
chiron    |   warn(
chiron    | WARNING: No libcudart.so found! Install CUDA or the cudatoolkit package (anaconda)!
chiron    | CUDA SETUP: Loading binary /usr/local/lib/python3.9/site-packages/bitsandbytes/libbitsandbytes_cpu.so...
chiron    | /usr/local/lib/python3.9/site-packages/bitsandbytes/cextension.py:48: UserWarning: The installed version of bitsandbytes was compiled without GPU support. 8-bit optimizers and GPU quantization are unavailable.
chiron    |   warn(
Steps:   0%|          | 0/800 [00:01<?, ?it/s, loss=0.183, lr=5e-6]Traceback (most recent call last):
chiron    |   File "/app/train_dreambooth.py", line 592, in <module>
chiron    |     main()
chiron    |   File "/app/train_dreambooth.py", line 560, in main
chiron    |     optimizer.step()
chiron    |   File "/usr/local/lib/python3.9/site-packages/accelerate/optimizer.py", line 140, in step
chiron    |     self.optimizer.step(closure)
chiron    |   File "/usr/local/lib/python3.9/site-packages/torch/optim/lr_scheduler.py", line 65, in wrapper
chiron    |     return wrapped(*args, **kwargs)
chiron    |   File "/usr/local/lib/python3.9/site-packages/torch/optim/optimizer.py", line 113, in wrapper
chiron    |     return func(*args, **kwargs)
chiron    |   File "/usr/local/lib/python3.9/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
chiron    |     return func(*args, **kwargs)
chiron    |   File "/usr/local/lib/python3.9/site-packages/bitsandbytes/optim/optimizer.py", line 265, in step
chiron    |     self.update_step(group, p, gindex, pindex)
chiron    |   File "/usr/local/lib/python3.9/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
chiron    |     return func(*args, **kwargs)
chiron    |   File "/usr/local/lib/python3.9/site-packages/bitsandbytes/optim/optimizer.py", line 506, in update_step
chiron    |     F.optimizer_update_8bit_blockwise(
chiron    |   File "/usr/local/lib/python3.9/site-packages/bitsandbytes/functional.py", line 858, in optimizer_update_8bit_blockwise
chiron    |     str2optimizer8bit_blockwise[optimizer_name][0](
chiron    | NameError: name 'str2optimizer8bit_blockwise' is not defined
Steps:   0%|          | 0/800 [00:01<?, ?it/s, loss=0.183, lr=5e-6]
chiron    | Traceback (most recent call last):
chiron    |   File "/usr/local/bin/accelerate", line 8, in <module>
chiron    |     sys.exit(main())
chiron    |   File "/usr/local/lib/python3.9/site-packages/accelerate/commands/accelerate_cli.py", line 43, in main
chiron    |     args.func(args)
chiron    |   File "/usr/local/lib/python3.9/site-packages/accelerate/commands/launch.py", line 837, in launch_command
chiron    |     simple_launcher(args)
chiron    |   File "/usr/local/lib/python3.9/site-packages/accelerate/commands/launch.py", line 354, in simple_launcher
chiron    |     raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)
```

result from python -m bitsandbytes

```
++++++++++++++++++++++++++ OTHER +++++++++++++++++++++++++++
COMPILED_WITH_CUDA = False
COMPUTE_CAPABILITIES_PER_GPU = ['7.0']
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
++++++++++++++++++++++ DEBUG INFO END ++++++++++++++++++++++
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

Running a quick check that:
    + library is importable
    + CUDA function is callable

name 'str2optimizer32bit' is not defined
```

run inside docker on VM linux ubuntu 20, 64GB, Intel(R) Xeon(R) CPU @ 2.20GHz, Nvidia GV100GL [Tesla V100 SXM2 16GB]

**Comment by wangrui6** [comment]
any updates?

**Comment by antkve** [comment]
Had this same problem, it's because it's not finding your CUDA version. Renaming libcudart.so.11.0 to libcudart.so in the dockerfile solved it for me.

**Comment by CharlesFauman** [comment]
my build is failing here too, with this error. - WSL2, cuda version V10.1.243

tracing the error, it's failing on the `lib.cadam32bit_g32` line of cextension.py (Attribute error) - lib is not None and torch.cuda.is_available, so it doesn't reach the generate_instructions call, but my COMPILED_WITH_CUDA gets set to False

the problem is that the evaluate_cuda_setup isn't working correctly, and my binary gets set to `libbitsandbytes_cpu.so`, even though I have cuda (including libcudart.do).

Looks like this is because i have cuda at `usr/lib/wsl/lib`, but my cudart_path gets set to `/usr/local/cuda/lib64`

setting LD_LIBRARY_PATH="/usr/lib/wsl/lib/" fixed this for me
https://github.com/rapidsai/cudf/issues/10308#issuecomment-1042388289

**Comment by ekeric13** [comment]
@TimDettmers Does the library need to be named literally "cudart.so"? Can it be named "libcudart.so.11.0"?

I am getting
```
CUDA_SETUP: WARNING! libcudart.so not found in any environmental path. Searching /usr/local/cuda/lib64...
WARNING: No libcudart.so found! Install CUDA or the cudatoolkit package (anaconda)!
```

I have the library installed in `/usr/lib/x86_64-linux-gnu/libcudart.so.11.0`.
I tried setting `export LD_LIBRARY_PATH=/usr/lib/x86_64-linux-gnu/libcudart.so.11.0` but that didn't work

**Comment by brucethemoose** [comment]
I am still getting this error, trying to figure out if it a CUDA dependency issue or not:

```
Traceback (most recent call last):
  File "/home/alpha/clone/sd-scripts/train_db.py", line 332, in <module>
    train(args)
  File "/home/alpha/clone/sd-scripts/train_db.py", line 266, in train
    optimizer.step()
  File "/home/alpha/.local/lib/python3.10/site-packages/accelerate/optimizer.py", line 134, in step
    self.scaler.step(self.optimizer, closure)
  File "/home/alpha/.local/lib/python3.10/site-packages/torch/cuda/amp/grad_scaler.py", line 341, in step
    retval = self._maybe_opt_step(optimizer, optimizer_state, *args, **kwargs)
  File "/home/alpha/.local/lib/python3.10/site-packages/torch/cuda/amp/grad_scaler.py", line 288, in _maybe_opt_step
    retval = optimizer.step(*args, **kwargs)
  File "/home/alpha/.local/lib/python3.10/site-packages/torch/optim/lr_scheduler.py", line 69, in wrapper
    return wrapped(*args, **kwargs)
  File "/home/alpha/.local/lib/python3.10/site-packages/torch/optim/optimizer.py", line 219, in wrapper
    out = func(*args, **kwargs)
  File "/home/alpha/.local/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/home/alpha/.local/lib/python3.10/site-packages/bitsandbytes/optim/optimizer.py", line 263, in step
    self.update_step(group, p, gindex, pindex)
  File "/home/alpha/.local/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/home/alpha/.local/lib/python3.10/site-packages/bitsandbytes/optim/optimizer.py", line 504, in update_step
    F.optimizer_update_8bit_blockwise(
  File "/home/alpha/.local/lib/python3.10/site-packages/bitsandbytes/functional.py", line 972, in optimizer_update_8bit_blockwise
    str2optimizer8bit_blockwise[optimizer_name][1](
NameError: name 'str2optimizer8bit_blockwise' is not defined
steps:   0%|                                                                    | 0/1600 [00:01<?, ?it/s]
Traceback (most recent call last):
```

**Comment by brucethemoose** [comment]
Yep, some CUDA thing is busted, no surprise :/ 

```
❯ python -m bitsandbytes

===================================BUG REPORT===================================
Welcome to bitsandbytes. For bug reports, please submit your error trace to: https://github.com/TimDettmers/bitsandbytes/issues
For effortless bug reporting copy-paste your error into this form: https://docs.google.com/forms/d/e/1FAIpQLScPB8emS3Thkp66nvqwmjTEgxp8Y9ufuWTzFyr9kJ5AoI47dQ/viewform?usp=sf_link
================================================================================
/home/alpha/.local/lib/python3.10/site-packages/bitsandbytes/cuda_setup/main.py:134: UserWarning: WARNING: The following directories listed in your path were found to be non-existent: {PosixPath('/home/alpha/.gtkrc'), PosixPath('/etc/gtk/gtkrc')}
  warn(msg)
/home/alpha/.local/lib/python3.10/site-packages/bitsandbytes/cuda_setup/main.py:134: UserWarning: WARNING: The following directories listed in your path were found to be non-existent: {PosixPath('/tmp/Alacritty-16327.log')}
  warn(msg)
/home/alpha/.local/lib/python3.10/site-packages/bitsandbytes/cuda_setup/main.py:134: UserWarning: WARNING: The following directories listed in your path were found to be non-existent: {PosixPath('https'), PosixPath('//debuginfod.archlinux.org')}
  warn(msg)
/home/alpha/.local/lib/python3.10/site-packages/bitsandbytes/cuda_setup/main.py:134: UserWarning: WARNING: The following directories listed in your path were found to be non-existent: {PosixPath('/home/alpha/.cache/dotnet_bundle_extract')}
  warn(msg)
/home/alpha/.local/lib/python3.10/site-packages/bitsandbytes/cuda_setup/main.py:134: UserWarning: WARNING: The following directories listed in your path were found to be non-existent: {PosixPath('/org/freedesktop/DisplayManager/Session0')}
  warn(msg)
/home/alpha/.local/lib/python3.10/site-packages/bitsandbytes/cuda_setup/main.py:134: UserWarning: WARNING: The following directories listed in your path were found to be non-existent: {PosixPath('/org/freedesktop/DisplayManager/Seat0')}
  warn(msg)
/home/alpha/.local/lib/python3.10/site-packages/bitsandbytes/cuda_setup/main.py:134: UserWarning: WARNING: The following directories listed in your path were found to be non-existent: {PosixPath('@/tmp/.ICE-unix/886,unix/Asus-GA401IV'), PosixPath('local/Asus-GA401IV')}
  warn(msg)
CUDA_SETUP: WARNING! libcudart.so not found in any environmental path. Searching /usr/local/cuda/lib64...
/home/alpha/.local/lib/python3.10/site-packages/bitsandbytes/cuda_setup/main.py:134: UserWarning: WARNING: The following directories listed in your path were found to be non-existent: {PosixPath('/usr/local/cuda/lib64')}
  warn(msg)
ERROR: python: undefined symbol: cudaRuntimeGetVersion
CUDA SETUP: libcudart.so path is None
CUDA SETUP: Is seems that your cuda installation is not in your path. See https://github.com/TimDettmers/bitsandbytes/issues/85 for more information.
CUDA SETUP: CUDA version lower than 11 are currently not supported for LLM.int8(). You will be only to use 8-bit optimizers and quantization routines!!
/home/alpha/.local/lib/python3.10/site-packages/bitsandbytes/cuda_setup/main.py:134: UserWarning: WARNING: No libcudart.so found! Install CUDA or the cudatoolkit package (anaconda)!
  warn(msg)
CUDA SETUP: Highest compute capability among GPUs detected: 7.5
CUDA SETUP: Detected CUDA version 00
CUDA SETUP: Loading binary /home/alpha/.local/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cpu.so...
/home/alpha/.local/lib/python3.10/site-packages/bitsandbytes/cextension.py:31: UserWarning: The installed version of bitsandbytes was compiled without GPU support. 8-bit optimizers and GPU quantization are unavailable.
  warn("The installed version of bitsandbytes was compiled without GPU support. "
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
++++++++++++++++++++ DEBUG INFORMATION +++++++++++++++++++++
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

++++++++++ POTENTIALLY LIBRARY-PATH-LIKE ENV VARS ++++++++++
'GTK_RC_FILES': '/etc/gtk/gtkrc:/home/alpha/.gtkrc:/home/alpha/.config/gtkrc'
'ALACRITTY_LOG': '/tmp/Alacritty-16327.log'
'ALACRITTY_SOCKET': '/run/user/1000/Alacritty-wayland-0-16327.sock'
'CUDA_PATH': '/opt/cuda'
'XAUTHORITY': '/run/user/1000/xauth_psWWsO'
'DEBUGINFOD_URLS': 'https://debuginfod.archlinux.org'
'DOTNET_BUNDLE_EXTRACT_BASE_DIR': '/home/alpha/.cache/dotnet_bundle_extract'
'XDG_SESSION_PATH': '/org/freedesktop/DisplayManager/Session0'
'GTK2_RC_FILES': '/home/alpha/.gtkrc-2.0'
'MKLROOT': '/opt/intel/oneapi/mkl/latest'
'XDG_SEAT_PATH': '/org/freedesktop/DisplayManager/Seat0'
'DOTNET_ROOT': '/usr/share/dotnet'
'PAM_KWALLET5_LOGIN': '/run/user/1000/kwallet5.socket'
'SESSION_MANAGER': 'local/Asus-GA401IV:@/tmp/.ICE-unix/886,unix/Asus-GA401IV:/tmp/.ICE-unix/886'
'XDG_CONFIG_DIRS': '/home/alpha/.config/kdedefaults:/etc/xdg'
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

WARNING: Please be sure to sanitize sensible info from any such env vars!

++++++++++++++++++++++++++ OTHER +++++++++++++++++++++++++++
COMPILED_WITH_CUDA = False
COMPUTE_CAPABILITIES_PER_GPU = ['7.5']
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
++++++++++++++++++++++ DEBUG INFO END ++++++++++++++++++++++
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
```

**Comment by brucethemoose** [comment]
The fix above solved the issue for me:

`LD_LIBRARY_PATH="/opt/cuda/targets/x86_64-linux/lib:$LD_LIBRARY_PATH"`

**Comment by jeremy-linchao** [comment]
I 

> @TimDettmers Does the library need to be named literally "cudart.so"? Can it be named "libcudart.so.11.0"?
> 
> I am getting
> 
> ```
> CUDA_SETUP: WARNING! libcudart.so not found in any environmental path. Searching /usr/local/cuda/lib64...
> WARNING: No libcudart.so found! Install CUDA or the cudatoolkit package (anaconda)!
> ```
> 
> I have the library installed in `/usr/lib/x86_64-linux-gnu/libcudart.so.11.0`. I tried setting `export LD_LIBRARY_PATH=/usr/lib/x86_64-linux-gnu/libcudart.so.11.0` but that didn't work
> 
> edit:
> 
> okay I think I got it working if I do `export LD_LIBRARY_PATH=/usr/lib/x86_64-linux-gnu/`

I set the LD_LIBRARY_PATH=/usr/lib/x86_64-linux-gnu/ and it still not works, is your app run on docker?

**Comment by Sanster** [comment]
bitsandbytes try to find `libcudart.so` in `LD_LIBRARY_PATH`, but the filename in my environment is `libcudart.so.11.0`, create a softlink works for me

**Comment by eschmidbauer** [comment]
i was able to solve this by using conda to install the required dependencies:
```
conda install -c "nvidia/label/cuda-11.7.1" \
	cuda-libraries=11.7.1 \
	cuda-libraries-dev=11.7.1 \
	cudnn
```

**Comment by bolner** [comment]
> i was able to solve this by using conda to install the required dependencies:
> 
> ```
> conda install -c "nvidia/label/cuda-11.7.1" \
> 	cuda-libraries=11.7.1 \
> 	cuda-libraries-dev=11.7.1 \
> 	cudnn
> ```

For me this broke the Torch library :) Luckily it happened in a docker container.

**Comment by han-code-4-fun** [comment]
Appreciated all your answers!

**Comment by xpluscal** [comment]
> LD_LIBRARY_PATH="/opt/cu

Could you explain that?
My path is set like this: 
`export LD_LIBRARY_PATH=/usr/local/cuda-12.0/lib64${LD_LIBRARY_PATH:+:${LD_LIBRARY_PATH}}`

Which results in the LD_LIBRARY_PATH being this:
/usr/local/cuda-12.0/lib64

**Comment by swumagic** [comment]
Bitsandbytes was not supported windows before, but my method can support windows.（yuhuang）
1  open folder J:\StableDiffusion\sdwebui，Click the address bar of the folder and enter CMD
or WIN+R, CMD  。enter，cd /d J:\StableDiffusion\sdwebui
2  J:\StableDiffusion\sdwebui\py310\python.exe -m pip uninstall bitsandbytes

3 J:\StableDiffusion\sdwebui\py310\python.exe -m pip uninstall bitsandbytes-windows

4 J:\StableDiffusion\sdwebui\py310\python.exe -m pip install https://github.com/jllllll/bitsandbytes-windows-webui/releases/download/wheels/bitsandbytes-0.41.1-py3-none-win_amd64.whl

Replace your SD venv directory file（python.exe Folder） here（J:\StableDiffusion\sdwebui\py310）
