### ISSUE TITLE
CUDA Setup failed despite GPU being available

### ISSUE THREAD

**Issue by eric-doug** [TimDettmers/bitsandbytes#651]
【Environment Information】
python 3.9.17
CUDA 11.0
bitsandbytes-0.41.0
OS: Ubuntu 18.04

【Install Information】
I am try to install bitsandbytes with source code with the following command:
# git clone --filter=blob:none git@github.com:TimDettmers/bitsandbytes.git
# cd bitsandbytes
# CUDA_VERSION=110 make cuda110_nomatmul
# python setup.py install

【Logging】
![image](https://github.com/TimDettmers/bitsandbytes/assets/104689238/c3696471-b62f-404e-a2bb-d817faa8e15d)

**Comment by YinhaoDeng** [comment]
same issue here.

**Comment by viktor-ferenczi** [comment]
Same issue on Windows

**Comment by dvtushar** [comment]
same issue

**Comment by jb-01** [comment]
First locate your CUDA version path, usually `/usr/local/cuda-XX.X`

Then manually override the Pytorch installed verion using:
```
export BNB_CUDA_VERSION=XXX
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/local/cuda-XX.X
```

Version 11.7 would be:
```
export BNB_CUDA_VERSION=117
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/local/cuda-11.7
```

Refer to: https://github.com/TimDettmers/bitsandbytes/blob/main/how_to_use_nonpytorch_cuda.md

**Comment by YinhaoDeng** [comment]
I assume you are using Windows.
I solved the issue by installing an extra **bitsandbytes** library that was specifically designed for windows. in your environment, try `pip install bitsandbytes-windows`

**Comment by swumagic** [comment]
OR you are  Linux distribution (Ubuntu, MacOS, etc.)system ,AND CUDA Version: 11.X.

Bitsandbytes can support ubuntu.（yuhuang）
1  open folder J:\StableDiffusion\sdwebui，Click the address bar of the folder and enter CMD
or WIN+R, CMD  。enter，cd /d J:\StableDiffusion\sdwebui
2  J:\StableDiffusion\sdwebui\py310\python.exe -m pip uninstall bitsandbytes

3 J:\StableDiffusion\sdwebui\py310\python.exe -m pip uninstall bitsandbytes-windows

4 J:\StableDiffusion\sdwebui\py310\python.exe -m pip install https://github.com/TimDettmers/bitsandbytes/releases/download/0.41.0/bitsandbytes-0.41.0-py3-none-any.whl

Replace your SD venv directory file（python.exe Folder） here（J:\StableDiffusion\sdwebui\py310）
