### ISSUE TITLE
 CUDA Setup failed despite GPU being available. Please run the following command to get more information:

### ISSUE THREAD

**Issue by dvtushar** [TimDettmers/bitsandbytes#653]
my system enviorment-  
python : 3.10.9
cuda - 11
os - windows 11
[
![image](https://github.com/TimDettmers/bitsandbytes/assets/96177523/c8a25669-690b-4bb8-b8d0-a2b32c51e588)
](url)

I get this error everytime i run my code to create a vector space

**Comment by YinhaoDeng** [comment]
same here, I tried running another Pytorch script and it's fine, so weird.

**Comment by wudajun7509** [comment]
pip install bitsandbytes-windows

**Comment by jiangzhuolin** [comment]
I tried to install bitsandbytes-windows but the issue was still exists, I think that it's still not supported for windows at the moment 
![image](https://github.com/TimDettmers/bitsandbytes/assets/10104887/ed1a79ea-991a-48d4-869b-8da4069c4548)

**Comment by MAKEOnesDestiny** [comment]
Same issus, I have forgiving windows11(Not supported yet) and turn to wsl instead

**Comment by dylanxia2017** [comment]
> pip install bitsandbytes-windows

on Linux，still do the "pip install bitsandbytes-windows"？

**Comment by oniondai** [comment]
![image](https://github.com/TimDettmers/bitsandbytes/assets/27003060/df70a3ca-996a-40f9-ad80-b09103b5014e)

**Comment by wangyongshuai88** [comment]
I also encountered the same issue, and I am using WSL2. In this case, installing CUDA doesn't install the driver in the WSL subsystem; instead, it uses the CUDA driver from Windows. 
Another program of mine can  successfully utilize CUDA too.

> same here, I tried running another Pytorch script and it's fine, so weird.

**Comment by dvtushar** [comment]
Thank you 😊

**Comment by Eikwang** [comment]
更新bitsandbytes和bitsandbytes-windows到最新版即可

**Comment by ZzzihaoGuo** [comment]
The version bitsandbytes  should match cuda. of Returned bitsandbytes to 0.39.0 works for me
`pip install bitsandbytes==0.39.0`
