### ISSUE TITLE
Hit by "CUDA Setup failed despite GPU being available" error message when trying to run a sample LLaMA model

### ISSUE THREAD

**Issue by DanielXiao2018** [TimDettmers/bitsandbytes#665]
Dear sir/madam,

I have already installed the PyTorch, CUDA on my local Win11 environment, by following the link below 
https://medium.com/@harunijaz/a-step-by-step-guide-to-installing-cuda-with-pytorch-in-conda-on-windows-verifying-via-console-9ba4cd5ccbef

Thereafter, I composed & run a batch program (the content is shown in the attached file runModel.txt below) to call an example python program to run LLaMA models
[runModel.txt](https://github.com/TimDettmers/bitsandbytes/files/12235454/runModel.txt)

However, all the way I hit the following error message:
"CUDA Setup failed despite GPU being available"

The full output text of running the model is shown in the attached file output.txt below.
[output.txt](https://github.com/TimDettmers/bitsandbytes/files/12235471/output.txt)

Please kindly help me to identify whether this is a bug and show me how to resolve the issue.
Thanks.

**Comment by DanielXiao2018** [comment]
Pls be noted that I am installing & running the LLaMA models on Win 11 environment instead of Linux. Tks.

**Comment by DanielXiao2018** [comment]
It seems that somehow all the way the CUDA run-time library file libcudart.so is not available in the installed CUDA 11.7 libraries. 

Please help me to resolve the issue. Thanks.

**Comment by slyfoxhd** [comment]
Running into the same problem with LLaMA. Same set up, Win 11 and CUDA 11.7.
Any idea would be appreciated.

**Comment by slyfoxhd** [comment]
pip install bitsandbytes-windows

**Comment by atanuGuin** [comment]
Hi, You may try this one -[](https://github.com/jllllll/bitsandbytes-windows-webui). Try installing 0.39.0 version.

**Comment by MuhammadShifa** [comment]
Try this: it's worked for me in Window 10.
```
pip uninstall bitsandbytes
pip install https://github.com/jllllll/bitsandbytes-windows-webui/releases/download/wheels/bitsandbytes-0.41.0-py3-none-win_amd64.whl
```
