### ISSUE TITLE
Setup failed despite GPU available

### ISSUE THREAD

**Issue by JanHmmr** [TimDettmers/bitsandbytes#723]
Hey,
Im on Cuda v11.8.
When trying to run bits and bites it gives me the following error:

_python -m bitsandbytes

warn(msg)
================================================================================
CUDA_SETUP: WARNING! libcudart.so not found in any environmental path. Searching in backup paths...
The following directories listed in your path were found to be non-existent: {WindowsPath('/usr/local/cuda/lib64')}
DEBUG: Possible options found for libcudart.so: set()
CUDA SETUP: PyTorch settings found: CUDA_VERSION=118, Highest Compute Capability: 8.6.
CUDA SETUP: To manually override the PyTorch CUDA version please see:https://github.com/TimDettmers/bitsandbytes/blob/main/how_to_use_nonpytorch_cuda.md
CUDA SETUP: Loading binary C:\Users\Jan Hammer\Pictures\kohya_ss\venv\lib\site-packages\bitsandbytes\libbitsandbytes_cuda118.so...
argument of type 'WindowsPath' is not iterable
CUDA SETUP: Problem: The main issue seems to be that the main CUDA runtime library was not detected.
CUDA SETUP: Solution 1: To solve the issue the libcudart.so location needs to be added to the LD_LIBRARY_PATH variable
CUDA SETUP: Solution 1a): Find the cuda runtime library via: find / -name libcudart.so 2>/dev/null
CUDA SETUP: Solution 1b): Once the library is found add it to the LD_LIBRARY_PATH: export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:FOUND_PATH_FROM_1a
CUDA SETUP: Solution 1c): For a permanent solution add the export from 1b into your .bashrc file, located at ~/.bashrc
CUDA SETUP: Solution 2: If no library was found in step 1a) you need to install CUDA.
CUDA SETUP: Solution 2a): Download CUDA install script: wget https://github.com/TimDettmers/bitsandbytes/blob/main/cuda_install.sh
CUDA SETUP: Solution 2b): Install desired CUDA version to desired location. The syntax is bash cuda_install.sh CUDA_VERSION PATH_TO_INSTALL_INTO.
CUDA SETUP: Solution 2b): For example, "bash cuda_install.sh 113 ~/local/" will download CUDA 11.3 and install into the folder ~/local
Traceback (most recent call last):
  File "C:\Users\Jan Hammer\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 187, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "C:\Users\Jan Hammer\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 146, in _get_module_details
    return _get_module_details(pkg_main_name, error)
  File "C:\Users\Jan Hammer\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 110, in _get_module_details
    __import__(pkg_name)
  File "C:\Users\Jan Hammer\Pictures\kohya_ss\venv\lib\site-packages\bitsandbytes\__init__.py", line 6, in <module>
    from . import cuda_setup, utils, research
  File "C:\Users\Jan Hammer\Pictures\kohya_ss\venv\lib\site-packages\bitsandbytes\research\__init__.py", line 1, in <module>
    from . import nn
  File "C:\Users\Jan Hammer\Pictures\kohya_ss\venv\lib\site-packages\bitsandbytes\research\nn\__init__.py", line 1, in <module>
    from .modules import LinearFP8Mixed, LinearFP8Global
  File "C:\Users\Jan Hammer\Pictures\kohya_ss\venv\lib\site-packages\bitsandbytes\research\nn\modules.py", line 8, in <module>
    from bitsandbytes.optim import GlobalOptimManager
  File "C:\Users\Jan Hammer\Pictures\kohya_ss\venv\lib\site-packages\bitsandbytes\optim\__init__.py", line 6, in <module>
    from bitsandbytes.cextension import COMPILED_WITH_CUDA
  File "C:\Users\Jan Hammer\Pictures\kohya_ss\venv\lib\site-packages\bitsandbytes\cextension.py", line 20, in <module>
    raise RuntimeError('''
RuntimeError:
        CUDA Setup failed despite GPU being available. Please run the following command to get more information:

        python -m bitsandbytes

        Inspect the output of the command and see if you can locate CUDA libraries. You might need to add them
        to your LD_LIBRARY_PATH. If you suspect a bug, please take the information from python -m bitsandbytes
        and open an issue at: https://github.com/TimDettmers/bitsandbytes/issues

(venv) C:\Users\Jan Hammer\Pictures\kohya_ss>_

Does anyone know what the issue could be?

**Comment by mlwei1** [comment]
same error , i tried cuda 11.7 and 11.8 in env but didnt solve

**Comment by t170815518** [comment]
I encountered the same issue on CUDA 11.6 and fixed it by building bitsandbytes from source. Below is my bash script for reference:

```bash
pip3 uninstall -y bitsandbytes 
git clone https://github.com/TimDettmers/bitsandbytes.git
cd bitsandbytes || exit
make CUDA_VERSION=116  # or 117, depending on the local CUDA version 
export PYTHONPATH=$PYTHONPATH:<EEG_PATH_OF_BUILT_PACKAGE>  # add the built package to pythonpath in case there is import error
python setup.py install 
```

**Comment by t170815518** [comment]
@richardsun-voyager 
`<EGG_PATH_OF_BUILT_PACKAGE>` refers to the directory where the built package (e.g., mine is like `xxx.egg`) is located. This is needed if the setup location is not included in PYTHONPATH yet

**Comment by nrjvarshney** [comment]
How can I find "EGG_PATH_OF_BUILT_PACKAGE" location @t170815518

**Comment by t170815518** [comment]
It's needed when the package is not installed at the default place, and `EGG_PATH_OF_BUILT_PACKAGE` will be specified by the user.

**Comment by GasolSun36** [comment]
> I encountered the same issue on CUDA 11.6 and fixed it by building bitsandbytes from source. Below is my bash script for reference:
> 
> ```shell
> pip3 uninstall -y bitsandbytes 
> git clone https://github.com/TimDettmers/bitsandbytes.git
> cd bitsandbytes || exit
> make CUDA_VERSION=116  # or 117, depending on the local CUDA version 
> python setup.py install 
> export PYTHONPATH=$PYTHONPATH:<EGG_PATH_OF_BUILT_PACKAGE>  # needed if the package is installed in non-default location
> ```

thanks a lot! this solved my issues.

**Comment by jackyLens** [comment]
> I encountered the same issue on CUDA 11.6 and fixed it by building bitsandbytes from source. Below is my bash script for reference:
> 
> ```shell
> pip3 uninstall -y bitsandbytes 
> git clone https://github.com/TimDettmers/bitsandbytes.git
> cd bitsandbytes || exit
> make CUDA_VERSION=116  # or 117, depending on the local CUDA version 
> python setup.py install 
> export PYTHONPATH=$PYTHONPATH:<EGG_PATH_OF_BUILT_PACKAGE>  # needed if the package is installed in non-default location
> ```

yes,it solved my issues

**Comment by kbmlcoding** [comment]
@jackyLens @GasolSun36 what gcc version did you use for this

**Comment by swumagic** [comment]
Bitsandbytes was not supported windows before, but my method can support windows.（yuhuang）
1  open folder J:\StableDiffusion\sdwebui，Click the address bar of the folder and enter CMD
or WIN+R, CMD  。enter，cd /d J:\StableDiffusion\sdwebui
2  J:\StableDiffusion\sdwebui\py310\python.exe -m pip uninstall bitsandbytes

3 J:\StableDiffusion\sdwebui\py310\python.exe -m pip uninstall bitsandbytes-windows

4 J:\StableDiffusion\sdwebui\py310\python.exe -m pip install https://github.com/jllllll/bitsandbytes-windows-webui/releases/download/wheels/bitsandbytes-0.41.1-py3-none-win_amd64.whl

Replace your SD venv directory file（python.exe Folder） here（J:\StableDiffusion\sdwebui\py310）

**Comment by keitaro2002** [comment]
> I encountered the same issue on CUDA 11.6 and fixed it by building bitsandbytes from source. Below is my bash script for reference:
> 
> ```shell
> pip3 uninstall -y bitsandbytes 
> git clone https://github.com/TimDettmers/bitsandbytes.git
> cd bitsandbytes || exit
> make CUDA_VERSION=116  # or 117, depending on the local CUDA version 
> python setup.py install 
> export PYTHONPATH=$PYTHONPATH:<EGG_PATH_OF_BUILT_PACKAGE>  # needed if the package is installed in non-default location
> ```

I couldn't find Makefile in bitsandbytes directory and `make CUDA_VERSION=116` doesn't work.
Could you tell me how to solve this problem.
