### ISSUE TITLE
CUDA_SETUP: WARNING! libcudart.so not found in any environmental path. Searching in backup paths.

### ISSUE THREAD

**Issue by SK12138** [TimDettmers/bitsandbytes#741]
Python\Python311\Lib\site-packages\bitsandbytes\cuda_setup\main.py:166: UserWarning: Welcome to bitsandbytes. For bug reports, please run

python -m bitsandbytes

  warn(msg)
================================================================================
CUDA_SETUP: WARNING! libcudart.so not found in any environmental path. Searching in backup paths...
The following directories listed in your path were found to be non-existent: {WindowsPath('/usr/local/cuda/lib64')}
DEBUG: Possible options found for libcudart.so: set()
CUDA SETUP: PyTorch settings found: CUDA_VERSION=121, Highest Compute Capability: 8.6.
CUDA SETUP: To manually override the PyTorch CUDA version please see:https://github.com/TimDettmers/bitsandbytes/blob/main/how_to_use_nonpytorch_cuda.md
CUDA SETUP: Loading binary C:\Users\SK\AppData\Local\Programs\Python\Python311\Lib\site-packages\bitsandbytes\libbitsandbytes_cuda121.so...
argument of type 'WindowsPath' is not iterable
CUDA SETUP: Problem: The main issue seems to be that the main CUDA runtime library was not detected.
CUDA SETUP: Solution 1: To solve the issue the libcudart.so location needs to be added to the LD_LIBRARY_PATH variable
CUDA SETUP: Solution 1a): Find the cuda runtime library via: find / -name libcudart.so 2>/dev/null
CUDA SETUP: Solution 1b): Once the library is found add it to the LD_LIBRARY_PATH: export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:FOUND_PATH_FROM_1a
CUDA SETUP: Solution 1c): For a permanent solution add the export from 1b into your .bashrc file, located at ~/.bashrc
CUDA SETUP: Solution 2: If no library was found in step 1a) you need to install CUDA.
CUDA SETUP: Solution 2a): Download CUDA install script: wget https://github.com/TimDettmers/bitsandbytes/blob/main/cuda_install.sh
CUDA SETUP: Solution 2b): Install desired CUDA version to desired location. The syntax is bash cuda_install.sh CUDA_VERSION PATH_TO_INSTALL_INTO.
CUDA SETUP: Solution 2b): For example, "bash cuda_install.sh 113 ~/local/" will download CUDA 11.3 and install into the folder ~/local

if anyone can help me, I do't know how to deal with this
![Snipaste_2023-09-01_17-26-35](https://github.com/TimDettmers/bitsandbytes/assets/48514994/0c250fbd-ddd7-498b-a122-4b383fb02afb)

**Comment by bodgeybodgeybodgey** [comment]
getting the same error

**Comment by ElizabethCappon** [comment]
same error, following

**Comment by alaeddine-abbagh** [comment]
same error

**Comment by M-Juhasz** [comment]
Same here - if I understand correctly, bitandbytes does not work under windows, as it's looking for a cuda .so file, and that is a linux specific format corresponding to windows .dll. See bitsandbytes readme: "**Requirements Python >=3.8. Linux distribution (Ubuntu, MacOS, etc.) + CUDA > 10.0.**". There is a 'bitandbytes-windows' library (https://pypi.org/project/bitsandbytes-windows/), but for me bitandbytes is required by the transformers library.

One way for windows users would be to use WSL to set up a linux VM, install cuda there and run your scripts in the VM. 
Still, any workaround to make this work with windows would be appreciated.

**Comment by ElizabethCappon** [comment]
I'm on Ubuntu 20.04, python 3.10

Solved by adding the following to my .bashrc script (replace 118 and 11.8 with your cuda version, and check if this is indeed the correct path on your machine):

```
BNB_CUDA_VERSION=118
export PATH="/usr/local/cuda-11.8/bin:$PATH"
export LD_LIBRARY_PATH="/usr/local/cuda-11.8/lib64:$LD_LIBRARY_PATH"
```

I AM still getting the same error in Jupyter notebooks though. Maybe could be fixed using `os.environ`.

**Comment by planb788** [comment]
you should do this:

1. pip uninstall bitsandbytes
2. pip install https://github.com/jllllll/bitsandbytes-windows-webui/releases/download/wheels/bitsandbytes-0.41.0-py3-none-win_amd64.whl

Why? Because you've downloaded a version of Bitsandbytes that isn't suitable for Windows, these tips are all for the Linux version to go wrong and will mislead you.

**Comment by swumagic** [comment]
> Python\Python311\Lib\site-packages\bitsandbytes\cuda_setup\main.py:166: UserWarning: Welcome to bitsandbytes. For bug reports, please runPython\Python311\Lib\site-packages\bitsandbytes\cuda_setup\main.py:166：用户警告：欢迎使用 bitsandbytes。对于错误报告，请运行
> 
> python -m bitsandbytes python -m 位字节
> 
> # warn(msg) 警告（MSG）
> CUDA_SETUP: WARNING! libcudart.so not found in any environmental path. Searching in backup paths...CUDA_SETUP：警告！libcudart.so 在任何环境路径中都找不到。正在搜索备份路径... The following directories listed in your path were found to be non-existent: {WindowsPath('/usr/local/cuda/lib64')}发现路径中列出的以下目录不存在：{WindowsPath（'/usr/local/cuda/lib64'）} DEBUG: Possible options found for libcudart.so: set()DEBUG：为 libcudart.so 找到的可能选项：set（） CUDA SETUP: PyTorch settings found: CUDA_VERSION=121, Highest Compute Capability: 8.6.CUDA 设置：找到 PyTorch 设置：CUDA_VERSION=121，最高计算能力：8.6。 CUDA SETUP: To manually override the PyTorch CUDA version please see:https://github.com/TimDettmers/bitsandbytes/blob/main/how_to_use_nonpytorch_cuda.mdCUDA 设置：要手动覆盖 PyTorch CUDA 版本，请参阅：https://github.com/TimDettmers/bitsandbytes/blob/main/how_to_use_nonpytorch_cuda.md CUDA SETUP: Loading binary C:\Users\SK\AppData\Local\Programs\Python\Python311\Lib\site-packages\bitsandbytes\libbitsandbytes_cuda121.so...CUDA 设置：加载二进制 C：\Users\SK\AppData\Local\Programs\Python\Python311\Lib\site-packages\bitsandbytes\libbitsandbytes_cuda121.so... argument of type 'WindowsPath' is not iterable类型为“WindowsPath”的参数不可迭代 CUDA SETUP: Problem: The main issue seems to be that the main CUDA runtime library was not detected.CUDA 设置： 问题：主要问题似乎是未检测到主 CUDA 运行时库。 CUDA SETUP: Solution 1: To solve the issue the libcudart.so location needs to be added to the LD_LIBRARY_PATH variableCUDA 设置： 解决方案 1：要解决此问题，需要将 libcudart.so 位置添加到LD_LIBRARY_PATH变量中 CUDA SETUP: Solution 1a): Find the cuda runtime library via: find / -name libcudart.so 2>/dev/nullCUDA 设置： 解决方案 1a）：通过以下方式查找 cuda 运行时库： find / -name libcudart.so 2>/dev/null CUDA SETUP: Solution 1b): Once the library is found add it to the LD_LIBRARY_PATH: export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:FOUND_PATH_FROM_1aCUDA 设置： 解决方案 1b）：找到库后，将其添加到LD_LIBRARY_PATH：export LD_LIBRARY_PATH=$LD_LIBRARY_PATH：FOUND_PATH_FROM_1a CUDA SETUP: Solution 1c): For a permanent solution add the export from 1b into your .bashrc file, located at ~/.bashrcCUDA 设置： 解决方案 1c）：对于永久解决方案，将 1b 的导出添加到位于 ~/.bashrc 的 .bashrc 文件中 CUDA SETUP: Solution 2: If no library was found in step 1a) you need to install CUDA.CUDA 设置： 解决方案 2：如果在步骤 1a） 中未找到库，则需要安装 CUDA。 CUDA SETUP: Solution 2a): Download CUDA install script: wget https://github.com/TimDettmers/bitsandbytes/blob/main/cuda_install.shCUDA设置： 解决方案 2a）： 下载 CUDA 安装脚本： wget https://github.com/TimDettmers/bitsandbytes/blob/main/cuda_install.sh CUDA SETUP: Solution 2b): Install desired CUDA version to desired location. The syntax is bash cuda_install.sh CUDA_VERSION PATH_TO_INSTALL_INTO.CUDA 设置：解决方案 2b）：将所需的 CUDA 版本安装到所需的位置。语法为 bash cuda_install.sh CUDA_VERSION PATH_TO_INSTALL_INTO。 CUDA SETUP: Solution 2b): For example, "bash cuda_install.sh 113 ~/local/" will download CUDA 11.3 and install into the folder ~/localCUDA 设置： 解决方案 2b）：例如，“bash cuda_install.sh 113 ~/local/”将下载 CUDA 11.3 并安装到文件夹 ~/local 中
> 
> if anyone can help me, I do't know how to deal with this如果有人能帮我，我不知道如何处理这个问题 ![Snipaste_2023-09-01_17-26-35](https://user-images.githubusercontent.com/48514994/264982491-0c250fbd-ddd7-498b-a122-4b383fb02afb.png)

Bitsandbytes was not supported windows before, but my method can support windows.（yuhuang）
1  open folder J:\StableDiffusion\sdwebui，Click the address bar of the folder and enter CMD
or WIN+R, CMD  。enter，cd /d J:\StableDiffusion\sdwebui
2  J:\StableDiffusion\sdwebui\py310\python.exe -m pip uninstall bitsandbytes

3 J:\StableDiffusion\sdwebui\py310\python.exe -m pip uninstall bitsandbytes-windows

4 J:\StableDiffusion\sdwebui\py310\python.exe -m pip install https://github.com/jllllll/bitsandbytes-windows-webui/releases/download/wheels/bitsandbytes-0.41.1-py3-none-win_amd64.whl

Replace your SD venv directory file（python.exe Folder） here（J:\StableDiffusion\sdwebui\py310）

**Comment by swumagic** [comment]
OR you are  Linux distribution (Ubuntu, MacOS, etc.)system ,AND CUDA Version: 11.X.

Bitsandbytes can support ubuntu.（yuhuang）
1  open folder J:\StableDiffusion\sdwebui，Click the address bar of the folder and enter CMD
or WIN+R, CMD  。enter，cd /d J:\StableDiffusion\sdwebui
2  J:\StableDiffusion\sdwebui\py310\python.exe -m pip uninstall bitsandbytes

3 J:\StableDiffusion\sdwebui\py310\python.exe -m pip uninstall bitsandbytes-windows

4 J:\StableDiffusion\sdwebui\py310\python.exe -m pip install https://github.com/TimDettmers/bitsandbytes/releases/download/0.41.0/bitsandbytes-0.41.0-py3-none-any.whl

Replace your SD venv directory file（python.exe Folder） here（J:\StableDiffusion\sdwebui\py310）

**Comment by AmazingGabriel16** [comment]
For future reference:

Version 0.46 works with Windows.

I previously had 0.40 which did not work and resulted in this error.
