### ISSUE TITLE
CUDA SETUP: CUDA detection failed! 

### ISSUE THREAD

**Issue by victor-buhl** [TimDettmers/bitsandbytes#742]
================================================================================
bin /home/victor.buhl@ern.nps.edu/miniconda3/envs/llama_fine/lib/python3.9/site-packages/bitsandbytes/libbitsandbytes_cuda122.so
False
CUDA_SETUP: WARNING! libcudart.so not found in any environmental path. Searching in backup paths...
CUDA SETUP: CUDA runtime path found: /usr/local/cuda/lib64/libcudart.so
CUDA SETUP: Highest compute capability among GPUs detected: 7.5
CUDA SETUP: Detected CUDA version 122
CUDA SETUP: Required library version not found: libbitsandbytes_cuda122.so. Maybe you need to compile it from source?
CUDA SETUP: Defaulting to libbitsandbytes_cpu.so...

================================================ERROR=====================================
CUDA SETUP: CUDA detection failed! Possible reasons:
1. CUDA driver not installed
2. CUDA not installed
3. You have multiple conflicting CUDA libraries
4. Required library not pre-compiled for this bitsandbytes release!
CUDA SETUP: If you compiled from source, try again with `make CUDA_VERSION=DETECTED_CUDA_VERSION` for example, `make CUDA_VERSION=113`.
CUDA SETUP: The CUDA version for the compile might depend on your conda install. Inspect CUDA version via `conda list | grep cuda`.
================================================================================

CUDA SETUP: Something unexpected happened. Please compile from source:
git clone git@github.com:TimDettmers/bitsandbytes.git
cd bitsandbytes
CUDA_VERSION=122
python setup.py install
CUDA SETUP: Setup Failed!

**Comment by XinXinShawn** [comment]
Same question. I resoved it by upgrade bitsandbytes. pip install --upgrade bitsandbytes

**Comment by buzhihuoyefeng** [comment]
> Same question. I resoved it by upgrade bitsandbytes. pip install --upgrade bitsandbytes

can you tell me bitsandbytes version and python version?

**Comment by victor-buhl** [comment]
I believe I was able to resolve the issue by upgrading bitsandbytes.

**Comment by XinXinShawn** [comment]
> > Same question. I resoved it by upgrade bitsandbytes. pip install --upgrade bitsandbytes
> 
> can you tell me bitsandbytes version and python version?
bitsandbytes  0.41.1
python  3.9.16

**Comment by swumagic** [comment]
Bitsandbytes was not supported windows before, but my method can support windows.（yuhuang）
1  open folder J:\StableDiffusion\sdwebui，Click the address bar of the folder and enter CMD
or WIN+R, CMD  。enter，cd /d J:\StableDiffusion\sdwebui
2  J:\StableDiffusion\sdwebui\py310\python.exe -m pip uninstall bitsandbytes

3 J:\StableDiffusion\sdwebui\py310\python.exe -m pip uninstall bitsandbytes-windows

4 J:\StableDiffusion\sdwebui\py310\python.exe -m pip install https://github.com/jllllll/bitsandbytes-windows-webui/releases/download/wheels/bitsandbytes-0.41.1-py3-none-win_amd64.whl

Replace your SD venv directory file（python.exe Folder） here（J:\StableDiffusion\sdwebui\py310）
