### ISSUE TITLE
RuntimeError:          CUDA Setup failed despite GPU being available. Please run the following command to get more information:          python -m bitsandbytes

### ISSUE THREAD

**Issue by tiamojames** [TimDettmers/bitsandbytes#748]
CUDA_SETUP: WARNING! libcudart.so not found in any environmental path. Searching in backup paths...
CUDA SETUP: WARNING! libcuda.so not found! Do you have a CUDA driver installed? If you are on a cluster, make sure you are on a CUDA machine!
CUDA SETUP: Loading binary D:\Anaconda\envs\summer2023\lib\site-packages\bitsandbytes\libbitsandbytes_cpu.so...
argument of type 'WindowsPath' is not iterable
CUDA SETUP: Problem: The main issue seems to be that the main CUDA library was not detected.
CUDA SETUP: Solution 1): Your paths are probably not up-to-date. You can update them via: sudo ldconfig.
CUDA SETUP: Solution 2): If you do not have sudo rights, you can do the following:
CUDA SETUP: Solution 2a): Find the cuda library via: find / -name libcuda.so 2>/dev/null
CUDA SETUP: Solution 2b): Once the library is found add it to the LD_LIBRARY_PATH: export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:FOUND_PATH_FROM_2a
CUDA SETUP: Solution 2c): For a permanent solution add the export from 2b into your .bashrc file, located at ~/.bashrc
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
Cell In[2], line 6
      4 model_id="/llama/models_hf/7B"
      5 tokenizer = LlamaTokenizer.from_pretrained(model_id)
----> 6 model =LlamaForCausalLM.from_pretrained(model_id, load_in_8bit=True, device_map='auto', torch_dtype=torch.float16)

File D:\Anaconda\envs\summer2023\lib\site-packages\transformers\modeling_utils.py:2710, in PreTrainedModel.from_pretrained(cls, pretrained_model_name_or_path, config, cache_dir, ignore_mismatched_sizes, force_download, local_files_only, token, revision, use_safetensors, *model_args, **kwargs)
   2707     keep_in_fp32_modules = []
   2709 if load_in_8bit or load_in_4bit:
-> 2710     from .utils.bitsandbytes import get_keys_to_not_convert, replace_with_bnb_linear
   2712     llm_int8_skip_modules = quantization_config.llm_int8_skip_modules
   2713     load_in_8bit_fp32_cpu_offload = quantization_config.llm_int8_enable_fp32_cpu_offload

File D:\Anaconda\envs\summer2023\lib\site-packages\transformers\utils\bitsandbytes.py:12
      8 from .import_utils import is_accelerate_available, is_bitsandbytes_available
     11 if is_bitsandbytes_available():
---> 12     import bitsandbytes as bnb
     13     import torch
     14     import torch.nn as nn

File D:\Anaconda\envs\summer2023\lib\site-packages\bitsandbytes\__init__.py:6
      1 # Copyright (c) Facebook, Inc. and its affiliates.
      2 #
      3 # This source code is licensed under the MIT license found in the
      4 # LICENSE file in the root directory of this source tree.
----> 6 from . import cuda_setup, utils, research
      7 from .autograd._functions import (
      8     MatmulLtState,
      9     bmm_cublas,
   (...)
     13     matmul_4bit
     14 )
     15 from .cextension import COMPILED_WITH_CUDA

File D:\Anaconda\envs\summer2023\lib\site-packages\bitsandbytes\research\__init__.py:1
----> 1 from . import nn
      2 from .autograd._functions import (
      3     switchback_bnb,
      4     matmul_fp8_global,
      5     matmul_fp8_mixed,
      6 )

File D:\Anaconda\envs\summer2023\lib\site-packages\bitsandbytes\research\nn\__init__.py:1
----> 1 from .modules import LinearFP8Mixed, LinearFP8Global

File D:\Anaconda\envs\summer2023\lib\site-packages\bitsandbytes\research\nn\modules.py:8
      5 from torch import Tensor, device, dtype, nn
      7 import bitsandbytes as bnb
----> 8 from bitsandbytes.optim import GlobalOptimManager
      9 from bitsandbytes.utils import OutlierTracer, find_outlier_dims
     11 T = TypeVar("T", bound="torch.nn.Module")

File D:\Anaconda\envs\summer2023\lib\site-packages\bitsandbytes\optim\__init__.py:6
      1 # Copyright (c) Facebook, Inc. and its affiliates.
      2 #
      3 # This source code is licensed under the MIT license found in the
      4 # LICENSE file in the root directory of this source tree.
----> 6 from bitsandbytes.cextension import COMPILED_WITH_CUDA
      8 from .adagrad import Adagrad, Adagrad8bit, Adagrad32bit
      9 from .adam import Adam, Adam8bit, Adam32bit, PagedAdam, PagedAdam8bit, PagedAdam32bit

File D:\Anaconda\envs\summer2023\lib\site-packages\bitsandbytes\cextension.py:20
     18     CUDASetup.get_instance().generate_instructions()
     19     CUDASetup.get_instance().print_log_stack()
---> 20     raise RuntimeError('''
     21     CUDA Setup failed despite GPU being available. Please run the following command to get more information:
     22 
     23     python -m bitsandbytes
     24 
     25     Inspect the output of the command and see if you can locate CUDA libraries. You might need to add them
     26     to your LD_LIBRARY_PATH. If you suspect a bug, please take the information from python -m bitsandbytes
     27     and open an issue at: https://github.com/TimDettmers/bitsandbytes/issues''')
     28 lib.cadam32bit_grad_fp32 # runs on an error if the library could not be found -> COMPILED_WITH_CUDA=False
     29 lib.get_context.restype = ct.c_void_p

RuntimeError: 
        CUDA Setup failed despite GPU being available. Please run the following command to get more information:

        python -m bitsandbytes

        Inspect the output of the command and see if you can locate CUDA libraries. You might need to add them
        to your LD_LIBRARY_PATH. If you suspect a bug, please take the information from python -m bitsandbytes
        and open an issue at: https://github.com/TimDettmers/bitsandbytes/issues

**Comment by rfroli** [comment]
Same here, with Nvidia SDK 1.8 / Windows / pytorch https://download.pytorch.org/whl/cu118
Thjere is no libcudart file on my system

**Comment by fillsok** [comment]
same

(venv) PS D:\code\llama2\llama_inference> python -m bitsandbytes
False

===================================BUG REPORT===================================
D:\code\llama2\llama_inference\venv\lib\site-packages\bitsandbytes\cuda_setup\main.py:166: UserWarning: Welcome to bitsandbytes. For bug reports, please run

python -m bitsandbytes


  warn(msg)
================================================================================
The following directories listed in your path were found to be non-existent: {WindowsPath('/storage.flutter-io.cn'), WindowsPath('https')}
The following directories listed in your path were found to be non-existent: {WindowsPath('https'), WindowsPath('/goproxy.io,direct')}
The following directories listed in your path were found to be non-existent: {WindowsPath('https'), WindowsPath('/pub.flutter-io.cn')}
CUDA_SETUP: WARNING! libcudart.so not found in any environmental path. Searching in backup paths...
The following directories listed in your path were found to be non-existent: {WindowsPath('/usr/local/cuda/lib64')}
DEBUG: Possible options found for libcudart.so: set()
CUDA SETUP: PyTorch settings found: CUDA_VERSION=118, Highest Compute Capability: 8.6.
CUDA SETUP: To manually override the PyTorch CUDA version please see:https://github.com/TimDettmers/bitsandbytes/blob/main/how_to_use_nonpytorch_cuda.md
CUDA SETUP: Loading binary D:\code\llama2\llama_inference\venv\lib\site-packages\bitsandbytes\libbitsandbytes_cuda118.so...
argument of type 'WindowsPath' is not iterable
CUDA SETUP: Problem: The main issue seems to be that the main CUDA runtime library was not detected.
CUDA SETUP: Solution 1: To solve the issue the libcudart.so location needs to be added to the LD_LIBRARY_PATH variable
CUDA SETUP: Solution 1a): Find the cuda runtime library via: find / -name libcudart.so 2>/dev/null
CUDA SETUP: Solution 1b): Once the library is found add it to the LD_LIBRARY_PATH: export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:FOUND_PATH_FROM_1a
CUDA SETUP: Solution 1c): For a permanent solution add the export from 1b into your .bashrc file, located at ~/.bashrc
CUDA SETUP: Solution 2: If no library was found in step 1a) you need to install CUDA.
CUDA SETUP: Solution 2a): Download CUDA install script: wget https://github.com/TimDettmers/bitsandbytes/blob/main/cuda_install.sh
CUDA SETUP: Solution 2b): Install desired CUDA version to desired location. The syntax is bash cuda_install.sh CUDA_VERSION PATH_TO_INSTALL_INTO.
CUDA SETUP: Solution 2b): For example, "bash cuda_install.sh 113 ~/local/" will download CUDA 11.3 and install into the folder ~/local
Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\runpy.py", line 187, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\runpy.py", line 146, in _get_module_details
    return _get_module_details(pkg_main_name, error)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\runpy.py", line 110, in _get_module_details
    __import__(pkg_name)
  File "D:\code\llama2\llama_inference\venv\lib\site-packages\bitsandbytes\__init__.py", line 6, in <module>
    from . import cuda_setup, utils, research
  File "D:\code\llama2\llama_inference\venv\lib\site-packages\bitsandbytes\research\__init__.py", line 1, in <module>
    from . import nn
  File "D:\code\llama2\llama_inference\venv\lib\site-packages\bitsandbytes\research\nn\__init__.py", line 1, in <module>
    from .modules import LinearFP8Mixed, LinearFP8Global
  File "D:\code\llama2\llama_inference\venv\lib\site-packages\bitsandbytes\research\nn\modules.py", line 8, in <module>
    from bitsandbytes.optim import GlobalOptimManager
  File "D:\code\llama2\llama_inference\venv\lib\site-packages\bitsandbytes\optim\__init__.py", line 6, in <module>
    from bitsandbytes.cextension import COMPILED_WITH_CUDA
  File "D:\code\llama2\llama_inference\venv\lib\site-packages\bitsandbytes\cextension.py", line 20, in <module>
    raise RuntimeError('''
RuntimeError:
        CUDA Setup failed despite GPU being available. Please run the following command to get more information:

        python -m bitsandbytes

        Inspect the output of the command and see if you can locate CUDA libraries. You might need to add them
        to your LD_LIBRARY_PATH. If you suspect a bug, please take the information from python -m bitsandbytes
        and open an issue at: https://github.com/TimDettmers/bitsandbytes/issues

**Comment by fillsok** [comment]
> same
> 
> (venv) PS D:\code\llama2\llama_inference> python -m bitsandbytes False
> 
> ===================================BUG REPORT=================================== D:\code\llama2\llama_inference\venv\lib\site-packages\bitsandbytes\cuda_setup\main.py:166: UserWarning: Welcome to bitsandbytes. For bug reports, please run
> 
> python -m bitsandbytes
> 
> # warn(msg)
> The following directories listed in your path were found to be non-existent: {WindowsPath('/storage.flutter-io.cn'), WindowsPath('https')} The following directories listed in your path were found to be non-existent: {WindowsPath('https'), WindowsPath('/goproxy.io,direct')} The following directories listed in your path were found to be non-existent: {WindowsPath('https'), WindowsPath('/pub.flutter-io.cn')} CUDA_SETUP: WARNING! libcudart.so not found in any environmental path. Searching in backup paths... The following directories listed in your path were found to be non-existent: {WindowsPath('/usr/local/cuda/lib64')} DEBUG: Possible options found for libcudart.so: set() CUDA SETUP: PyTorch settings found: CUDA_VERSION=118, Highest Compute Capability: 8.6. CUDA SETUP: To manually override the PyTorch CUDA version please see:https://github.com/TimDettmers/bitsandbytes/blob/main/how_to_use_nonpytorch_cuda.md CUDA SETUP: Loading binary D:\code\llama2\llama_inference\venv\lib\site-packages\bitsandbytes\libbitsandbytes_cuda118.so... argument of type 'WindowsPath' is not iterable CUDA SETUP: Problem: The main issue seems to be that the main CUDA runtime library was not detected. CUDA SETUP: Solution 1: To solve the issue the libcudart.so location needs to be added to the LD_LIBRARY_PATH variable CUDA SETUP: Solution 1a): Find the cuda runtime library via: find / -name libcudart.so 2>/dev/null CUDA SETUP: Solution 1b): Once the library is found add it to the LD_LIBRARY_PATH: export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:FOUND_PATH_FROM_1a CUDA SETUP: Solution 1c): For a permanent solution add the export from 1b into your .bashrc file, located at ~/.bashrc CUDA SETUP: Solution 2: If no library was found in step 1a) you need to install CUDA. CUDA SETUP: Solution 2a): Download CUDA install script: wget https://github.com/TimDettmers/bitsandbytes/blob/main/cuda_install.sh CUDA SETUP: Solution 2b): Install desired CUDA version to desired location. The syntax is bash cuda_install.sh CUDA_VERSION PATH_TO_INSTALL_INTO. CUDA SETUP: Solution 2b): For example, "bash cuda_install.sh 113 ~/local/" will download CUDA 11.3 and install into the folder ~/local Traceback (most recent call last): File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\runpy.py", line 187, in _run_module_as_main mod_name, mod_spec, code = _get_module_details(mod_name, _Error) File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\runpy.py", line 146, in _get_module_details return _get_module_details(pkg_main_name, error) File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\runpy.py", line 110, in _get_module_details **import**(pkg_name) File "D:\code\llama2\llama_inference\venv\lib\site-packages\bitsandbytes__init__.py", line 6, in from . import cuda_setup, utils, research File "D:\code\llama2\llama_inference\venv\lib\site-packages\bitsandbytes\research__init__.py", line 1, in from . import nn File "D:\code\llama2\llama_inference\venv\lib\site-packages\bitsandbytes\research\nn__init_.py", line 1, in from .modules import LinearFP8Mixed, LinearFP8Global File "D:\code\llama2\llama_inference\venv\lib\site-packages\bitsandbytes\research\nn\modules.py", line 8, in from bitsandbytes.optim import GlobalOptimManager File "D:\code\llama2\llama_inference\venv\lib\site-packages\bitsandbytes\optim__init_.py", line 6, in from bitsandbytes.cextension import COMPILED_WITH_CUDA File "D:\code\llama2\llama_inference\venv\lib\site-packages\bitsandbytes\cextension.py", line 20, in raise RuntimeError(''' RuntimeError: CUDA Setup failed despite GPU being available. Please run the following command to get more information:__
> 
> ```
>     python -m bitsandbytes
> 
>     Inspect the output of the command and see if you can locate CUDA libraries. You might need to add them
>     to your LD_LIBRARY_PATH. If you suspect a bug, please take the information from python -m bitsandbytes
>     and open an issue at: https://github.com/TimDettmers/bitsandbytes/issues
> ```

My setup  LD_LIBRARY_PATH = C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v12.1\lib\x64

**Comment by tiamojames** [comment]
> > same
> > (venv) PS D:\code\llama2\llama_inference> python -m bitsandbytes False
> > ===================================BUG REPORT=================================== D:\code\llama2\llama_inference\venv\lib\site-packages\bitsandbytes\cuda_setup\main.py:166: UserWarning: Welcome to bitsandbytes. For bug reports, please run
> > python -m bitsandbytes
> > # warn(msg)
> > The following directories listed in your path were found to be non-existent: {WindowsPath('/storage.flutter-io.cn'), WindowsPath('https')} The following directories listed in your path were found to be non-existent: {WindowsPath('https'), WindowsPath('/goproxy.io,direct')} The following directories listed in your path were found to be non-existent: {WindowsPath('https'), WindowsPath('/pub.flutter-io.cn')} CUDA_SETUP: WARNING! libcudart.so not found in any environmental path. Searching in backup paths... The following directories listed in your path were found to be non-existent: {WindowsPath('/usr/local/cuda/lib64')} DEBUG: Possible options found for libcudart.so: set() CUDA SETUP: PyTorch settings found: CUDA_VERSION=118, Highest Compute Capability: 8.6. CUDA SETUP: To manually override the PyTorch CUDA version please see:https://github.com/TimDettmers/bitsandbytes/blob/main/how_to_use_nonpytorch_cuda.md CUDA SETUP: Loading binary D:\code\llama2\llama_inference\venv\lib\site-packages\bitsandbytes\libbitsandbytes_cuda118.so... argument of type 'WindowsPath' is not iterable CUDA SETUP: Problem: The main issue seems to be that the main CUDA runtime library was not detected. CUDA SETUP: Solution 1: To solve the issue the libcudart.so location needs to be added to the LD_LIBRARY_PATH variable CUDA SETUP: Solution 1a): Find the cuda runtime library via: find / -name libcudart.so 2>/dev/null CUDA SETUP: Solution 1b): Once the library is found add it to the LD_LIBRARY_PATH: export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:FOUND_PATH_FROM_1a CUDA SETUP: Solution 1c): For a permanent solution add the export from 1b into your .bashrc file, located at ~/.bashrc CUDA SETUP: Solution 2: If no library was found in step 1a) you need to install CUDA. CUDA SETUP: Solution 2a): Download CUDA install script: wget https://github.com/TimDettmers/bitsandbytes/blob/main/cuda_install.sh CUDA SETUP: Solution 2b): Install desired CUDA version to desired location. The syntax is bash cuda_install.sh CUDA_VERSION PATH_TO_INSTALL_INTO. CUDA SETUP: Solution 2b): For example, "bash cuda_install.sh 113 ~/local/" will download CUDA 11.3 and install into the folder ~/local Traceback (most recent call last): File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\runpy.py", line 187, in _run_module_as_main mod_name, mod_spec, code = _get_module_details(mod_name, _Error) File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\runpy.py", line 146, in _get_module_details return _get_module_details(pkg_main_name, error) File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\runpy.py", line 110, in _get_module_details **import**(pkg_name) File "D:\code\llama2\llama_inference\venv\lib\site-packages\bitsandbytes__init__.py", line 6, in from . import cuda_setup, utils, research File "D:\code\llama2\llama_inference\venv\lib\site-packages\bitsandbytes\research__init__.py", line 1, in from . import nn File "D:\code\llama2\llama_inference\venv\lib\site-packages\bitsandbytes\research\nn__init_.py", line 1, in from .modules import LinearFP8Mixed, LinearFP8Global File "D:\code\llama2\llama_inference\venv\lib\site-packages\bitsandbytes\research\nn\modules.py", line 8, in from bitsandbytes.optim import GlobalOptimManager File "D:\code\llama2\llama_inference\venv\lib\site-packages\bitsandbytes\optim__init_.py", line 6, in from bitsandbytes.cextension import COMPILED_WITH_CUDA File "D:\code\llama2\llama_inference\venv\lib\site-packages\bitsandbytes\cextension.py", line 20, in raise RuntimeError(''' RuntimeError: CUDA Setup failed despite GPU being available. Please run the following command to get more information:__
> > ```
> >     python -m bitsandbytes
> > 
> >     Inspect the output of the command and see if you can locate CUDA libraries. You might need to add them
> >     to your LD_LIBRARY_PATH. If you suspect a bug, please take the information from python -m bitsandbytes
> >     and open an issue at: https://github.com/TimDettmers/bitsandbytes/issues
> > ```
> 
> My setup LD_LIBRARY_PATH = C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v12.1\lib\x64

did you sovle this problem by this way?

**Comment by rfroli** [comment]
Guys, we all are wasting time here, since it is explicitly notified that "The bitsandbytes library is currently only supported on Linux distributions. Windows is not supported at the moment." (https://github.com/TimDettmers/bitsandbytes)
There would be another repository dedicated to Windows there: https://github.com/Keith-Hon/bitsandbytes-windows
I'm currently trying to get it to work...

**Comment by tiamojames** [comment]
> Guys, we all are wasting time here, since it is explicitly notified that "The bitsandbytes library is currently only supported on Linux distributions. Windows is not supported at the moment." (https://github.com/TimDettmers/bitsandbytes) There would be another repository dedicated to Windows there: https://github.com/Keith-Hon/bitsandbytes-windows I'm currently trying to get it to work...

wdf... thanks bro, i'll try it after class

**Comment by tiamojames** [comment]
> Guys, we all are wasting time here, since it is explicitly notified that "The bitsandbytes library is currently only supported on Linux distributions. Windows is not supported at the moment." (https://github.com/TimDettmers/bitsandbytes) There would be another repository dedicated to Windows there: https://github.com/Keith-Hon/bitsandbytes-windows I'm currently trying to get it to work...

wtf... thanks bro, i'll try it after class

**Comment by rfroli** [comment]
Seemed to work but I am stuck, since I am using 4 bits quantization and it is not yet in this release ( "4 bit quantization requires bitsandbytes>=0.39.0 - please upgrade your bitsandbytes version").

**Comment by fillsok** [comment]
You guy just try:
pip install bitsandbytes-windows

Latest version is 0.37.5，my cuda sdk version is 12.2, after installed, even though it use cuda116 but for me it works!!!

================================================================================
binary_path: D:\code\llama2\llama_inference\venv\lib\site-packages\bitsandbytes\cuda_setup\libbitsandbytes_cuda116.dll
CUDA SETUP: Loading binary D:\code\llama2\llama_inference\venv\lib\site-packages\bitsandbytes\cuda_setup\libbitsandbytes_cuda116.dll...

**Comment by rfroli** [comment]
Yes, bitsandbytes-windows installation worked good, but my specific project is using 4 bits quantization, which seems to have been integrated in later release  0.39...

**Comment by tiamojames** [comment]
> You guy just try: pip install bitsandbytes-windows
> 
> Latest version is 0.37.5，my cuda sdk version is 12.2, after installed, even though it use cuda116 but for me it works!!!
> 
> ================================================================================ binary_path: D:\code\llama2\llama_inference\venv\lib\site-packages\bitsandbytes\cuda_setup\libbitsandbytes_cuda116.dll CUDA SETUP: Loading binary D:\code\llama2\llama_inference\venv\lib\site-packages\bitsandbytes\cuda_setup\libbitsandbytes_cuda116.dll...
> 
> ![image](https://user-images.githubusercontent.com/141209165/266279684-402ba3b2-f896-4bd2-b515-fe82df7214ad.png) ![image](https://user-images.githubusercontent.com/141209165/266279585-e9f7fc89-4550-4605-bd94-b5fee06113de.png)

love ya bro！, that worked， i install  bitsandbytes-windows-0.37.5

**Comment by liaosu0755** [comment]
> 

Thank you very much,problem solved!

**Comment by tiamojames** [comment]
> > 
> 
> Thank you very much,problem solved!

you're welcome,guys

**Comment by CYXDBY** [comment]
> Yes, bitsandbytes-windows installation worked good, but my specific project is using 4 bits quantization, which seems to have been integrated in later release 0.39...

try it bro:https://github.com/jllllll/bitsandbytes-windows-webui/releases/download/wheels/bitsandbytes-0.41.1-py3-none-win_amd64.whl

**Comment by tiamojames** [comment]
> Yes, bitsandbytes-windows installation worked good, but my specific project is using 4 bits quantization, which seems to have been integrated in later release  0.39...
> 
> 

sry you can try to update,maybe that will work

**Comment by gotsathacker1** [comment]
Just in case you're either using wsl and or it isn't working with the just regular pip install bitsandbytes I was having the issue with it not finding libcudart.so even after adding to $LD_LIBRARY_PATH so in bitsandbytes/cuda_setup/main.py I changed it to

     CUDA_RUNTIME_LIBS: list = ['libcudart.so', 'libcudart.so.12', 'libcudart.so.12.2.140'] 

and then input this command as it suggested, into the command line: export BNB_CUDA_VERSION=122
It worked for me after that.

**Comment by lumiamilk** [comment]
> > Yes, bitsandbytes-windows installation worked good, but my specific project is using 4 bits quantization, which seems to have been integrated in later release 0.39...
> 
> try it bro:https://github.com/jllllll/bitsandbytes-windows-webui/releases/download/wheels/bitsandbytes-0.41.1-py3-none-win_amd64.whl

It works! I will call you bitsandbytes-superman from now😚

**Comment by ZixuanLiu4869** [comment]
> Just in case you're either using wsl and or it isn't working with the just regular pip install bitsandbytes I was having the issue with it not finding libcudart.so even after adding to $LD_LIBRARY_PATH so in bitsandbytes/cuda_setup/main.py I changed it to
> 
> ```
>  CUDA_RUNTIME_LIBS: list = ['libcudart.so', 'libcudart.so.12', 'libcudart.so.12.2.140'] 
> ```
> 
> and then input this command as it suggested, into the command line: export BNB_CUDA_VERSION=122 It worked for me after that.

This helps!

**Comment by swumagic** [comment]
Bitsandbytes was not supported windows before, but my method can support windows.（yuhuang）
1  open folder J:\StableDiffusion\sdwebui，Click the address bar of the folder and enter CMD
or WIN+R, CMD  。enter，cd /d J:\StableDiffusion\sdwebui
2  J:\StableDiffusion\sdwebui\py310\python.exe -m pip uninstall bitsandbytes

3 J:\StableDiffusion\sdwebui\py310\python.exe -m pip uninstall bitsandbytes-windows

4 J:\StableDiffusion\sdwebui\py310\python.exe -m pip install https://github.com/jllllll/bitsandbytes-windows-webui/releases/download/wheels/bitsandbytes-0.41.1-py3-none-win_amd64.whl

Replace your SD venv directory file（python.exe Folder） here（J:\StableDiffusion\sdwebui\py310）

**Comment by XixuHu** [comment]
> Guys, we all are wasting time here, since it is explicitly notified that "The bitsandbytes library is currently only supported on Linux distributions. Windows is not supported at the moment." (https://github.com/TimDettmers/bitsandbytes) There would be another repository dedicated to Windows there: https://github.com/Keith-Hon/bitsandbytes-windows I've tried to get it to work in my project, but was stuck since I am using 4 bits quantization and it is not yet in this release ( "4 bit quantization requires bitsandbytes>=0.39.0 - please upgrade your bitsandbytes version").

I am using WSL, I wonder whether I should use the bitsandbyes or bitsandbytes-windows.. Any suggestion and advice?

**Comment by tiamojames** [comment]
> > Guys, we all are wasting time here, since it is explicitly notified that "The bitsandbytes library is currently only supported on Linux distributions. Windows is not supported at the moment." (https://github.com/TimDettmers/bitsandbytes) There would be another repository dedicated to Windows there: https://github.com/Keith-Hon/bitsandbytes-windows I've tried to get it to work in my project, but was stuck since I am using 4 bits quantization and it is not yet in this release ( "4 bit quantization requires bitsandbytes>=0.39.0 - please upgrade your bitsandbytes version").
> 
> I am using WSL, I wonder whether I should use the bitsandbyes or bitsandbytes-windows.. Any suggestion and advice?

Try both

**Comment by LeoAkun** [comment]
We need "pip installl bitsandbytes-windows", and it will work in Windows.
