### ISSUE TITLE
RuntimeError:  CUDA Setup failed despite GPU being available.

### ISSUE THREAD

**Issue by wasifferoze** [TimDettmers/bitsandbytes#778]
I face this error despite following the instruction for reproducing result
`===================================BUG REPORT===================================
/opt/conda/envs/ptl-py310/lib/python3.10/site-packages/bitsandbytes/cuda_setup/main.py:166: UserWarning: Welcome to bitsandbytes. For bug reports, please run

python -m bitsandbytes

  warn(msg)
================================================================================
/opt/conda/envs/ptl-py310/lib/python3.10/site-packages/bitsandbytes/cuda_setup/main.py:166: UserWarning: /opt/conda/envs/ptl-py310 did not contain ['libcudart.so', 'libcudart.so.11.0', 'libcudart.so.12.0'] as expected! Searching further paths...
  warn(msg)
/opt/conda/envs/ptl-py310/lib/python3.10/site-packages/bitsandbytes/cuda_setup/main.py:166: UserWarning: /opt/conda/envs/ptl-py310/lib did not contain ['libcudart.so', 'libcudart.so.11.0', 'libcudart.so.12.0'] as expected! Searching further paths...
  warn(msg)
CUDA_SETUP: WARNING! libcudart.so not found in any environmental path. Searching in backup paths...
The following directories listed in your path were found to be non-existent: {PosixPath('/usr/local/cuda/lib64')}
DEBUG: Possible options found for libcudart.so: set()
CUDA SETUP: PyTorch settings found: CUDA_VERSION=117, Highest Compute Capability: 7.5.
CUDA SETUP: To manually override the PyTorch CUDA version please see:https://github.com/TimDettmers/bitsandbytes/blob/main/how_to_use_nonpytorch_cuda.md
CUDA SETUP: Required library version not found: libbitsandbytes_cuda117.so. Maybe you need to compile it from source?
CUDA SETUP: Defaulting to libbitsandbytes_cpu.so...

================================================ERROR=====================================
CUDA SETUP: CUDA detection failed! Possible reasons:
1. You need to manually override the PyTorch CUDA version. Please see: "https://github.com/TimDettmers/bitsandbytes/blob/main/how_to_use_nonpytorch_cuda.md
2. CUDA driver not installed
3. CUDA not installed
4. You have multiple conflicting CUDA libraries
5. Required library not pre-compiled for this bitsandbytes release!
CUDA SETUP: If you compiled from source, try again with `make CUDA_VERSION=DETECTED_CUDA_VERSION` for example, `make CUDA_VERSION=113`.
CUDA SETUP: The CUDA version for the compile might depend on your conda install. Inspect CUDA version via `conda list | grep cuda`.
================================================================================

CUDA SETUP: Problem: The main issue seems to be that the main CUDA runtime library was not detected.
CUDA SETUP: Solution 1: To solve the issue the libcudart.so location needs to be added to the LD_LIBRARY_PATH variable
CUDA SETUP: Solution 1a): Find the cuda runtime library via: find / -name libcudart.so 2>/dev/null
CUDA SETUP: Solution 1b): Once the library is found add it to the LD_LIBRARY_PATH: export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:FOUND_PATH_FROM_1a
CUDA SETUP: Solution 1c): For a permanent solution add the export from 1b into your .bashrc file, located at ~/.bashrc
CUDA SETUP: Solution 2: If no library was found in step 1a) you need to install CUDA.
CUDA SETUP: Solution 2a): Download CUDA install script: wget https://github.com/TimDettmers/bitsandbytes/blob/main/cuda_install.sh
CUDA SETUP: Solution 2b): Install desired CUDA version to desired location. The syntax is bash cuda_install.sh CUDA_VERSION PATH_TO_INSTALL_INTO.
CUDA SETUP: Solution 2b): For example, "bash cuda_install.sh 113 ~/local/" will download CUDA 11.3 and install into the folder ~/local
CUDA SETUP: Setup Failed!
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/conda/envs/ptl-py310/lib/python3.10/site-packages/bitsandbytes/__init__.py", line 6, in <module>
    from . import cuda_setup, utils, research
  File "/opt/conda/envs/ptl-py310/lib/python3.10/site-packages/bitsandbytes/research/__init__.py", line 1, in <module>
    from . import nn
  File "/opt/conda/envs/ptl-py310/lib/python3.10/site-packages/bitsandbytes/research/nn/__init__.py", line 1, in <module>
    from .modules import LinearFP8Mixed, LinearFP8Global
  File "/opt/conda/envs/ptl-py310/lib/python3.10/site-packages/bitsandbytes/research/nn/modules.py", line 8, in <module>
    from bitsandbytes.optim import GlobalOptimManager
  File "/opt/conda/envs/ptl-py310/lib/python3.10/site-packages/bitsandbytes/optim/__init__.py", line 6, in <module>
    from bitsandbytes.cextension import COMPILED_WITH_CUDA
  File "/opt/conda/envs/ptl-py310/lib/python3.10/site-packages/bitsandbytes/cextension.py", line 20, in <module>
    raise RuntimeError('''
RuntimeError: 
        CUDA Setup failed despite GPU being available. Please run the following command to get more information:

        python -m bitsandbytes

        Inspect the output of the command and see if you can locate CUDA libraries. You might need to add them
        to your LD_LIBRARY_PATH. If you suspect a bug, please take the information from python -m bitsandbytes
        and open an issue at: https://github.com/TimDettmers/bitsandbytes/issues`

It say libcudart.so is not present in LD_LIBRARY_PATH, which is not true you can see `(ptl-py310) root@a8:/# find -name libcudart.so
./opt/conda/envs/ptl-py310/lib/libcudart.so`
and this is my LD_LIBRARY_PATH 
`ptl-py310) root@a8:/# echo $LD_LIBRARY_PATH
/opt/conda/envs/ptl-py310/lib`

What should I do please help

**Comment by yasinda-s** [comment]
try installing bitsandbytes this way - `pip install git+https://github.com/Keith-Hon/bitsandbytes-windows.git`

**Comment by wasifferoze** [comment]
I use linux system and was using for docker, I uninstalled bitsandbytes and reinstalled it using pip on conda envirment which solve my problem, latest version find cuda path automatically

**Comment by duany049** [comment]
> try installing bitsandbytes this way - `pip install git+https://github.com/Keith-Hon/bitsandbytes-windows.git`

thx，it works for me！

**Comment by duany049** [comment]
> > try installing bitsandbytes this way - `pip install git+https://github.com/Keith-Hon/bitsandbytes-windows.git`
> 
> thx，it works for me！

I use linux system, I solved the problem by reinstalling it using conda enviroment！

**Comment by recman55** [comment]
doesn't works my env ... (torch201+cu118)
Why Tim fix this problem long time...

**Comment by Samge0** [comment]
> try installing bitsandbytes this way - `pip install git+https://github.com/Keith-Hon/bitsandbytes-windows.git`

thx，it works for me！

**Comment by swumagic** [comment]
Bitsandbytes was not supported windows before, but my method can support windows.（yuhuang）
1  open folder J:\StableDiffusion\sdwebui，Click the address bar of the folder and enter CMD
or WIN+R, CMD  。enter，cd /d J:\StableDiffusion\sdwebui
2  J:\StableDiffusion\sdwebui\py310\python.exe -m pip uninstall bitsandbytes

3 J:\StableDiffusion\sdwebui\py310\python.exe -m pip uninstall bitsandbytes-windows

4 J:\StableDiffusion\sdwebui\py310\python.exe -m pip install https://github.com/jllllll/bitsandbytes-windows-webui/releases/download/wheels/bitsandbytes-0.41.1-py3-none-win_amd64.whl

Replace your SD venv directory file（python.exe Folder） here（J:\StableDiffusion\sdwebui\py310）

**Comment by Xnhyacinth** [comment]
> I use linux system and was using for docker, I uninstalled bitsandbytes and reinstalled it using pip on conda envirment which solve my problem, latest version (0.41.1) find cuda path automatically

hi, there is error when in docker, and did you just reinstall? but I can't solve it.

**Comment by Xnhyacinth** [comment]
> > > try installing bitsandbytes this way - `pip install git+https://github.com/Keith-Hon/bitsandbytes-windows.git`
> > 
> > 
> > thx，it works for me！
> 
> I use linux system, I solved the problem by reinstalling it using conda enviroment！

hi, did you install conda? and used conda install?
