### ISSUE TITLE
CUDA SETUP: CUDA detection failed! Possible reasons:

### ISSUE THREAD

**Issue by TomasAndersonFang** [TimDettmers/bitsandbytes#818]
If I directly use torch, everything is ok. Here is the output of `python -m bitsandbytes`:

```
/home/x_senfa/.conda/envs/apr/lib/python3.10/site-packages/bitsandbytes/cuda_setup/main.py:106: UserWarning:

================================================================================
WARNING: Manual override via BNB_CUDA_VERSION env variable detected!
BNB_CUDA_VERSION=XXX can be used to load a bitsandbytes version that is different from the PyTorch CUDA version.
If this was unintended set the BNB_CUDA_VERSION variable to an empty string: export BNB_CUDA_VERSION=
If you use the manual override make sure the right libcudart.so is in your LD_LIBRARY_PATH
For example by adding the following to your .bashrc: export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:<path_to_cuda_dir/lib64
Loading CUDA version: BNB_CUDA_VERSION=118
================================================================================


  warn((f'\n\n{"="*80}\n'
False

===================================BUG REPORT===================================
/home/x_senfa/.conda/envs/apr/lib/python3.10/site-packages/bitsandbytes/cuda_setup/main.py:166: UserWarning: Welcome to bitsandbytes. For bug reports, please run

python -m bitsandbytes


  warn(msg)
================================================================================
/home/x_senfa/.conda/envs/apr/lib/python3.10/site-packages/bitsandbytes/cuda_setup/main.py:166: UserWarning: Found duplicate ['libcudart.so', 'libcudart.so.11.0', 'libcudart.so.12.0'] files: {PosixPath('/home/x_senfa/.conda/envs/apr/lib/libcudart.so.11.0'), PosixPath('/home/x_senfa/.conda/envs/apr/lib/libcudart.so')}.. We select the PyTorch default libcudart.so, which is {torch.version.cuda},but this might missmatch with the CUDA version that is needed for bitsandbytes.To override this behavior set the BNB_CUDA_VERSION=<version string, e.g. 122> environmental variableFor example, if you want to use the CUDA version 122BNB_CUDA_VERSION=122 python ...OR set the environmental variable in your .bashrc: export BNB_CUDA_VERSION=122In the case of a manual override, make sure you set the LD_LIBRARY_PATH, e.g.export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/local/cuda-11.2
  warn(msg)
/home/x_senfa/.conda/envs/apr/lib/python3.10/site-packages/bitsandbytes/cuda_setup/main.py:166: UserWarning: /home/x_senfa/.conda/envs/apr did not contain ['libcudart.so', 'libcudart.so.11.0', 'libcudart.so.12.0'] as expected! Searching further paths...
  warn(msg)
/home/x_senfa/.conda/envs/apr/lib/python3.10/site-packages/bitsandbytes/cuda_setup/main.py:166: UserWarning: Found duplicate ['libcudart.so', 'libcudart.so.11.0', 'libcudart.so.12.0'] files: {PosixPath('/home/x_senfa/.conda/envs/apr/lib/libcudart.so.11.0'), PosixPath('/home/x_senfa/.conda/envs/apr/lib/libcudart.so'), PosixPath('/proj/berzelius-2023-175/users/x_senfa/local/cuda-11.8/lib64/libcudart.so.11.0'), PosixPath('/proj/berzelius-2023-175/users/x_senfa/local/cuda-11.8/lib64/libcudart.so')}.. We select the PyTorch default libcudart.so, which is {torch.version.cuda},but this might missmatch with the CUDA version that is needed for bitsandbytes.To override this behavior set the BNB_CUDA_VERSION=<version string, e.g. 122> environmental variableFor example, if you want to use the CUDA version 122BNB_CUDA_VERSION=122 python ...OR set the environmental variable in your .bashrc: export BNB_CUDA_VERSION=122In the case of a manual override, make sure you set the LD_LIBRARY_PATH, e.g.export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/local/cuda-11.2
  warn(msg)
/home/x_senfa/.conda/envs/apr/lib/python3.10/site-packages/bitsandbytes/cuda_setup/main.py:166: UserWarning: /cm/shared/apps/slurm/current/lib64/slurm:/cm/shared/apps/slurm/current/lib64:/home/x_senfa/.conda/envs/apr/lib:/proj/berzelius-2023-175/users/x_senfa/local/cuda-11.8/lib64 did not contain ['libcudart.so', 'libcudart.so.11.0', 'libcudart.so.12.0'] as expected! Searching further paths...
  warn(msg)
The following directories listed in your path were found to be non-existent: {PosixPath('1;/home/x_senfa/bin'), PosixPath('1;/usr/sbin'), PosixPath('1;/cm/shared/apps/slurm/current/sbin'), PosixPath('1;/usr/local/sbin'), PosixPath('1;/cm/shared/apps/slurm/current/bin'), PosixPath('1;/usr/local/bin'), PosixPath('1;/home/x_senfa/.local/bin'), PosixPath('1;/software/tools/bin'), PosixPath('1;/usr/bin'), PosixPath('1;/software/sse/manual/mpprun/4.1.5/bin'), PosixPath('1'), PosixPath('1;/software/sse/manual/Mambaforge/23.3.1-1/nsc_wrapscripts'), PosixPath('1;/opt/puppetlabs/bin')}
The following directories listed in your path were found to be non-existent: {PosixPath('1;/software/sse/modules/nsc/.1.1.lua'), PosixPath('1'), PosixPath('1;/software/sse/modules/Mambaforge/23.3.1-1.lua')}
The following directories listed in your path were found to be non-existent: {PosixPath('1'), PosixPath('1;/cm/shared/apps/slurm/current/lib64')}
The following directories listed in your path were found to be non-existent: {PosixPath('-200;/software/sse/manual/mpprun/4.1.5/nsc-wrappers'), PosixPath('-2000')}
The following directories listed in your path were found to be non-existent: {PosixPath('1;Mambaforge/23.3.1-1'), PosixPath('1'), PosixPath('mpprun/4.1.5'), PosixPath('1;nsc/.1.1')}
The following directories listed in your path were found to be non-existent: {PosixPath('/scratch/local')}
The following directories listed in your path were found to be non-existent: {PosixPath('1'), PosixPath('1;/cm/shared/apps/slurm/current/lib64')}
The following directories listed in your path were found to be non-existent: {PosixPath('nsc/.1.1'), PosixPath('mpprun/4.1.5'), PosixPath('Mambaforge/23.3.1-1')}
The following directories listed in your path were found to be non-existent: {PosixPath('2;/software/sse/manual/lmod/lmod/share/man'), PosixPath('1;/usr/share/man'), PosixPath('1;/cm/local/apps/environment-modules/current/share/man'), PosixPath('1;/usr/local/share/man'), PosixPath('1')}
The following directories listed in your path were found to be non-existent: {PosixPath('1')}
The following directories listed in your path were found to be non-existent: {PosixPath('() {  ( alias;\n eval ${which_declare} ) | /usr/bin/which --tty-only --read-alias --read-functions --show-tilde --show-dot $@\n}')}
The following directories listed in your path were found to be non-existent: {PosixPath('() {  eval $($LMOD_DIR/ml_cmd "$@")\n}')}
CUDA_SETUP: WARNING! libcudart.so not found in any environmental path. Searching in backup paths...
The following directories listed in your path were found to be non-existent: {PosixPath('/usr/local/cuda/lib64')}
DEBUG: Possible options found for libcudart.so: set()
CUDA SETUP: PyTorch settings found: CUDA_VERSION=118, Highest Compute Capability: 7.5.
CUDA SETUP: To manually override the PyTorch CUDA version please see:https://github.com/TimDettmers/bitsandbytes/blob/main/how_to_use_nonpytorch_cuda.md
CUDA SETUP: Required library version not found: libbitsandbytes_cuda118.so. Maybe you need to compile it from source?
CUDA SETUP: Defaulting to libbitsandbytes_cpu.so...

================================================ERROR=====================================
CUDA SETUP: CUDA detection failed! Possible reasons:
1. You need to manually override the PyTorch CUDA version. Please see: "https://github.com/TimDettmers/bitsandbytes/blob/main/how_to_use_nonpytorch_cuda.md
2. CUDA driver not installed
3. CUDA not installed
4. You have multiple conflicting CUDA libraries
5. Required library not pre-compiled for this bitsandbytes release!
CUDA SETUP: If you compiled from source, try again with `make CUDA_VERSION=DETECTED_CUDA_VERSION` for example, `make CUDA_VERSION=113`.
CUDA SETUP: The CUDA version for the compile might depend on your conda install. Inspect CUDA version via `conda list | grep cuda`.
================================================================================

CUDA SETUP: Problem: The main issue seems to be that the main CUDA runtime library was not detected.
CUDA SETUP: Solution 1: To solve the issue the libcudart.so location needs to be added to the LD_LIBRARY_PATH variable
CUDA SETUP: Solution 1a): Find the cuda runtime library via: find / -name libcudart.so 2>/dev/null
CUDA SETUP: Solution 1b): Once the library is found add it to the LD_LIBRARY_PATH: export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:FOUND_PATH_FROM_1a
CUDA SETUP: Solution 1c): For a permanent solution add the export from 1b into your .bashrc file, located at ~/.bashrc
CUDA SETUP: Solution 2: If no library was found in step 1a) you need to install CUDA.
CUDA SETUP: Solution 2a): Download CUDA install script: wget https://github.com/TimDettmers/bitsandbytes/blob/main/cuda_install.sh
CUDA SETUP: Solution 2b): Install desired CUDA version to desired location. The syntax is bash cuda_install.sh CUDA_VERSION PATH_TO_INSTALL_INTO.
CUDA SETUP: Solution 2b): For example, "bash cuda_install.sh 113 ~/local/" will download CUDA 11.3 and install into the folder ~/local
CUDA SETUP: Setup Failed!
Traceback (most recent call last):
  File "/home/x_senfa/.conda/envs/apr/lib/python3.10/runpy.py", line 187, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/home/x_senfa/.conda/envs/apr/lib/python3.10/runpy.py", line 146, in _get_module_details
    return _get_module_details(pkg_main_name, error)
  File "/home/x_senfa/.conda/envs/apr/lib/python3.10/runpy.py", line 110, in _get_module_details
    __import__(pkg_name)
  File "/home/x_senfa/.conda/envs/apr/lib/python3.10/site-packages/bitsandbytes/__init__.py", line 6, in <module>
    from . import cuda_setup, utils, research
  File "/home/x_senfa/.conda/envs/apr/lib/python3.10/site-packages/bitsandbytes/research/__init__.py", line 1, in <module>
    from . import nn
  File "/home/x_senfa/.conda/envs/apr/lib/python3.10/site-packages/bitsandbytes/research/nn/__init__.py", line 1, in <module>
    from .modules import LinearFP8Mixed, LinearFP8Global
  File "/home/x_senfa/.conda/envs/apr/lib/python3.10/site-packages/bitsandbytes/research/nn/modules.py", line 8, in <module>
    from bitsandbytes.optim import GlobalOptimManager
  File "/home/x_senfa/.conda/envs/apr/lib/python3.10/site-packages/bitsandbytes/optim/__init__.py", line 6, in <module>
    from bitsandbytes.cextension import COMPILED_WITH_CUDA
  File "/home/x_senfa/.conda/envs/apr/lib/python3.10/site-packages/bitsandbytes/cextension.py", line 20, in <module>
    raise RuntimeError('''
RuntimeError:
        CUDA Setup failed despite GPU being available. Please run the following command to get more information:

        python -m bitsandbytes

        Inspect the output of the command and see if you can locate CUDA libraries. You might need to add them
        to your LD_LIBRARY_PATH. If you suspect a bug, please take the information from python -m bitsandbytes
        and open an issue at: https://github.com/TimDettmers/bitsandbytes/issues
```

**Comment by TomasAndersonFang** [comment]
I tried to solve this problem, but finally I always met the problem described in https://github.com/TimDettmers/bitsandbytes/pull/812, and this solved my final problem.

**Comment by swumagic** [comment]
Bitsandbytes was not supported windows before, but my method can support windows.（yuhuang）
1  open folder J:\StableDiffusion\sdwebui，Click the address bar of the folder and enter CMD
or WIN+R, CMD  。enter，cd /d J:\StableDiffusion\sdwebui
2  J:\StableDiffusion\sdwebui\py310\python.exe -m pip uninstall bitsandbytes

3 J:\StableDiffusion\sdwebui\py310\python.exe -m pip uninstall bitsandbytes-windows

4 J:\StableDiffusion\sdwebui\py310\python.exe -m pip install https://github.com/jllllll/bitsandbytes-windows-webui/releases/download/wheels/bitsandbytes-0.41.1-py3-none-win_amd64.whl

Replace your SD venv directory file（python.exe Folder） here（J:\StableDiffusion\sdwebui\py310）
