### ISSUE TITLE
CUDA SETUP: Something unexpected happened. Please compile from source:

### ISSUE THREAD

**Issue by jpiabrantes** [TimDettmers/bitsandbytes#84]
Getting the following error:
```sh
CUDA_SETUP: WARNING! libcudart.so not found in any environmental path. Searching /usr/local/cuda/lib64...
CUDA SETUP: CUDA runtime path found: /usr/local/cuda/lib64/libcudart.so
CUDA SETUP: Highest compute capability among GPUs detected: 7.5
CUDA SETUP: Detected CUDA version 116
CUDA SETUP: Loading binary /opt/conda/envs/dreambooth/lib/python3.7/site-packages/bitsandbytes-0.35.4-py3.7.egg/bitsandbytes/libbitsandbytes_cuda116.so...
CUDA_SETUP: WARNING! libcudart.so not found in any environmental path. Searching /usr/local/cuda/lib64...
CUDA SETUP: CUDA runtime path found: /usr/local/cuda/lib64/libcudart.so
CUDA SETUP: Highest compute capability among GPUs detected: 7.5
CUDA SETUP: Detected CUDA version 116
CUDA SETUP: Loading binary /opt/conda/envs/dreambooth/lib/python3.7/site-packages/bitsandbytes-0.35.4-py3.7.egg/bitsandbytes/libbitsandbytes_cuda116.so...
CUDA SETUP: Something unexpected happened. Please compile from source:
git clone git@github.com:TimDettmers/bitsandbytes.git
cd bitsandbytes
CUDA_VERSION=116 make cuda11x
python setup.py install
Traceback (most recent call last):
  File "train_dreambooth.py", line 811, in <module>
    main(args)
  File "train_dreambooth.py", line 528, in main
    import bitsandbytes as bnb
  File "/opt/conda/envs/dreambooth/lib/python3.7/site-packages/bitsandbytes-0.35.4-py3.7.egg/bitsandbytes/__init__.py", line 6, in <module>
    from .autograd._functions import (
  File "/opt/conda/envs/dreambooth/lib/python3.7/site-packages/bitsandbytes-0.35.4-py3.7.egg/bitsandbytes/autograd/_functions.py", line 5, in <module>
    import bitsandbytes.functional as F
  File "/opt/conda/envs/dreambooth/lib/python3.7/site-packages/bitsandbytes-0.35.4-py3.7.egg/bitsandbytes/functional.py", line 13, in <module>
    from .cextension import COMPILED_WITH_CUDA, lib
  File "/opt/conda/envs/dreambooth/lib/python3.7/site-packages/bitsandbytes-0.35.4-py3.7.egg/bitsandbytes/cextension.py", line 121, in <module>
    https://github.com/TimDettmers/bitsandbytes/issues''')
RuntimeError: 
        CUDA Setup failed despite GPU being available. Inspect the CUDA SETUP outputs aboveto fix your environment!
        If you cannot find any issues and suspect a bug, please open an issue with detals about your environment:
        https://github.com/TimDettmers/bitsandbytes/issues
```

I already installed from source by running:
```sh 
git clone git@github.com:TimDettmers/bitsandbytes.git
cd bitsandbytes
CUDA_VERSION=116 make cuda11x
python setup.py install
```

But I keep getting the same error (and suggestion).

I am wondering if my installation from source went ok, because I do get a SyntaxError when installing from source:
```sh
byte-compiling build/bdist.linux-x86_64/egg/bitsandbytes/__main__.py to __main__.cpython-37.pyc
  File "<fstring>", line 1
    (COMPILED_WITH_CUDA = )
                        ^
SyntaxError: invalid syntax

byte-compiling build/bdist.linux-x86_64/egg/bitsandbytes/optim/optimizer.py to optimizer.cpython-37.pyc
byte-compiling build/bdist.linux-x86_64/egg/bitsandbytes/optim/lamb.py to lamb.cpython-37.pyc
byte-compiling build/bdist.linux-x86_64/egg/bitsandbytes/optim/adamw.py to adamw.cpython-37.pyc
byte-compiling build/bdist.linux-x86_64/egg/bitsandbytes/optim/adagrad.py to adagrad.cpython-37.pyc
byte-compiling build/bdist.linux-x86_64/egg/bitsandbytes/optim/__init__.py to __init__.cpython-37.pyc
byte-compiling build/bdist.linux-x86_64/egg/bitsandbytes/optim/lars.py to lars.cpython-37.pyc
byte-compiling build/bdist.linux-x86_64/egg/bitsandbytes/optim/sgd.py to sgd.cpython-37.pyc
byte-compiling build/bdist.linux-x86_64/egg/bitsandbytes/optim/adam.py to adam.cpython-37.pyc
byte-compiling build/bdist.linux-x86_64/egg/bitsandbytes/optim/rmsprop.py to rmsprop.cpython-37.pyc
byte-compiling build/bdist.linux-x86_64/egg/bitsandbytes/__init__.py to __init__.cpython-37.pyc
byte-compiling build/bdist.linux-x86_64/egg/bitsandbytes/utils.py to utils.cpython-37.pyc
byte-compiling build/bdist.linux-x86_64/egg/bitsandbytes/nn/__init__.py to __init__.cpython-37.pyc
byte-compiling build/bdist.linux-x86_64/egg/bitsandbytes/nn/modules.py to modules.cpython-37.pyc
byte-compiling build/bdist.linux-x86_64/egg/bitsandbytes/autograd/_functions.py to _functions.cpython-37.pyc
byte-compiling build/bdist.linux-x86_64/egg/bitsandbytes/autograd/__init__.py to __init__.cpython-37.pyc
creating build/bdist.linux-x86_64/egg/EGG-INFO
copying bitsandbytes.egg-info/PKG-INFO -> build/bdist.linux-x86_64/egg/EGG-INFO
copying bitsandbytes.egg-info/SOURCES.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying bitsandbytes.egg-info/dependency_links.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying bitsandbytes.egg-info/entry_points.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying bitsandbytes.egg-info/top_level.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
writing build/bdist.linux-x86_64/egg/EGG-INFO/native_libs.txt
zip_safe flag not set; analyzing archive contents...
bitsandbytes.__pycache__.cextension.cpython-37: module references __file__
creating 'dist/bitsandbytes-0.35.4-py3.7.egg' and adding 'build/bdist.linux-x86_64/egg' to it
removing 'build/bdist.linux-x86_64/egg' (and everything under it)
Processing bitsandbytes-0.35.4-py3.7.egg
removing '/opt/conda/envs/dreambooth/lib/python3.7/site-packages/bitsandbytes-0.35.4-py3.7.egg' (and everything under it)
creating /opt/conda/envs/dreambooth/lib/python3.7/site-packages/bitsandbytes-0.35.4-py3.7.egg
Extracting bitsandbytes-0.35.4-py3.7.egg to /opt/conda/envs/dreambooth/lib/python3.7/site-packages
  File "<fstring>", line 1
    (COMPILED_WITH_CUDA = )
                        ^
SyntaxError: invalid syntax

bitsandbytes 0.35.4 is already the active version in easy-install.pth
Installing debug_cuda script to /opt/conda/envs/dreambooth/bin

Installed /opt/conda/envs/dreambooth/lib/python3.7/site-packages/bitsandbytes-0.35.4-py3.7.egg
Processing dependencies for bitsandbytes==0.35.4
Finished processing dependencies for bitsandbytes==0.35.4
```

**Comment by arpowers** [comment]
got the same error as well

**Comment by tomaarsen** [comment]
When compiling from source, you're encountering an error on:
https://github.com/TimDettmers/bitsandbytes/blob/08fa2e7b01dda8959a930295de9829516f8c77bc/bitsandbytes/__main__.py#L48

The reason for your `SyntaxError` is that this use of `=` in f-strings were only [introduced in Python 3.8](https://docs.python.org/3/whatsnew/3.8.html#f-strings-support-for-self-documenting-expressions-and-debugging).
But you are using Python 3.7, as indicated by your path (`/opt/conda/envs/dreambooth/lib/python3.7`).

Upgrading to Python 3.8 would fix this issue, but I believe that `bitsandbytes` ought to support Python 3.7 as well for the time being. That said, the Python 3.7 end of life is in only [7 months](https://endoflife.date/python), so I understand that it doesn't have the highest priority to push for Python 3.7 support again.

`bitsandbytes` never mentions a supported Python version, but I believe that Hugging Face's `transformers` is still on Python 3.6+, and it relies on `bitsandbytes` for some functionality. So, I believe the line should be changed to work for Python 3.7, but I'm unsure if there are more cases of syntax that would prevent it from working for Python 3.7.

Perhaps I can make a PR to add (reintroduce?) Python 3.7 support in the coming week or two, if @TimDettmers would like.

**Comment by arpowers** [comment]
@tomaarsen i think its only important to document this better. Compatibility issues are fine, but when errors messages and vague and docs are non-existent days can be wasted :)

**Comment by jpiabrantes** [comment]
Got the same error on Python 3.9 (not the syntax error from the f-string but the CUDA setup failed).

Fixed the error by adding
```sh
export LD_LIBRARY_PATH=/usr/local/cuda/lib64/:$LD_LIBRARY_PATH
```

To my .bashrc

**Comment by RiceCat7487** [comment]
Congratulations on finding a solution to your problem, I had the same problem as you.
But sorry I'm a computer noob, I'd appreciate it if you could explain a little more detail.Thank you! @jpiabrantes

**Comment by jpiabrantes** [comment]
@RiceCat7487 has you can see in the error above:

```sh
CUDA_SETUP: WARNING! libcudart.so not found in any environmental path. Searching /usr/local/cuda/lib64...
CUDA SETUP: CUDA runtime path found: /usr/local/cuda/lib64/libcudart.so
```

bitsandbytes try to look for my CUDA files in the wrong place and then finds them on /usr/local/cuda/lib64.

You can tell it from the start to look at the right place by opening a terminal and writing
```sh
export LD_LIBRARY_PATH=/usr/local/cuda/lib64/:$LD_LIBRARY_PATH
```

However, if you want to do this automatically every time a new terminal is open you write this line on a file called .bashrc that stays in your home folder (assuming you are using linux).

**Comment by RiceCat7487** [comment]
Thank you @jpiabrantes ,Thanks for your help, the problem was solved ：）

**Comment by TimDettmers** [comment]
@tomaarsen Thanks for being on this so quickly! Looking at the [PyPi statistics](https://pypistats.org/packages/bitsandbytes), it seems that about 4% of installs are Python 3.7. I think at this point it is better to prioritize other issues. I will update the README to reflect the Python >=3.8 requirement.

**Comment by tomaarsen** [comment]
Works for me!

**Comment by Shedarin** [comment]
> @RiceCat7487 has you can see in the error above:
> 
> ```shell
> CUDA_SETUP: WARNING! libcudart.so not found in any environmental path. Searching /usr/local/cuda/lib64...
> CUDA SETUP: CUDA runtime path found: /usr/local/cuda/lib64/libcudart.so
> ```
> 
> bitsandbytes try to look for my CUDA files in the wrong place and then finds them on /usr/local/cuda/lib64.
> 
> You can tell it from the start to look at the right place by opening a terminal and writing
> 
> ```shell
> export LD_LIBRARY_PATH=/usr/local/cuda/lib64/:$LD_LIBRARY_PATH
> ```
> 
> However, if you want to do this automatically every time a new terminal is open you write this line on a file called .bashrc that stays in your home folder (assuming you are using linux).

what if i use windows? it doesn't work

**Comment by tomaarsen** [comment]
Windows is not supported by `bitsandbytes` at the moment. See the [Requirements section](https://github.com/TimDettmers/bitsandbytes#requirements--installation) of the README:

> The bitsandbytes library is currently only supported on Linux distributions. Windows is not supported at the moment.

**Comment by swumagic** [comment]
Bitsandbytes was not supported windows before, but my method can support windows.（yuhuang）
1  open folder J:\StableDiffusion\sdwebui，Click the address bar of the folder and enter CMD
or WIN+R, CMD  。enter，cd /d J:\StableDiffusion\sdwebui
2  J:\StableDiffusion\sdwebui\py310\python.exe -m pip uninstall bitsandbytes

3 J:\StableDiffusion\sdwebui\py310\python.exe -m pip uninstall bitsandbytes-windows

4 J:\StableDiffusion\sdwebui\py310\python.exe -m pip install https://github.com/jllllll/bitsandbytes-windows-webui/releases/download/wheels/bitsandbytes-0.41.1-py3-none-win_amd64.whl

Replace your SD venv directory file（python.exe Folder） here（J:\StableDiffusion\sdwebui\py310）
