### ISSUE TITLE
Installation errors

### ISSUE THREAD

**Issue by qmeeus** [TimDettmers/bitsandbytes#849]
Hi,

I have been trying to figure out how to install bitsandbytes. Here is what I tried:

- `pip install bitsandbytes`: bitsandbytes was not compiled with CUDA support
- `pip install bitsandbytes-cudaXXX`: this version is deprecated, pls use pip install bitsandbytes
- install from source (following README): nvcc version 12 is invalid (I cannot install other versions of nvcc because I'm not root)
- `conda install bitsandbytes`  does not work either (tries to install `cudatoolkit`, which messes up the environment)

I'm running out of ideas.

Is there ANY way that is recommended and proved to work?

Thanks

**Comment by qmeeus** [comment]
Turns out the solution is to `pip install bitsandbytes` from a computer where the GPU has a compute capability > 7.5, a matching pytorch version and cuda installed (not as part of a conda environment but the [good old way](https://raw.githubusercontent.com/TimDettmers/bitsandbytes/main/cuda_install.sh
)). Although this might seem trivial, when using clusters with a shared file system and various GPUs, this essentially mean that you need to have one environment per cuda + cudnn version, and run the right environment per GPU.

If someone found an easier way to work around this, please let me know
