### ISSUE TITLE
RuntimeError: CUDA Setup failed despite GPU being available.

### ISSUE THREAD

**Issue by Rcrossmeister** [TimDettmers/bitsandbytes#862]
(llama) zijinhong@DGX-Station-A800:~$ python -m bitsandbytes
False

===================================BUG REPORT===================================
/raid/home/zijinhong/anaconda3/envs/llama/lib/python3.10/site-packages/bitsandbytes/cuda_setup/main.py:166: UserWarning: Welcome to bitsandbytes. For bug reports, please run

python -m bitsandbytes

warn(msg)

================================================================================
/raid/home/zijinhong/anaconda3/envs/llama/lib/python3.10/site-packages/bitsandbytes/cuda_setup/main.py:166: UserWarning: /raid/home/zijinhong/anaconda3/envs/llama did not contain ['libcudart.so', 'libcudart.so.11.0', 'libcudart.so.12.0'] as expected! Searching further paths...
  warn(msg)
/raid/home/zijinhong/anaconda3/envs/llama/lib/python3.10/site-packages/bitsandbytes/cuda_setup/main.py:166: UserWarning: Found duplicate ['libcudart.so', 'libcudart.so.11.0', 'libcudart.so.12.0'] files: {PosixPath('/usr/local/cuda/lib64/libcudart.so.11.0'), PosixPath('/usr/local/cuda/lib64/libcudart.so')}.. We select the PyTorch default libcudart.so, which is {torch.version.cuda},but this might missmatch with the CUDA version that is needed for bitsandbytes.To override this behavior set the BNB_CUDA_VERSION=<version string, e.g. 122> environmental variableFor example, if you want to use the CUDA version 122BNB_CUDA_VERSION=122 python ...OR set the environmental variable in your .bashrc: export BNB_CUDA_VERSION=122In the case of a manual override, make sure you set the LD_LIBRARY_PATH, e.g.export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/local/cuda-11.2
  warn(msg)
/raid/home/zijinhong/anaconda3/envs/llama/lib/python3.10/site-packages/bitsandbytes/cuda_setup/main.py:166: UserWarning: /usr/local/cuda/lib64: did not contain ['libcudart.so', 'libcudart.so.11.0', 'libcudart.so.12.0'] as expected! Searching further paths...
  warn(msg)
The following directories listed in your path were found to be non-existent: {PosixPath('/var/lib/nvidia-mig-manager/checkpoint.json')}
CUDA_SETUP: WARNING! libcudart.so not found in any environmental path. Searching in backup paths...
DEBUG: Possible options found for libcudart.so: {PosixPath('/usr/local/cuda/lib64/libcudart.so.11.0'), PosixPath('/usr/local/cuda/lib64/libcudart.so')}
CUDA SETUP: PyTorch settings found: CUDA_VERSION=113, Highest Compute Capability: 8.0.
CUDA SETUP: To manually override the PyTorch CUDA version please see:https://github.com/TimDettmers/bitsandbytes/blob/main/how_to_use_nonpytorch_cuda.md
CUDA SETUP: Required library version not found: libbitsandbytes_cuda113.so. Maybe you need to compile it from source?
CUDA SETUP: Defaulting to libbitsandbytes_cpu.so...

================================================ERROR=====================================
CUDA SETUP: CUDA detection failed! Possible reasons:
1. You need to manually override the PyTorch CUDA version. Please see: "https://github.com/TimDettmers/bitsandbytes/blob/main/how_to_use_nonpytorch_cuda.md
2. CUDA driver not installed
3. CUDA not installed
4. You have multiple conflicting CUDA libraries
5. Required library not pre-compiled for this bitsandbytes release!
CUDA SETUP: If you compiled from source, try again with `make CUDA_VERSION=DETECTED_CUDA_VERSION` for example, `make CUDA_VERSION=113`.
CUDA SETUP: The CUDA version for the compile might depend on your conda install. Inspect CUDA version via `conda list | grep cuda`.
================================================================================

CUDA SETUP: Something unexpected happened. Please compile from source:
git clone https://github.com/TimDettmers/bitsandbytes.git
cd bitsandbytes
CUDA_VERSION=113 make cuda11x
python setup.py install
CUDA SETUP: Setup Failed!
Traceback (most recent call last):
  File "/raid/home/zijinhong/anaconda3/envs/llama/lib/python3.10/runpy.py", line 187, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/raid/home/zijinhong/anaconda3/envs/llama/lib/python3.10/runpy.py", line 146, in _get_module_details
    return _get_module_details(pkg_main_name, error)
  File "/raid/home/zijinhong/anaconda3/envs/llama/lib/python3.10/runpy.py", line 110, in _get_module_details
    __import__(pkg_name)
  File "/raid/home/zijinhong/anaconda3/envs/llama/lib/python3.10/site-packages/bitsandbytes/__init__.py", line 6, in <module>
    from . import cuda_setup, utils, research
  File "/raid/home/zijinhong/anaconda3/envs/llama/lib/python3.10/site-packages/bitsandbytes/research/__init__.py", line 1, in <module>
    from . import nn
  File "/raid/home/zijinhong/anaconda3/envs/llama/lib/python3.10/site-packages/bitsandbytes/research/nn/__init__.py", line 1, in <module>
    from .modules import LinearFP8Mixed, LinearFP8Global
  File "/raid/home/zijinhong/anaconda3/envs/llama/lib/python3.10/site-packages/bitsandbytes/research/nn/modules.py", line 8, in <module>
    from bitsandbytes.optim import GlobalOptimManager
  File "/raid/home/zijinhong/anaconda3/envs/llama/lib/python3.10/site-packages/bitsandbytes/optim/__init__.py", line 6, in <module>
    from bitsandbytes.cextension import COMPILED_WITH_CUDA
  File "/raid/home/zijinhong/anaconda3/envs/llama/lib/python3.10/site-packages/bitsandbytes/cextension.py", line 20, in <module>
    raise RuntimeError('''
RuntimeError: 
        CUDA Setup failed despite GPU being available. Please run the following command to get more information:

        python -m bitsandbytes

        Inspect the output of the command and see if you can locate CUDA libraries. You might need to add them
        to your LD_LIBRARY_PATH. If you suspect a bug, please take the information from python -m bitsandbytes
        and open an issue at: https://github.com/TimDettmers/bitsandbytes/issues

My detailed environment: CUDA Version: 11.4, torch Version: 1.12.1+cu113

**Comment by swumagic** [comment]
Bitsandbytes was not supported windows before, but my method can support windows.（yuhuang）
1  open folder J:\StableDiffusion\sdwebui，Click the address bar of the folder and enter CMD
or WIN+R, CMD  。enter，cd /d J:\StableDiffusion\sdwebui
2  J:\StableDiffusion\sdwebui\py310\python.exe -m pip uninstall bitsandbytes

3 J:\StableDiffusion\sdwebui\py310\python.exe -m pip uninstall bitsandbytes-windows

4 J:\StableDiffusion\sdwebui\py310\python.exe -m pip install https://github.com/jllllll/bitsandbytes-windows-webui/releases/download/wheels/bitsandbytes-0.41.1-py3-none-win_amd64.whl

Replace your SD venv directory file（python.exe Folder） here（J:\StableDiffusion\sdwebui\py310）

**Comment by Rcrossmeister** [comment]
I'm using ubuntu system, seems bitsandbytes-windows do not solve for this issue.

**Comment by swumagic** [comment]
sorry,you are  ubuntu system,CUDA Version: 11.4, torch Version: 1.12.1+cu113.

Bitsandbytes can support ubuntu.（yuhuang）
1  open folder J:\StableDiffusion\sdwebui，Click the address bar of the folder and enter CMD
or WIN+R, CMD  。enter，cd /d J:\StableDiffusion\sdwebui
2  J:\StableDiffusion\sdwebui\py310\python.exe -m pip uninstall bitsandbytes

3 J:\StableDiffusion\sdwebui\py310\python.exe -m pip uninstall bitsandbytes-windows

4 J:\StableDiffusion\sdwebui\py310\python.exe -m pip install https://github.com/TimDettmers/bitsandbytes/releases/download/0.41.0/bitsandbytes-0.41.0-py3-none-any.whl

Replace your SD venv directory file（python.exe Folder） here（J:\StableDiffusion\sdwebui\py310）

**Comment by jndiogo** [comment]
For people having problems getting bitsandbytes to work in Linux, here's the way I got it running:

1) Using Conda/Mamba, I installed bitsandbytes 0.41.0 from conda-forge (https://anaconda.org/conda-forge/bitsandbytes) - by doing:
mamba install bitsandbytes -c conda-forge

2) Ran diagnostics which gave several warnings and errors: python -m bitsandbytes

3) Looked up libbitsandbytes:
find / -name 'libbitsandbytes*.so' 2>/dev/null
...
/home/user/miniforge3/envs/c/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cuda112.so

3) The cause of the problem was that I'm using CUDA 11.8, but the bitsandbytes package was compiled using number 11.2 (hence the 112 in the filename) and it was looking for libbitsandbytes_cuda118.so which is not there.
So, I used the number at the end of the found filename (112) to set the BNB_CUDA_VERSION env var:
export BNB_CUDA_VERSION=112
(For continued use add the export to your .bashrc)

4) Now run python -m bitsandbytes and it will hopefully report success at the end:
================================================================================
WARNING: Manual override via BNB_CUDA_VERSION env variable detected!
BNB_CUDA_VERSION=XXX can be used to load a bitsandbytes version that is different from the PyTorch CUDA version.
If this was unintended set the BNB_CUDA_VERSION variable to an empty string: export BNB_CUDA_VERSION=
If you use the manual override make sure the right libcudart.so is in your LD_LIBRARY_PATH
For example by adding the following to your .bashrc: export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:<path_to_cuda_dir/lib64
Loading CUDA version: BNB_CUDA_VERSION=112
================================================================================
...
...
SUCCESS!
Installation was successful!

BTW, cuda_setup/main.py appears to have a bug in method determine_cuda_runtime_lib_path() line 294 where the found lib paths are cleaned up, which makes it useless to set LD_LIBRARY_PATH. 
But setting BNB_CUDA_VERSION as above overrides this bug.

**Comment by NaomiNomz** [comment]
> pip install bitsandbytes-windows

You are a legend! I've been going mad uninstalling and reinstalling CUDA etc

**Comment by aksv5718** [comment]
> > pip install bitsandbytes-windows
> 
> You are a legend! I've been going mad uninstalling and reinstalling CUDA etc

still can't get it to work, i think it's because of the replacing the SD venv directory file part that I'm not understanding.
