### ISSUE TITLE
bug:There is a conflict between the two plug-ins. The bitsandbytes  version  required by the two plug-ins are different（Dreambooth-bitsandbytes version 0.41.1，but mov2mov bitsandbytes version 0.41.2.post2）.

### ISSUE THREAD

**Issue by swumagic** [TimDettmers/bitsandbytes#869]
bug
There is a conflict between the two plug-ins. The bitsandbytes  version  required by the two plug-ins are different（Dreambooth-bitsandbytes version 0.41.1，but mov2mov bitsandbytes version 0.41.2.post2）.

Initializing Dreambooth
Dreambooth revision: d8e01e1fd13dd4b6afadbb0382875f905ee5f429
[+] xformers version 0.0.21 installed.
[+] torch version 2.0.1+cu118 installed.
[+] torchvision version 0.15.2+cu118 installed.
[+] accelerate version 0.23.0 installed.
[+] diffusers version 0.21.2 installed.
[+] transformers version 4.30.2 installed.
[+] bitsandbytes version 0.41.1 installed.

False
The following directories listed in your path were found to be non-existent: {WindowsPath('J')}
CUDA_SETUP: WARNING! libcudart.so not found in any environmental path. Searching in backup paths...
The following directories listed in your path were found to be non-existent: {WindowsPath('/usr/local/cuda/lib64')}
DEBUG: Possible options found for libcudart.so: set()
CUDA SETUP: PyTorch settings found: CUDA_VERSION=118, Highest Compute Capability: 8.9.
CUDA SETUP: To manually override the PyTorch CUDA version please see:https://github.com/TimDettmers/bitsandbytes/blob/main/how_to_use_nonpytorch_cuda.md
CUDA SETUP: Loading binary J:\StableDiffusion\sdwebui\py310\lib\site-packages\bitsandbytes\libbitsandbytes_cuda118.so...
argument of type 'WindowsPath' is not iterable
CUDA SETUP: Problem: The main issue seems to be that the main CUDA runtime library was not detected.
CUDA SETUP: Solution 1: To solve the issue the libcudart.so location needs to be added to the LD_LIBRARY_PATH variable
CUDA SETUP: Solution 1a): Find the cuda runtime library via: find / -name libcudart.so 2>/dev/null
CUDA SETUP: Solution 1b): Once the library is found add it to the LD_LIBRARY_PATH: export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:FOUND_PATH_FROM_1a
CUDA SETUP: Solution 1c): For a permanent solution add the export from 1b into your .bashrc file, located at ~/.bashrc
CUDA SETUP: Solution 2: If no library was found in step 1a) you need to install CUDA.
CUDA SETUP: Solution 2a): Download CUDA install script: wget https://github.com/TimDettmers/bitsandbytes/blob/main/cuda_install.sh
CUDA SETUP: Solution 2b): Install desired CUDA version to desired location. The syntax is bash cuda_install.sh CUDA_VERSION PATH_TO_INSTALL_INTO.
CUDA SETUP: Solution 2b): For example, "bash cuda_install.sh 113 ~/local/" will download CUDA 11.3 and install into the folder ~/local

        CUDA Setup failed despite GPU being available. Please run the following command to get more information:

        python -m bitsandbytes

        Inspect the output of the command and see if you can locate CUDA libraries. You might need to add them
        to your LD_LIBRARY_PATH. If you suspect a bug, please take the information from python -m bitsandbytes
        and open an issue at: https://github.com/TimDettmers/bitsandbytes/issues

Traceback (most recent call last):
  File "J:\StableDiffusion\sdwebui\launch.py", line 48, in <module>
    main()
  File "J:\StableDiffusion\sdwebui\launch.py", line 44, in main
    start()
  File "J:\StableDiffusion\sdwebui\modules\launch_utils.py", line 436, in start
    webui.webui()
  File "J:\StableDiffusion\sdwebui\webui.py", line 64, in webui
    shared.demo = ui.create_ui()
  File "J:\StableDiffusion\sdwebui\modules\ui.py", line 1279, in create_ui
    with gr.TabItem(label, id=ifid, elem_id=f"tab_{ifid}"):
  File "J:\StableDiffusion\sdwebui\py310\lib\site-packages\gradio\layouts.py", line 221, in __init__
    BlockContext.__init__(self, elem_id=elem_id, **kwargs)
  File "J:\StableDiffusion\sdwebui\extensions\sd-webui-mov2mov\scripts\m2m_ui.py", line 603, in block_context_init
    on_ui_tabs()
  File "J:\StableDiffusion\sdwebui\extensions\sd-webui-mov2mov\scripts\m2m_ui.py", line 497, in on_ui_tabs
    editor = MovieEditor(id_part, init_mov, movie_frames)
UnboundLocalError: local variable 'movie_frames' referenced before assignment
提示：Python 运行时抛出了一个异常。请检查疑难解答页面。

--------

[程序崩溃，退出代码为 1 (0x00000001)]

**Comment by swumagic** [comment]
Bitsandbytes was not supported windows before, but my method can support windows.（yuhuang）
1  open folder J:\StableDiffusion\sdwebui，Click the address bar of the folder and enter CMD
or WIN+R, CMD  。enter，cd /d J:\StableDiffusion\sdwebui
2  J:\StableDiffusion\sdwebui\py310\python.exe -m pip uninstall bitsandbytes

3 J:\StableDiffusion\sdwebui\py310\python.exe -m pip uninstall bitsandbytes-windows

4 J:\StableDiffusion\sdwebui\py310\python.exe -m pip install https://github.com/jllllll/bitsandbytes-windows-webui/releases/download/wheels/bitsandbytes-0.41.1-py3-none-win_amd64.whl

Replace your SD venv directory file（python.exe Folder） here（J:\StableDiffusion\sdwebui\py310）

**Comment by realblankname1** [comment]
Thank you! This worked for me
