### ISSUE TITLE
"The installed version of bitsandbytes was compiled without GPU support" CUDA problem on Windows 10

### ISSUE THREAD

**Issue by AlexxB31** [TimDettmers/bitsandbytes#879]
Hello, I get always an error, when I run   python -m bitsandbytes

**_"The installed version of bitsandbytes was compiled without GPU support. 8-bit optimizers, 8-bit multiplication, and GPU quantization are unavailable.
  warn("The installed version of bitsandbytes was compiled without GPU support. "
function 'cadam32bit_grad_fp32' not found_**

The main issue is a failed Dreambooth initialization, which ends with: 
**"CUDA Setup failed despite GPU being available."**

CUDA is installed, I have added it as environment to the "Path" and also created a LD_LIBRARY_PATH as demanded
the path is:
C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v12.3
(just in case this is the wrong kind of cuda)

I have no more idea... Please help, thank

**Comment by Greg0mega** [comment]
Yes, I get his too now all of a sudden.

**Comment by offmybach** [comment]
did you figure it out yet?

**Comment by AlexxB31** [comment]
yes, the solution for me was in another thread here (https://github.com/TimDettmers/bitsandbytes/issues/858)
The folder "bitsandbytes" inside "venv/.../site-packages" must be replaced with a copy of the folder "bitsandbytes" inside "appdata/.../site-packages" . 
If you compare you will see, that the folder in appdata has much more cuda items.

A copy of the full description, just in my words is here:

1.    Open cmd, run this: python.exe -m pip install bitsandbytes-windows

    go to C:\Users\Me\AppData\Local\Programs\Python\Python310\Lib\site-packages

or wherever you have installed Python 3.10

2. copy the "bitsandbytes" folder.

    paste and replace the folder in your "\venv\Lib\site-packages"

for me is C:\stable-diffusion-webui\venv\Lib\site-packages.

**Comment by yanhaoYh** [comment]
thanks it sooo useful
