### ISSUE TITLE
[CUDA Setup failed despite GPU being available] ChatGLM3-6b / LLAMA-Factory / Langchain-chatchat

### ISSUE THREAD

**Issue by ShanJianSoda** [TimDettmers/bitsandbytes#892]
使用LLAMA-Factory 训练并合并LoRA权重导出完整模型 chatglm3-6b-peft
使用Langchain-chatchat 启动 chatglm3-6b-peft报错
The complete model chatglm3-6b-peft was derived by training and merging LoRA weights using LLAMA-Factory
Using Langchain-chatchat to start chatglm3-6b-peft yields an error

```
2023-12-01 15:16:52 | INFO | stdout | ================================================================================
2023-12-01 15:16:52 | INFO | stdout | binary_path: e:\anaconda3\Lib\site-packages\bitsandbytes\cuda_setup\libbitsandbytes_cuda116.dll
2023-12-01 15:16:52 | INFO | stdout | CUDA SETUP: Loading binary e:\anaconda3\Lib\site-packages\bitsandbytes\cuda_setup\libbitsandbytes_cuda116.dll...
2023-12-01 15:16:52 | INFO | stdout | Could not find module 'e:\anaconda3\Lib\site-packages\bitsandbytes\cuda_setup\libbitsandbytes_cuda116.dll' (or one of its dependencies). Try using the full path with constructor syntax.
2023-12-01 15:16:52 | INFO | stdout | CUDA SETUP: Loading binary e:\anaconda3\Lib\site-packages\bitsandbytes\cuda_setup\libbitsandbytes_cuda116.dll...
2023-12-01 15:16:52 | INFO | stdout | Could not find module 'e:\anaconda3\Lib\site-packages\bitsandbytes\cuda_setup\libbitsandbytes_cuda116.dll' (or one of its dependencies). Try using the full path with constructor syntax.
2023-12-01 15:16:52 | INFO | stdout | CUDA SETUP: Loading binary e:\anaconda3\Lib\site-packages\bitsandbytes\cuda_setup\libbitsandbytes_cuda116.dll...
2023-12-01 15:16:52 | INFO | stdout | Could not find module 'e:\anaconda3\Lib\site-packages\bitsandbytes\cuda_setup\libbitsandbytes_cuda116.dll' (or one of its dependencies). Try using the full path with constructor syntax.
2023-12-01 15:16:52 | INFO | stdout | CUDA SETUP: Problem: The main issue seems to be that the main CUDA library was not detected.
2023-12-01 15:16:52 | INFO | stdout | CUDA SETUP: Solution 1): Your paths are probably not up-to-date. You can update them via: sudo ldconfig.
2023-12-01 15:16:52 | INFO | stdout | CUDA SETUP: Solution 2): If you do not have sudo rights, you can do the following:
2023-12-01 15:16:52 | INFO | stdout | CUDA SETUP: Solution 2a): Find the cuda library via: find / -name libcuda.so 2>/dev/null
2023-12-01 15:16:52 | INFO | stdout | CUDA SETUP: Solution 2b): Once the library is found add it to the LD_LIBRARY_PATH: export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:FOUND_PATH_FROM_2a
2023-12-01 15:16:52 | INFO | stdout | CUDA SETUP: Solution 2c): For a permanent solution add the export from 2b into your .bashrc file, located at ~/.bashrc
2023-12-01 15:16:52 | ERROR | stderr | Process model_worker - chatglm3-6b-peft:
2023-12-01 15:16:52 | ERROR | stderr | Traceback (most recent call last):
2023-12-01 15:16:52 | ERROR | stderr |   File "e:\anaconda3\Lib\multiprocessing\process.py", line 314, in _bootstrap
2023-12-01 15:16:52 | ERROR | stderr |     self.run()
2023-12-01 15:16:52 | ERROR | stderr |   File "e:\anaconda3\Lib\multiprocessing\process.py", line 108, in run
2023-12-01 15:16:52 | ERROR | stderr |     self._target(*self._args, **self._kwargs)
2023-12-01 15:16:52 | ERROR | stderr |   File "E:\langchain\Langchain-Chatchat\startup.py", line 383, in run_model_worker
2023-12-01 15:16:52 | ERROR | stderr |     app = create_model_worker_app(log_level=log_level, **kwargs)
2023-12-01 15:16:52 | ERROR | stderr |           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2023-12-01 15:16:52 | ERROR | stderr |   File "E:\langchain\Langchain-Chatchat\startup.py", line 211, in create_model_worker_app
2023-12-01 15:16:52 | ERROR | stderr |     worker = ModelWorker(
2023-12-01 15:16:52 | ERROR | stderr |              ^^^^^^^^^^^^
2023-12-01 15:16:52 | ERROR | stderr |   File "e:\anaconda3\Lib\site-packages\fastchat\serve\model_worker.py", line 63, in __init__
2023-12-01 15:16:52 | ERROR | stderr |     super().__init__(
2023-12-01 15:16:52 | ERROR | stderr |   File "e:\anaconda3\Lib\site-packages\fastchat\serve\base_model_worker.py", line 47, in __init__
2023-12-01 15:16:52 | ERROR | stderr |     self.conv = self.make_conv_template(conv_template, model_path)
2023-12-01 15:16:52 | ERROR | stderr |                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2023-12-01 15:16:52 | ERROR | stderr |   File "e:\anaconda3\Lib\site-packages\fastchat\serve\base_model_worker.py", line 75, in make_conv_template
2023-12-01 15:16:52 | ERROR | stderr |     conv = get_conversation_template(model_path)
2023-12-01 15:16:53 | ERROR | stderr |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2023-12-01 15:16:53 | ERROR | stderr |   File "e:\anaconda3\Lib\site-packages\fastchat\model\model_adapter.py", line 334, in get_conversation_template
2023-12-01 15:16:53 | ERROR | stderr |     return adapter.get_default_conv_template(model_path)
2023-12-01 15:16:53 | ERROR | stderr |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2023-12-01 15:16:53 | ERROR | stderr |   File "e:\anaconda3\Lib\site-packages\fastchat\model\model_adapter.py", line 567, in get_default_conv_template
2023-12-01 15:16:53 | ERROR | stderr |     from peft import PeftConfig, PeftModel
2023-12-01 15:16:53 | ERROR | stderr |   File "e:\anaconda3\Lib\site-packages\peft\__init__.py", line 22, in <module>
2023-12-01 15:16:53 | ERROR | stderr |     from .auto import (
2023-12-01 15:16:53 | ERROR | stderr |   File "e:\anaconda3\Lib\site-packages\peft\auto.py", line 31, in <module>
2023-12-01 15:16:53 | ERROR | stderr |     from .mapping import MODEL_TYPE_TO_PEFT_MODEL_MAPPING
2023-12-01 15:16:53 | ERROR | stderr |   File "e:\anaconda3\Lib\site-packages\peft\mapping.py", line 23, in <module>
2023-12-01 15:16:53 | ERROR | stderr |     from .peft_model import (
2023-12-01 15:16:53 | ERROR | stderr |   File "e:\anaconda3\Lib\site-packages\peft\peft_model.py", line 39, in <module>
2023-12-01 15:16:53 | ERROR | stderr |     from .tuners import (
2023-12-01 15:16:53 | ERROR | stderr |   File "e:\anaconda3\Lib\site-packages\peft\tuners\__init__.py", line 21, in <module>
2023-12-01 15:16:53 | ERROR | stderr |     from .lora import LoraConfig, LoraModel
2023-12-01 15:16:53 | ERROR | stderr |   File "e:\anaconda3\Lib\site-packages\peft\tuners\lora\__init__.py", line 21, in <module>
2023-12-01 15:16:53 | ERROR | stderr |     from .model import LoraModel
2023-12-01 15:16:53 | ERROR | stderr |   File "e:\anaconda3\Lib\site-packages\peft\tuners\lora\model.py", line 45, in <module>
2023-12-01 15:16:53 | ERROR | stderr |     import bitsandbytes as bnb
2023-12-01 15:16:53 | ERROR | stderr |   File "e:\anaconda3\Lib\site-packages\bitsandbytes\__init__.py", line 7, in <module>
2023-12-01 15:16:53 | ERROR | stderr |     from .autograd._functions import (
2023-12-01 15:16:53 | ERROR | stderr |   File "e:\anaconda3\Lib\site-packages\bitsandbytes\autograd\__init__.py", line 1, in <module>
2023-12-01 15:16:53 | ERROR | stderr |     from ._functions import undo_layout, get_inverse_transform_indices
2023-12-01 15:16:53 | ERROR | stderr |   File "e:\anaconda3\Lib\site-packages\bitsandbytes\autograd\_functions.py", line 9, in <module>
2023-12-01 15:16:53 | ERROR | stderr |     import bitsandbytes.functional as F
2023-12-01 15:16:53 | ERROR | stderr |   File "e:\anaconda3\Lib\site-packages\bitsandbytes\functional.py", line 17, in <module>
2023-12-01 15:16:53 | ERROR | stderr |     from .cextension import COMPILED_WITH_CUDA, lib
2023-12-01 15:16:53 | ERROR | stderr |   File "e:\anaconda3\Lib\site-packages\bitsandbytes\cextension.py", line 22, in <module>
2023-12-01 15:16:53 | ERROR | stderr |     raise RuntimeError('''
2023-12-01 15:16:53 | ERROR | stderr | RuntimeError:
2023-12-01 15:16:53 | ERROR | stderr |         CUDA Setup failed despite GPU being available. Inspect the CUDA SETUP outputs above to fix your environment!
2023-12-01 15:16:53 | ERROR | stderr |         If you cannot find any issues and suspect a bug, please open an issue with detals about your environment:
2023-12-01 15:16:53 | ERROR | stderr |         https://github.com/TimDettmers/bitsandbytes/issues
```

环境：
environment:
windows 11
```
>>> print(torch.__version__)
2.1.0+cu121
>>> print(torch.cuda.is_available())
True
```

**Comment by OleksandrKorovii** [comment]
Try to install it from source. I have CUDA version  12.3 but set  CUDA_VERSION=121 for capabilities with pytorch 2.1.0

Here is my steps:
````
git clone https://github.com/timdettmers/bitsandbytes.git

cd bitsandbytes

CUDA_VERSION=121 make cuda12x

pip install . 
````
After that try to run: 
```
python -m bitsandbytes
```

Please comment below if it works for you. Thanks)

**Comment by conorKotwasinski** [comment]
This worked for me thank you so much!

**Comment by Utkarsh-quytech** [comment]
Getting this issue while using train_dreambooth_lora.py (the above worked for train_dreambooth.py but not for this)
===================================BUG REPORT===================================
C:\Users\Utkarsh.Singh\anaconda3\envs\avatar\lib\site-packages\bitsandbytes\cuda_setup\main.py:166: UserWarning: Welcome to bitsandbytes. For bug reports, please run

python -m bitsandbytes


  warn(msg)
================================================================================
The following directories listed in your path were found to be non-existent: {WindowsPath('C')}
C:\Users\Utkarsh.Singh\anaconda3\envs\avatar\lib\site-packages\bitsandbytes\cuda_setup\main.py:166: UserWarning: C:\Users\Utkarsh.Singh\anaconda3\envs\avatar did not contain ['libcudart.so', 'libcudart.so.11.0', 'libcudart.so.12.0'] as expected! Searching further paths...
  warn(msg)
CUDA_SETUP: WARNING! libcudart.so not found in any environmental path. Searching in backup paths...
The following directories listed in your path were found to be non-existent: {WindowsPath('/usr/local/cuda/lib64')}
DEBUG: Possible options found for libcudart.so: set()
CUDA SETUP: PyTorch settings found: CUDA_VERSION=118, Highest Compute Capability: 7.5.
CUDA SETUP: To manually override the PyTorch CUDA version please see:https://github.com/TimDettmers/bitsandbytes/blob/main/how_to_use_nonpytorch_cuda.md
CUDA SETUP: Required library version not found: libbitsandbytes_cuda118.so. Maybe you need to compile it from source?
CUDA SETUP: Defaulting to libbitsandbytes_cpu.so...

================================================ERROR=====================================
CUDA SETUP: CUDA detection failed! Possible reasons:
1. You need to manually override the PyTorch CUDA version. Please see: "https://github.com/TimDettmers/bitsandbytes/blob/main/how_to_use_nonpytorch_cuda.md
2. CUDA driver not installed
3. CUDA not installed
4. You have multiple conflicting CUDA libraries
5. Required library not pre-compiled for this bitsandbytes release!
CUDA SETUP: If you compiled from source, try again with `make CUDA_VERSION=DETECTED_CUDA_VERSION` for example, `make CUDA_VERSION=113`.
CUDA SETUP: The CUDA version for the compile might depend on your conda install. Inspect CUDA version via `conda list | grep cuda`.
================================================================================

CUDA SETUP: Problem: The main issue seems to be that the main CUDA runtime library was not detected.
CUDA SETUP: Solution 1: To solve the issue the libcudart.so location needs to be added to the LD_LIBRARY_PATH variable
CUDA SETUP: Solution 1a): Find the cuda runtime library via: find / -name libcudart.so 2>/dev/null
CUDA SETUP: Solution 1b): Once the library is found add it to the LD_LIBRARY_PATH: export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:FOUND_PATH_FROM_1a
CUDA SETUP: Solution 1c): For a permanent solution add the export from 1b into your .bashrc file, located at ~/.bashrc
CUDA SETUP: Solution 2: If no library was found in step 1a) you need to install CUDA.
CUDA SETUP: Solution 2a): Download CUDA install script: wget https://github.com/TimDettmers/bitsandbytes/blob/main/install_cuda.sh
CUDA SETUP: Solution 2b): Install desired CUDA version to desired location. The syntax is bash install_cuda.sh CUDA_VERSION PATH_TO_INSTALL_INTO.
CUDA SETUP: Solution 2b): For example, "bash install_cuda.sh 113 ~/local/" will download CUDA 11.3 and install into the folder ~/local
CUDA SETUP: Setup Failed!
Traceback (most recent call last):
  File "C:\Users\Utkarsh.Singh\Documents\dreambooth\diffusers\examples\dreambooth\train_dreambooth_lora.py", line 37, in <module>
    from peft import LoraConfig
  File "C:\Users\Utkarsh.Singh\anaconda3\envs\avatar\lib\site-packages\peft\__init__.py", line 22, in <module>
    from .auto import (
  File "C:\Users\Utkarsh.Singh\anaconda3\envs\avatar\lib\site-packages\peft\auto.py", line 31, in <module>
    from .mapping import MODEL_TYPE_TO_PEFT_MODEL_MAPPING
  File "C:\Users\Utkarsh.Singh\anaconda3\envs\avatar\lib\site-packages\peft\mapping.py", line 23, in <module>
    from .mixed_model import PeftMixedModel
  File "C:\Users\Utkarsh.Singh\anaconda3\envs\avatar\lib\site-packages\peft\mixed_model.py", line 27, in <module>
    from peft.tuners.mixed import COMPATIBLE_TUNER_TYPES
  File "C:\Users\Utkarsh.Singh\anaconda3\envs\avatar\lib\site-packages\peft\tuners\__init__.py", line 21, in <module>
    from .lora import LoraConfig, LoraModel, LoftQConfig
  File "C:\Users\Utkarsh.Singh\anaconda3\envs\avatar\lib\site-packages\peft\tuners\lora\__init__.py", line 21, in <module>
    from .model import LoraModel
  File "C:\Users\Utkarsh.Singh\anaconda3\envs\avatar\lib\site-packages\peft\tuners\lora\model.py", line 49, in <module>
    import bitsandbytes as bnb
  File "C:\Users\Utkarsh.Singh\anaconda3\envs\avatar\lib\site-packages\bitsandbytes\__init__.py", line 6, in <module>
    from . import cuda_setup, utils, research
  File "C:\Users\Utkarsh.Singh\anaconda3\envs\avatar\lib\site-packages\bitsandbytes\research\__init__.py", line 1, in <module>
    from . import nn
  File "C:\Users\Utkarsh.Singh\anaconda3\envs\avatar\lib\site-packages\bitsandbytes\research\nn\__init__.py", line 1, in <module>
    from .modules import LinearFP8Mixed, LinearFP8Global
  File "C:\Users\Utkarsh.Singh\anaconda3\envs\avatar\lib\site-packages\bitsandbytes\research\nn\modules.py", line 8, in <module>
    from bitsandbytes.optim import GlobalOptimManager
  File "C:\Users\Utkarsh.Singh\anaconda3\envs\avatar\lib\site-packages\bitsandbytes\optim\__init__.py", line 6, in <module>
    from bitsandbytes.cextension import COMPILED_WITH_CUDA
  File "C:\Users\Utkarsh.Singh\anaconda3\envs\avatar\lib\site-packages\bitsandbytes\cextension.py", line 20, in <module>
    raise RuntimeError('''
RuntimeError:
        CUDA Setup failed despite GPU being available. Please run the following command to get more information:

        python -m bitsandbytes

        Inspect the output of the command and see if you can locate CUDA libraries. You might need to add them
        to your LD_LIBRARY_PATH. If you suspect a bug, please take the information from python -m bitsandbytes
        and open an issue at: https://github.com/TimDettmers/bitsandbytes/issues
Traceback (most recent call last):
  File "C:\Users\Utkarsh.Singh\anaconda3\envs\avatar\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\Utkarsh.Singh\anaconda3\envs\avatar\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\Utkarsh.Singh\anaconda3\envs\avatar\Scripts\accelerate.exe\__main__.py", line 7, in <module>
  File "C:\Users\Utkarsh.Singh\anaconda3\envs\avatar\lib\site-packages\accelerate\commands\accelerate_cli.py", line 47, in main
    args.func(args)
  File "C:\Users\Utkarsh.Singh\anaconda3\envs\avatar\lib\site-packages\accelerate\commands\launch.py", line 1017, in launch_command
    simple_launcher(args)
  File "C:\Users\Utkarsh.Singh\anaconda3\envs\avatar\lib\site-packages\accelerate\commands\launch.py", line 637, in simple_launcher
    raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)
subprocess.CalledProcessError: Command '['C:\\Users\\Utkarsh.Singh\\anaconda3\\envs\\avatar\\python.exe', 'C:/Users/Utkarsh.Singh/Documents/dreambooth/diffusers/examples/dreambooth/train_dreambooth_lora.py', '--pretrained_model_name_or_path=runwayml/stable-diffusion-v1-5', '--instance_data_dir=images', '--output_dir=model', "--instance_prompt='a photo of Utkarsh'", '--resolution=512', '--train_batch_size=1', '--gradient_accumulation_steps=1', '--checkpointing_steps=100', '--learning_rate=1e-4', '--report_to=wandb', '--lr_scheduler=constant', '--lr_warmup_steps=0', '--max_train_steps=800', "--validation_prompt='A photo of Utkarsh, blue fire, sci - fi, glowing lights!! intricate, elegant, digital painting, artstation, concept art, smooth, illustration, art by artgerm'", '--validation_epochs=100', '--seed=0', '--push_to_hub']' returned non-zero exit status 1.
Traceback (most recent call last):
  File "C:\Users\Utkarsh.Singh\Documents\dreambooth\diffusers\examples\dreambooth\train_test1.py", line 33, in <module>
    subprocess.run(command, check=True)
  File "C:\Users\Utkarsh.Singh\anaconda3\envs\avatar\lib\subprocess.py", line 524, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['accelerate', 'launch', 'C:/Users/Utkarsh.Singh/Documents/dreambooth/diffusers/examples/dreambooth/train_dreambooth_lora.py', '--pretrained_model_name_or_path=runwayml/stable-diffusion-v1-5', '--instance_data_dir=images', '--output_dir=model', "--instance_prompt='a photo of Utkarsh'", '--resolution=512', '--train_batch_size=1', '--gradient_accumulation_steps=1', '--checkpointing_steps=100', '--learning_rate=1e-4', '--report_to=wandb', '--lr_scheduler=constant', '--lr_warmup_steps=0', '--max_train_steps=800', "--validation_prompt='A photo of Utkarsh, blue fire, sci - fi, glowing lights!! intricate, elegant, digital painting, artstation, concept art, smooth, illustration, art by artgerm'", '--validation_epochs=100', '--seed=0', '--push_to_hub']' returned non-zero exit status 1.

If someone has a solution please provide here!!

**Comment by chiayi-hsu** [comment]
This is work for me! Thank you!

**Comment by Titus-von-Koeller** [comment]
Dear all,

Since the current release (last week, 8th of March) we now have official support for Windows 🎉 (which we did not have before) via

```
pip install bitsandbytes>=0.43.0
```

We're closing all old Windows issues and are asking everyone to try installing with this new version as outlined above and validate the install with `python -m bitsandbytes` which should spit out a bunch of stuff and then `SUCCESS`. Please let us know if everything worked correctly in [this new umbrella / catch-all issue](https://github.com/TimDettmers/bitsandbytes/issues/1131). Thanks 🤗
