### ISSUE TITLE
bitsandbytes just never works.

### ISSUE THREAD

**Issue by venturaEffect** [TimDettmers/bitsandbytes#914]
I've tried with different repos to finetune llms. Alsways when I see bitsandbytes are needed I already know this will be a pain in the ass. And this time was no difference.

Used the repo of Llama-Factory to fine tune a model. And needed bitsandbytes.

It tells there is a bug and following the instructions I write `python -m bitsandbytes` to see what is wrong. But, it just sends me the Bug Report from before.

`===================================BUG REPORT===================================
Welcome to bitsandbytes. For bug reports, please run

python -m bitsandbytes

 and submit this information together with your error trace to: https://github.com/TimDettmers/bitsandbytes/issues
================================================================================
bin C:\Users\zaesa\anaconda3\envs\llama_factory\lib\site-packages\bitsandbytes\libbitsandbytes_cuda118.dll
False
C:\Users\zaesa\anaconda3\envs\llama_factory\lib\site-packages\bitsandbytes\cuda_setup\main.py:156: UserWarning: WARNING: The following directories listed in your path were found to be non-existent: {WindowsPath('C:/Users/zaesa/anaconda3/envs/llama_factory/bin')}
  warn(msg)
C:\Users\zaesa\anaconda3\envs\llama_factory\lib\site-packages\bitsandbytes\cuda_setup\main.py:156: UserWarning: C:\Users\zaesa\anaconda3\envs\llama_factory did not contain ['cudart64_110.dll', 'cudart64_120.dll', 'cudart64_12.dll'] as expected! Searching further paths...
  warn(msg)
CUDA SETUP: CUDA runtime path found: C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.8\bin\cudart64_110.dll
CUDA SETUP: Highest compute capability among GPUs detected: 8.9
CUDA SETUP: Detected CUDA version 118
CUDA SETUP: Loading binary C:\Users\zaesa\anaconda3\envs\llama_factory\lib\site-packages\bitsandbytes\libbitsandbytes_cuda118.dll...
Could not find module 'C:\Users\zaesa\anaconda3\envs\llama_factory\lib\site-packages\bitsandbytes\libbitsandbytes_cuda118.dll' (or one of its dependencies). Try using the full path with constructor syntax.
CUDA SETUP: Something unexpected happened. Please compile from source:
git clone git@github.com:TimDettmers/bitsandbytes.git
cd bitsandbytes
CUDA_VERSION=118 make cuda11x
python setup.py install
Traceback (most recent call last):
  File "C:\Users\zaesa\anaconda3\envs\llama_factory\lib\runpy.py", line 187, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "C:\Users\zaesa\anaconda3\envs\llama_factory\lib\runpy.py", line 146, in _get_module_details
    return _get_module_details(pkg_main_name, error)
  File "C:\Users\zaesa\anaconda3\envs\llama_factory\lib\runpy.py", line 110, in _get_module_details
    __import__(pkg_name)
  File "C:\Users\zaesa\anaconda3\envs\llama_factory\lib\site-packages\bitsandbytes\__init__.py", line 6, in <module>
    from . import cuda_setup, utils, research
  File "C:\Users\zaesa\anaconda3\envs\llama_factory\lib\site-packages\bitsandbytes\research\__init__.py", line 1, in <module>
    from . import nn
  File "C:\Users\zaesa\anaconda3\envs\llama_factory\lib\site-packages\bitsandbytes\research\nn\__init__.py", line 1, in <module>
    from .modules import LinearFP8Mixed, LinearFP8Global
  File "C:\Users\zaesa\anaconda3\envs\llama_factory\lib\site-packages\bitsandbytes\research\nn\modules.py", line 8, in <module>
    from bitsandbytes.optim import GlobalOptimManager
  File "C:\Users\zaesa\anaconda3\envs\llama_factory\lib\site-packages\bitsandbytes\optim\__init__.py", line 6, in <module>
    from bitsandbytes.cextension import COMPILED_WITH_CUDA
  File "C:\Users\zaesa\anaconda3\envs\llama_factory\lib\site-packages\bitsandbytes\cextension.py", line 20, in <module>
    raise RuntimeError('''
RuntimeError:
        CUDA Setup failed despite GPU being available. Please run the following command to get more information:

        python -m bitsandbytes

        Inspect the output of the command and see if you can locate CUDA libraries. You might need to add them
        to your LD_LIBRARY_PATH. If you suspect a bug, please take the information from python -m bitsandbytes
        and open an issue at: https://github.com/TimDettmers/bitsandbytes/issues`

Would really appreciate how to solve this. I can't imagine how many people is going through this for fine tune and use LLMs. Because doesn't matter the path I take, when there is bitsandbytes involved it just breaks things.

Appreciate any suggestion.

**Comment by cbjrobertson** [comment]
Can I bump this 1000 times?

**Comment by josemerinom** [comment]
colab 
===================================BUG REPORT===================================
/usr/local/lib/python3.10/dist-packages/bitsandbytes/cuda_setup/main.py:166: UserWarning: Welcome to bitsandbytes. For bug reports, please run

python -m bitsandbytes


  warn(msg)
================================================================================
/usr/local/lib/python3.10/dist-packages/bitsandbytes/cuda_setup/main.py:166: UserWarning: /usr/lib64-nvidia did not contain ['libcudart.so', 'libcudart.so.11.0', 'libcudart.so.12.0'] as expected! Searching further paths...
  warn(msg)
The following directories listed in your path were found to be non-existent: {PosixPath('/sys/fs/cgroup/memory.events /var/colab/cgroup/jupyter-children/memory.events')}
The following directories listed in your path were found to be non-existent: {PosixPath('http'), PosixPath('//172.28.0.1'), PosixPath('8013')}
The following directories listed in your path were found to be non-existent: {PosixPath('--logtostderr --listen_host=172.28.0.12 --target_host=172.28.0.12 --tunnel_background_save_url=https'), PosixPath('//colab.research.google.com/tun/m/cc48301118ce562b961b3c22d803539adc1e0c19/gpu-t4-s-k1i9keaqrl3p --tunnel_background_save_delay=10s --tunnel_periodic_background_save_frequency=30m0s --enable_output_coalescing=true --output_coalescing_required=true')}
The following directories listed in your path were found to be non-existent: {PosixPath('/datalab/web/pyright/typeshed-fallback/stdlib,/usr/local/lib/python3.10/dist-packages')}
The following directories listed in your path were found to be non-existent: {PosixPath('/env/python')}
The following directories listed in your path were found to be non-existent: {PosixPath('module'), PosixPath('//ipykernel.pylab.backend_inline')}
CUDA_SETUP: WARNING! libcudart.so not found in any environmental path. Searching in backup paths...
DEBUG: Possible options found for libcudart.so: {PosixPath('/usr/local/cuda/lib64/libcudart.so')}
CUDA SETUP: PyTorch settings found: CUDA_VERSION=118, Highest Compute Capability: 7.5.
CUDA SETUP: To manually override the PyTorch CUDA version please see:https://github.com/TimDettmers/bitsandbytes/blob/main/how_to_use_nonpytorch_cuda.md
CUDA SETUP: Loading binary /usr/local/lib/python3.10/dist-packages/bitsandbytes/libbitsandbytes_cuda118.so...
libcusparse.so.11: cannot open shared object file: No such file or directory

**Comment by Arindam75** [comment]
Same problem here. 
I removed all the NVIDIA Drivers and CUDA related stuff. Re-installed cuda_12.0.0_527.41_windows.exe
Exactly same problem.

RuntimeError: Failed to import transformers.trainer because of the following error (look up to see its traceback):

      CUDA Setup failed despite GPU being available. Please run the following command to get more information:

      python -m bitsandbytes

      Inspect the output of the command and see if you can locate CUDA libraries. You might need to add them
      to your LD_LIBRARY_PATH. If you suspect a bug, please take the information from python -m bitsandbytes
      and open an issue at: https://github.com/TimDettmers/bitsandbytes/issues

**Comment by josemerinom** [comment]
In colab, I use:

1. !pip install -U bitsandbytes 

2. !pip install bitsandbytes==...( version: v35.. v40 v41 )

3. !git clone https://github.com/timdettmers/bitsandbytes.git
%cd bitsandbytes
!CUDA_VERSION=118 make cuda11x
!python setup.py install

4. !wget https://raw.githubusercontent.com/TimDettmers/bitsandbytes/main/install_cuda.sh
!bash install_cuda.sh 117 ~/local 1 

5. https://developer.nvidia.com/cuda-11-8-0-download-archive?target_os=Linux

6. ...
!apt-get install cuda...

7. I tried version 12.2, which is installed by default

Colab has cuda version 12.2, I reinstalled version 11.8, I had both versions, I used the suggested installation in the repository and it didn't work for me

**Comment by venturaEffect** [comment]
Yeah, I tried everything, installed from scratch CUDA different versions, compatibility with Pytorch and also with bitsandbytes. Also on different enviroments for different repos. Nothing, it just never works.

**Comment by josemerinom** [comment]
I have changed the patch location of the libraries, I have copied the libraries to the location that requests bit, the only file that I cannot find is libcudart.so in google colab, (libcudart.so.11 and libcudart.so.12 if I have them)

**Comment by Titus-von-Koeller** [comment]
Dear all,

Sorry that you all are having these hard to solve issues. Unfortunately, a
few people keep having these issues, partly to external reasons but I agree
it super frustrating. The majority of downloads (millions) seem to be
working, luckily enough, but let's try to figure this out together and try
to improve the situation going
forward.

I'll look more into this next week, but I would be very interested if this
proposed fix changes your situation at all:

https://github.com/TimDettmers/bitsandbytes/issues/915#issue-2043092383

Another approach to debug dynamic linking issues would be to run `ldd` on
the respective bnb binary and see if it's linked with the correct
dependencies.

Unfortunately these things are tricky because through pip we can only
control the Python part of the equation and package binaries, but there are
a bunch of dependencies that come from the system libraries and CUDA
install libraries, that have to be detected and linked together correctly.
The situation is a bit complex unfortunately and only partially under bnb
control.

The trace that you're all sharing is our attempt of helping in detecting
and guiding to resolve these issues. Obviously, there's still potential for
improvement that's why I just opened an improvement proposal RFC on the
topic.

The situation becomes even trickier with Windows, which is only has limited
(unofficial) support in bnb.

Sorry again for your struggles. We re working hard to get on top of
maintenance issues, as this library has only recently found sponsorship and
has a big backlog.

Thanks also for any info that you're providing to help along with
improvements.

Best,
Titus

**Comment by josemerinom** [comment]
I understand the situation, last week I was training in colab with bitsandbytes (I did tests and trained 6 to 8 models every day), but one morning, I started to get the error.
Sorry if I'm only talking about collab, but it's where I work.
In colab, every time it is used, bitsandbytes must be installed, I installed the latest version.
What changed from a few days ago to today?
I don't know if there was any update to bitsandbytes, or in my case, something changed in colab.
In the error message it indicates places where you search for the libraries, perhaps one of those sites is down and producing the error. I don't know, I speak without knowing about programming.

Thank you for your work and we hope to find a solution

**Comment by Titus-von-Koeller** [comment]
Hey! Thanks for getting back to me. Which type of instance are you using,
is it with a T4 GPU? Can you share the notebook with me, so I can take a
look + debug?

Is it now always not working or only some of the time?

**Comment by josemerinom** [comment]
here I uploaded my notebook + debugging messages
It is the notebook I used to train
the only modification is:
!pip install bitsandbytes > !pip install bitsandbytes==0.41.1

https://colab.research.google.com/github/josemerinom/test/blob/master/test.ipynb

pd: 
![image](https://github.com/TimDettmers/bitsandbytes/assets/20940429/f0a0a927-60f2-4e89-9138-6927885572c5)

**Comment by bcallonnec** [comment]
In colab i had the same issue,

Following recommandation [this post](https://stackoverflow.com/questions/50560395/how-to-install-cuda-in-google-colab-gpus/74561909#74561909) saved my problem.

**Comment by apurtell** [comment]
https://github.com/TimDettmers/bitsandbytes/issues/934

> So i followed the recommandations of [this post](https://stackoverflow.com/questions/50560395/how-to-install-cuda-in-google-colab-gpus/74561909#74561909) to install cuda 11-7

If you have Colab Pro you can get a shell, followed those recommendations, but `nvcc --version` still outputs "release 12.2" for me. 🤷

**Comment by bcallonnec** [comment]
Same for me `nvcc --version` still outpus "release 12.2" but command `python -m bitsandbytes` now print out "success"

**Comment by venturaEffect** [comment]
It keeps not working.

It doesn't matter the path I take. Always the same problem it doesn't matter what, if it involves bitsandbytes, then you are screwed.

**Comment by josemerinom** [comment]
I am using google colab, torch==2.0.1+cu118...
  I installed cuda 11.8 and added the location to the patch and it worked bitsandbytes
  
  CODE:
  
  !apt-get update
  !apt-get install cuda-toolkit-11-8
  import os
  os.environ["LD_LIBRARY_PATH"] += ":" + "/usr/local/cuda-11/lib64"
  os.environ["LD_LIBRARY_PATH"] += ":" + "/usr/local/cuda-11.8/lib64"

**Comment by Zeon8985Army** [comment]
@josemerinom , your solution work for my case, thanks,
I hope another people can find it to

**Comment by Titus-von-Koeller** [comment]
Hey everyone, the main issue (which started this thread) is actually clearly an installation on Windows, which wasn't supported before now but could be wrongly installed because the package build was setup wrong to support `any` OS. This has now been fixed and official Windows support added with the latest release from last week.

Since the issue creator was on Windows, I'm therefore closing this issue. For the others, I'm sorry, but since we took over maintenance we're working tirelessly to get on top of the maintenance backlog and improve bitsandbytes in all kinds of respect, also trying to better handle the long tail of people that are still experiencing issues with installation (it does work for most). Often this is related to the underlying installation or people are on CUDA versions or GPUs that are not supported and would need to [compile from source](https://huggingface.co/docs/bitsandbytes/v0.43.0/en/installation#alternative-compiling-from-source).

Anyways, we're currently working hard to improve the setup and diagnostics in bitsandbytes and you should see major improvements there in the next two releases. For now, I can't look in detail into each of your questions, I'm really sorry. I need to focus my energies to improve the overall situation in BNB and there's endless work right now.

For those on Windows, please reinstall the latest bitsandbytes version and try again. If you're  still having issues, post them in [this new umbrella / catch-all issue](https://github.com/TimDettmers/bitsandbytes/issues/1131).

For those on Linux, if you're still having issues, please open a separate issue and be extra careful to read through the debug output in detail and make sure to not cross-post on issue that only look superficially similar, because the debug output often looks too similar.

For other platforms, these are currently not officially supported and on versions prior to `v0.43.0` BNB could wrongly be installed on them via pip. This was a bug / wrong implementation. Now this is not possible anymore. Sorry for the time some of you have lost on this!

----

Dear all,

Since the current release (last week, 8th of March) we now have official support for Windows 🎉 (which we did not have before) via

```
pip install bitsandbytes>=0.43.0
```

We're closing all old Windows issues and are asking everyone to try installing with this new version as outlined above and validate the install with `python -m bitsandbytes` which should spit out a bunch of stuff and then `SUCCESS`. Please let us know if everything worked correctly in [this new umbrella / catch-all issue](https://github.com/TimDettmers/bitsandbytes/issues/1131). Thanks 🤗
