### ISSUE TITLE
 CUDA Setup failed despite GPU being available

### ISSUE THREAD

**Issue by Ivan9511** [TimDettmers/bitsandbytes#935]
I'm trying to install bitsandbytes in a conda environment.

Windows 10
Python 3.8.18
GPU: Nvidia GTX 1070
Cuda 12.3

I use 
`pip install bitsandbytes-windows`
Successfully installed bitsandbytes-windows-0.37.5

When I try to import into Python I get the following:

`===================================BUG REPORT===================================
Welcome to bitsandbytes. For bug reports, please submit your error trace to: https://github.com/TimDettmers/bitsandbytes/issues
================================================================================
binary_path: E:\Programs\Python\Anaconda\envs\llm\lib\site-packages\bitsandbytes\cuda_setup\libbitsandbytes_cuda116.dll
CUDA SETUP: Loading binary E:\Programs\Python\Anaconda\envs\llm\lib\site-packages\bitsandbytes\cuda_setup\libbitsandbytes_cuda116.dll...
Could not find module 'E:\Programs\Python\Anaconda\envs\llm\lib\site-packages\bitsandbytes\cuda_setup\libbitsandbytes_cuda116.dll' (or one of its dependencies). Try using the full path with constructor syntax.
CUDA SETUP: Loading binary E:\Programs\Python\Anaconda\envs\llm\lib\site-packages\bitsandbytes\cuda_setup\libbitsandbytes_cuda116.dll...
Could not find module 'E:\Programs\Python\Anaconda\envs\llm\lib\site-packages\bitsandbytes\cuda_setup\libbitsandbytes_cuda116.dll' (or one of its dependencies). Try using the full path with constructor syntax.
CUDA SETUP: Loading binary E:\Programs\Python\Anaconda\envs\llm\lib\site-packages\bitsandbytes\cuda_setup\libbitsandbytes_cuda116.dll...
Could not find module 'E:\Programs\Python\Anaconda\envs\llm\lib\site-packages\bitsandbytes\cuda_setup\libbitsandbytes_cuda116.dll' (or one of its dependencies). Try using the full path with constructor syntax.
CUDA SETUP: Problem: The main issue seems to be that the main CUDA library was not detected.
CUDA SETUP: Solution 1): Your paths are probably not up-to-date. You can update them via: sudo ldconfig.
CUDA SETUP: Solution 2): If you do not have sudo rights, you can do the following:
CUDA SETUP: Solution 2a): Find the cuda library via: find / -name libcuda.so 2>/dev/null
CUDA SETUP: Solution 2b): Once the library is found add it to the LD_LIBRARY_PATH: export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:FOUND_PATH_FROM_2a
CUDA SETUP: Solution 2c): For a permanent solution add the export from 2b into your .bashrc file, located at ~/.bashrc
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "E:\Programs\Python\Anaconda\envs\llm\lib\site-packages\bitsandbytes\__init__.py", line 7, in <module>
    from .autograd._functions import (
  File "E:\Programs\Python\Anaconda\envs\llm\lib\site-packages\bitsandbytes\autograd\__init__.py", line 1, in <module>
    from ._functions import undo_layout, get_inverse_transform_indices
  File "E:\Programs\Python\Anaconda\envs\llm\lib\site-packages\bitsandbytes\autograd\_functions.py", line 9, in <module>
    import bitsandbytes.functional as F
  File "E:\Programs\Python\Anaconda\envs\llm\lib\site-packages\bitsandbytes\functional.py", line 17, in <module>
    from .cextension import COMPILED_WITH_CUDA, lib
  File "E:\Programs\Python\Anaconda\envs\llm\lib\site-packages\bitsandbytes\cextension.py", line 22, in <module>
    raise RuntimeError('''
RuntimeError:
        CUDA Setup failed despite GPU being available. Inspect the CUDA SETUP outputs above to fix your environment!
        If you cannot find any issues and suspect a bug, please open an issue with detals about your environment:
        https://github.com/TimDettmers/bitsandbytes/issues`

I'm executing the command
`nvcc --version`
in the same environment outputs:
`nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2023 NVIDIA Corporation
Built on Fri_Nov__3_17:51:05_Pacific_Daylight_Time_2023
Cuda compilation tools, release 12.3, V12.3.103
Build cuda_12.3.r12.3/compiler.33492891_0`

**Comment by Ivan9511** [comment]
I solved the problem by installing Cuda 11.8

**Comment by Titus-von-Koeller** [comment]
`bitsandbytes-windows` is actually not related to this repo, it was created by other people. But now we have official Windows support, see below:

---

Dear all,

Since the current release (last week, 8th of March) we now have official support for Windows 🎉 (which we did not have before) via

```
pip install bitsandbytes>=0.43.0
```

We're closing all old Windows issues and are asking everyone to try installing with this new version as outlined above and validate the install with `python -m bitsandbytes` which should spit out a bunch of stuff and then `SUCCESS`. Please let us know if everything worked correctly in [this new umbrella / catch-all issue](https://github.com/TimDettmers/bitsandbytes/issues/1131). Thanks 🤗
