### ISSUE TITLE
Problem running on Windows, says CUDA is not installed but it actually is.

### ISSUE THREAD

**Issue by rmib200** [TimDettmers/bitsandbytes#939]
### System Info

Windows 11
Cuda 12.1 
PyTorch 
Python 3.10
GPU: NVIDIA 2050
bitsandbytes version 0.41.3.post2

### Reproduction

I am trying to run the same code that is in this colab (7.FineTune_LLAMA2_with_QLORA.ipynb): https://colab.research.google.com/github/ashishpatel26/LLM-Finetuning/blob/main/7.FineTune_LLAMA2_with_QLORA.ipynb
on my Windows machine. I always get stuck when trying to run bitandbytes getting this message:
```
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
File [c:\Users\rmib2\miniconda3\envs\llm-env\lib\site-packages\transformers\utils\import_utils.py:1382](file:///C:/Users/rmib2/miniconda3/envs/llm-env/lib/site-packages/transformers/utils/import_utils.py:1382), in _LazyModule._get_module(self, module_name)
   [1381](file:///C:/Users/rmib2/miniconda3/envs/llm-env/lib/site-packages/transformers/utils/import_utils.py:1381) try:
-> [1382](file:///C:/Users/rmib2/miniconda3/envs/llm-env/lib/site-packages/transformers/utils/import_utils.py:1382)     return importlib.import_module("." + module_name, self.__name__)
   [1383](file:///C:/Users/rmib2/miniconda3/envs/llm-env/lib/site-packages/transformers/utils/import_utils.py:1383) except Exception as e:

File [c:\Users\rmib2\miniconda3\envs\llm-env\lib\importlib\__init__.py:126](file:///C:/Users/rmib2/miniconda3/envs/llm-env/lib/importlib/__init__.py:126), in import_module(name, package)
    [125](file:///C:/Users/rmib2/miniconda3/envs/llm-env/lib/importlib/__init__.py:125)         level += 1
--> [126](file:///C:/Users/rmib2/miniconda3/envs/llm-env/lib/importlib/__init__.py:126) return _bootstrap._gcd_import(name[level:], package, level)

File <frozen importlib._bootstrap>:1050, in _gcd_import(name, package, level)

File <frozen importlib._bootstrap>:1027, in _find_and_load(name, import_)

File <frozen importlib._bootstrap>:1006, in _find_and_load_unlocked(name, import_)

File <frozen importlib._bootstrap>:688, in _load_unlocked(spec)

File <frozen importlib._bootstrap_external>:883, in exec_module(self, module)

File <frozen importlib._bootstrap>:241, in _call_with_frames_removed(f, *args, **kwds)

File [c:\Users\rmib2\miniconda3\envs\llm-env\lib\site-packages\transformers\integrations\bitsandbytes.py:11](file:///C:/Users/rmib2/miniconda3/envs/llm-env/lib/site-packages/transformers/integrations/bitsandbytes.py:11)
     [10](file:///C:/Users/rmib2/miniconda3/envs/llm-env/lib/site-packages/transformers/integrations/bitsandbytes.py:10) if is_bitsandbytes_available():
---> [11](file:///C:/Users/rmib2/miniconda3/envs/llm-env/lib/site-packages/transformers/integrations/bitsandbytes.py:11)     import bitsandbytes as bnb
     [12](file:///C:/Users/rmib2/miniconda3/envs/llm-env/lib/site-packages/transformers/integrations/bitsandbytes.py:12)     import torch

File [c:\Users\rmib2\miniconda3\envs\llm-env\lib\site-packages\bitsandbytes\__init__.py:6](file:///C:/Users/rmib2/miniconda3/envs/llm-env/lib/site-packages/bitsandbytes/__init__.py:6)
      [1](file:///C:/Users/rmib2/miniconda3/envs/llm-env/lib/site-packages/bitsandbytes/__init__.py:1) # Copyright (c) Facebook, Inc. and its affiliates.
      [2](file:///C:/Users/rmib2/miniconda3/envs/llm-env/lib/site-packages/bitsandbytes/__init__.py:2) #
      [3](file:///C:/Users/rmib2/miniconda3/envs/llm-env/lib/site-packages/bitsandbytes/__init__.py:3) # This source code is licensed under the MIT license found in the
      [4](file:///C:/Users/rmib2/miniconda3/envs/llm-env/lib/site-packages/bitsandbytes/__init__.py:4) # LICENSE file in the root directory of this source tree.
----> [6](file:///C:/Users/rmib2/miniconda3/envs/llm-env/lib/site-packages/bitsandbytes/__init__.py:6) from . import cuda_setup, utils, research
      [7](file:///C:/Users/rmib2/miniconda3/envs/llm-env/lib/site-packages/bitsandbytes/__init__.py:7) from .autograd._functions import (
      [8](file:///C:/Users/rmib2/miniconda3/envs/llm-env/lib/site-packages/bitsandbytes/__init__.py:8)     MatmulLtState,
      [9](file:///C:/Users/rmib2/miniconda3/envs/llm-env/lib/site-packages/bitsandbytes/__init__.py:9)     bmm_cublas,
   (...)
     [13](file:///C:/Users/rmib2/miniconda3/envs/llm-env/lib/site-packages/bitsandbytes/__init__.py:13)     matmul_4bit
     [14](file:///C:/Users/rmib2/miniconda3/envs/llm-env/lib/site-packages/bitsandbytes/__init__.py:14) )

File [c:\Users\rmib2\miniconda3\envs\llm-env\lib\site-packages\bitsandbytes\research\__init__.py:1](file:///C:/Users/rmib2/miniconda3/envs/llm-env/lib/site-packages/bitsandbytes/research/__init__.py:1)
----> [1](file:///C:/Users/rmib2/miniconda3/envs/llm-env/lib/site-packages/bitsandbytes/research/__init__.py:1) from . import nn
      [2](file:///C:/Users/rmib2/miniconda3/envs/llm-env/lib/site-packages/bitsandbytes/research/__init__.py:2) from .autograd._functions import (
      [3](file:///C:/Users/rmib2/miniconda3/envs/llm-env/lib/site-packages/bitsandbytes/research/__init__.py:3)     switchback_bnb,
      [4](file:///C:/Users/rmib2/miniconda3/envs/llm-env/lib/site-packages/bitsandbytes/research/__init__.py:4)     matmul_fp8_global,
      [5](file:///C:/Users/rmib2/miniconda3/envs/llm-env/lib/site-packages/bitsandbytes/research/__init__.py:5)     matmul_fp8_mixed,
      [6](file:///C:/Users/rmib2/miniconda3/envs/llm-env/lib/site-packages/bitsandbytes/research/__init__.py:6) )

File [c:\Users\rmib2\miniconda3\envs\llm-env\lib\site-packages\bitsandbytes\research\nn\__init__.py:1](file:///C:/Users/rmib2/miniconda3/envs/llm-env/lib/site-packages/bitsandbytes/research/nn/__init__.py:1)
----> [1](file:///C:/Users/rmib2/miniconda3/envs/llm-env/lib/site-packages/bitsandbytes/research/nn/__init__.py:1) from .modules import LinearFP8Mixed, LinearFP8Global

File [c:\Users\rmib2\miniconda3\envs\llm-env\lib\site-packages\bitsandbytes\research\nn\modules.py:8](file:///C:/Users/rmib2/miniconda3/envs/llm-env/lib/site-packages/bitsandbytes/research/nn/modules.py:8)
      [7](file:///C:/Users/rmib2/miniconda3/envs/llm-env/lib/site-packages/bitsandbytes/research/nn/modules.py:7) import bitsandbytes as bnb
----> [8](file:///C:/Users/rmib2/miniconda3/envs/llm-env/lib/site-packages/bitsandbytes/research/nn/modules.py:8) from bitsandbytes.optim import GlobalOptimManager
      [9](file:///C:/Users/rmib2/miniconda3/envs/llm-env/lib/site-packages/bitsandbytes/research/nn/modules.py:9) from bitsandbytes.utils import OutlierTracer, find_outlier_dims

File [c:\Users\rmib2\miniconda3\envs\llm-env\lib\site-packages\bitsandbytes\optim\__init__.py:6](file:///C:/Users/rmib2/miniconda3/envs/llm-env/lib/site-packages/bitsandbytes/optim/__init__.py:6)
      [1](file:///C:/Users/rmib2/miniconda3/envs/llm-env/lib/site-packages/bitsandbytes/optim/__init__.py:1) # Copyright (c) Facebook, Inc. and its affiliates.
      [2](file:///C:/Users/rmib2/miniconda3/envs/llm-env/lib/site-packages/bitsandbytes/optim/__init__.py:2) #
      [3](file:///C:/Users/rmib2/miniconda3/envs/llm-env/lib/site-packages/bitsandbytes/optim/__init__.py:3) # This source code is licensed under the MIT license found in the
      [4](file:///C:/Users/rmib2/miniconda3/envs/llm-env/lib/site-packages/bitsandbytes/optim/__init__.py:4) # LICENSE file in the root directory of this source tree.
----> [6](file:///C:/Users/rmib2/miniconda3/envs/llm-env/lib/site-packages/bitsandbytes/optim/__init__.py:6) from bitsandbytes.cextension import COMPILED_WITH_CUDA
      [8](file:///C:/Users/rmib2/miniconda3/envs/llm-env/lib/site-packages/bitsandbytes/optim/__init__.py:8) from .adagrad import Adagrad, Adagrad8bit, Adagrad32bit

File [c:\Users\rmib2\miniconda3\envs\llm-env\lib\site-packages\bitsandbytes\cextension.py:20](file:///C:/Users/rmib2/miniconda3/envs/llm-env/lib/site-packages/bitsandbytes/cextension.py:20)
     [19](file:///C:/Users/rmib2/miniconda3/envs/llm-env/lib/site-packages/bitsandbytes/cextension.py:19)     CUDASetup.get_instance().print_log_stack()
---> [20](file:///C:/Users/rmib2/miniconda3/envs/llm-env/lib/site-packages/bitsandbytes/cextension.py:20)     raise RuntimeError('''
     [21](file:///C:/Users/rmib2/miniconda3/envs/llm-env/lib/site-packages/bitsandbytes/cextension.py:21)     CUDA Setup failed despite GPU being available. Please run the following command to get more information:
     [22](file:///C:/Users/rmib2/miniconda3/envs/llm-env/lib/site-packages/bitsandbytes/cextension.py:22) 
     [23](file:///C:/Users/rmib2/miniconda3/envs/llm-env/lib/site-packages/bitsandbytes/cextension.py:23)     python -m bitsandbytes
     [24](file:///C:/Users/rmib2/miniconda3/envs/llm-env/lib/site-packages/bitsandbytes/cextension.py:24) 
     [25](file:///C:/Users/rmib2/miniconda3/envs/llm-env/lib/site-packages/bitsandbytes/cextension.py:25)     Inspect the output of the command and see if you can locate CUDA libraries. You might need to add them
     [26](file:///C:/Users/rmib2/miniconda3/envs/llm-env/lib/site-packages/bitsandbytes/cextension.py:26)     to your LD_LIBRARY_PATH. If you suspect a bug, please take the information from python -m bitsandbytes
     [27](file:///C:/Users/rmib2/miniconda3/envs/llm-env/lib/site-packages/bitsandbytes/cextension.py:27)     and open an issue at: https://github.com/TimDettmers/bitsandbytes/issues''')
     [28](file:///C:/Users/rmib2/miniconda3/envs/llm-env/lib/site-packages/bitsandbytes/cextension.py:28) lib.cadam32bit_grad_fp32 # runs on an error if the library could not be found -> COMPILED_WITH_CUDA=False

RuntimeError: 
        CUDA Setup failed despite GPU being available. Please run the following command to get more information:

        python -m bitsandbytes

        Inspect the output of the command and see if you can locate CUDA libraries. You might need to add them
        to your LD_LIBRARY_PATH. If you suspect a bug, please take the information from python -m bitsandbytes
        and open an issue at: https://github.com/TimDettmers/bitsandbytes/issues

The above exception was the direct cause of the following exception:

RuntimeError                              Traceback (most recent call last)
Cell In[17], [line 1](vscode-notebook-cell:?execution_count=17&line=1)
----> [1](vscode-notebook-cell:?execution_count=17&line=1) model = AutoModelForCausalLM.from_pretrained(
      [2](vscode-notebook-cell:?execution_count=17&line=2)     model_name,
      [3](vscode-notebook-cell:?execution_count=17&line=3)     quantization_config=bnb_config,
      [4](vscode-notebook-cell:?execution_count=17&line=4)     trust_remote_code=True
      [5](vscode-notebook-cell:?execution_count=17&line=5) )
      [6](vscode-notebook-cell:?execution_count=17&line=6) model.config.use_cache = False

File [c:\Users\rmib2\miniconda3\envs\llm-env\lib\site-packages\transformers\models\auto\auto_factory.py:566](file:///C:/Users/rmib2/miniconda3/envs/llm-env/lib/site-packages/transformers/models/auto/auto_factory.py:566), in _BaseAutoModelClass.from_pretrained(cls, pretrained_model_name_or_path, *model_args, **kwargs)
    [564](file:///C:/Users/rmib2/miniconda3/envs/llm-env/lib/site-packages/transformers/models/auto/auto_factory.py:564) elif type(config) in cls._model_mapping.keys():
    [565](file:///C:/Users/rmib2/miniconda3/envs/llm-env/lib/site-packages/transformers/models/auto/auto_factory.py:565)     model_class = _get_model_class(config, cls._model_mapping)
--> [566](file:///C:/Users/rmib2/miniconda3/envs/llm-env/lib/site-packages/transformers/models/auto/auto_factory.py:566)     return model_class.from_pretrained(
    [567](file:///C:/Users/rmib2/miniconda3/envs/llm-env/lib/site-packages/transformers/models/auto/auto_factory.py:567)         pretrained_model_name_or_path, *model_args, config=config, **hub_kwargs, **kwargs
    [568](file:///C:/Users/rmib2/miniconda3/envs/llm-env/lib/site-packages/transformers/models/auto/auto_factory.py:568)     )
    [569](file:///C:/Users/rmib2/miniconda3/envs/llm-env/lib/site-packages/transformers/models/auto/auto_factory.py:569) raise ValueError(
    [570](file:///C:/Users/rmib2/miniconda3/envs/llm-env/lib/site-packages/transformers/models/auto/auto_factory.py:570)     f"Unrecognized configuration class {config.__class__} for this kind of AutoModel: {cls.__name__}.\n"
    [571](file:///C:/Users/rmib2/miniconda3/envs/llm-env/lib/site-packages/transformers/models/auto/auto_factory.py:571)     f"Model type should be one of {', '.join(c.__name__ for c in cls._model_mapping.keys())}."
    [572](file:///C:/Users/rmib2/miniconda3/envs/llm-env/lib/site-packages/transformers/models/auto/auto_factory.py:572) )

File [c:\Users\rmib2\miniconda3\envs\llm-env\lib\site-packages\transformers\modeling_utils.py:3476](file:///C:/Users/rmib2/miniconda3/envs/llm-env/lib/site-packages/transformers/modeling_utils.py:3476), in PreTrainedModel.from_pretrained(cls, pretrained_model_name_or_path, config, cache_dir, ignore_mismatched_sizes, force_download, local_files_only, token, revision, use_safetensors, *model_args, **kwargs)
   [3473](file:///C:/Users/rmib2/miniconda3/envs/llm-env/lib/site-packages/transformers/modeling_utils.py:3473)     keep_in_fp32_modules = []
   [3475](file:///C:/Users/rmib2/miniconda3/envs/llm-env/lib/site-packages/transformers/modeling_utils.py:3475) if load_in_8bit or load_in_4bit:
-> [3476](file:///C:/Users/rmib2/miniconda3/envs/llm-env/lib/site-packages/transformers/modeling_utils.py:3476)     from .integrations import get_keys_to_not_convert, replace_with_bnb_linear
   [3478](file:///C:/Users/rmib2/miniconda3/envs/llm-env/lib/site-packages/transformers/modeling_utils.py:3478)     llm_int8_skip_modules = quantization_config.llm_int8_skip_modules
   [3479](file:///C:/Users/rmib2/miniconda3/envs/llm-env/lib/site-packages/transformers/modeling_utils.py:3479)     load_in_8bit_fp32_cpu_offload = quantization_config.llm_int8_enable_fp32_cpu_offload

File <frozen importlib._bootstrap>:1075, in _handle_fromlist(module, fromlist, import_, recursive)

File [c:\Users\rmib2\miniconda3\envs\llm-env\lib\site-packages\transformers\utils\import_utils.py:1372](file:///C:/Users/rmib2/miniconda3/envs/llm-env/lib/site-packages/transformers/utils/import_utils.py:1372), in _LazyModule.__getattr__(self, name)
   [1370](file:///C:/Users/rmib2/miniconda3/envs/llm-env/lib/site-packages/transformers/utils/import_utils.py:1370)     value = self._get_module(name)
   [1371](file:///C:/Users/rmib2/miniconda3/envs/llm-env/lib/site-packages/transformers/utils/import_utils.py:1371) elif name in self._class_to_module.keys():
-> [1372](file:///C:/Users/rmib2/miniconda3/envs/llm-env/lib/site-packages/transformers/utils/import_utils.py:1372)     module = self._get_module(self._class_to_module[name])
   [1373](file:///C:/Users/rmib2/miniconda3/envs/llm-env/lib/site-packages/transformers/utils/import_utils.py:1373)     value = getattr(module, name)
   [1374](file:///C:/Users/rmib2/miniconda3/envs/llm-env/lib/site-packages/transformers/utils/import_utils.py:1374) else:

File [c:\Users\rmib2\miniconda3\envs\llm-env\lib\site-packages\transformers\utils\import_utils.py:1384](file:///C:/Users/rmib2/miniconda3/envs/llm-env/lib/site-packages/transformers/utils/import_utils.py:1384), in _LazyModule._get_module(self, module_name)
   [1382](file:///C:/Users/rmib2/miniconda3/envs/llm-env/lib/site-packages/transformers/utils/import_utils.py:1382)     return importlib.import_module("." + module_name, self.__name__)
   [1383](file:///C:/Users/rmib2/miniconda3/envs/llm-env/lib/site-packages/transformers/utils/import_utils.py:1383) except Exception as e:
-> [1384](file:///C:/Users/rmib2/miniconda3/envs/llm-env/lib/site-packages/transformers/utils/import_utils.py:1384)     raise RuntimeError(
   [1385](file:///C:/Users/rmib2/miniconda3/envs/llm-env/lib/site-packages/transformers/utils/import_utils.py:1385)         f"Failed to import {self.__name__}.{module_name} because of the following error (look up to see its"
   [1386](file:///C:/Users/rmib2/miniconda3/envs/llm-env/lib/site-packages/transformers/utils/import_utils.py:1386)         f" traceback):\n{e}"
   [1387](file:///C:/Users/rmib2/miniconda3/envs/llm-env/lib/site-packages/transformers/utils/import_utils.py:1387)     ) from e

RuntimeError: Failed to import transformers.integrations.bitsandbytes because of the following error (look up to see its traceback):

        CUDA Setup failed despite GPU being available. Please run the following command to get more information:

        python -m bitsandbytes

        Inspect the output of the command and see if you can locate CUDA libraries. You might need to add them
        to your LD_LIBRARY_PATH. If you suspect a bug, please take the information from python -m bitsandbytes
        and open an issue at: https://github.com/TimDettmers/bitsandbytes/issues
```

When I run the `python -m bitsandbytes ` command and try to follow all the CUDA step isntructions it says that I don't have CUDA installed, which is not true I have the 12.1 version. 
When I try to run the install_cuda file I get that the PATH is not absolute, but it is. Maybe there is not enough support for windows, or what could I be doing wrong? Please help I don't know what to do anymore, any help would be appreaciated.

### Expected behavior

Fine tune a model.

**Comment by chenxiaodongman** [comment]
我也跟你遇见了同一个问题，C:\Users\chenx>nvcc --version
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2022 NVIDIA Corporation
Built on Tue_May__3_19:00:59_Pacific_Daylight_Time_2022
Cuda compilation tools, release 11.7, V11.7.64
Build cuda_11.7.r11.7/compiler.31294372_0

C:\Users\chenx>import bitsandbytes
'import' 不是内部或外部命令，也不是可运行的程序
或批处理文件。

C:\Users\chenx>python
Python 3.10.8 (tags/v3.10.8:aaaf517, Oct 11 2022, 16:50:30) [MSC v.1933 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import bitsandbytes
C:\Python312\lib\site-packages\bitsandbytes\cuda_setup\main.py:106: UserWarning:

================================================================================
WARNING: Manual override via BNB_CUDA_VERSION env variable detected!
BNB_CUDA_VERSION=XXX can be used to load a bitsandbytes version that is different from the PyTorch CUDA version.
If this was unintended set the BNB_CUDA_VERSION variable to an empty string: export BNB_CUDA_VERSION=
If you use the manual override make sure the right libcudart.so is in your LD_LIBRARY_PATH
For example by adding the following to your .bashrc: export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:<path_to_cuda_dir/lib64
Loading CUDA version: BNB_CUDA_VERSION=117
================================================================================


  warn((f'\n\n{"="*80}\n'
False

===================================BUG REPORT===================================
C:\Python312\lib\site-packages\bitsandbytes\cuda_setup\main.py:166: UserWarning: Welcome to bitsandbytes. For bug reports, please run

python -m bitsandbytes


  warn(msg)
================================================================================
CUDA_SETUP: WARNING! libcudart.so not found in any environmental path. Searching in backup paths...
The following directories listed in your path were found to be non-existent: {WindowsPath('/usr/local/cuda/lib64')}
DEBUG: Possible options found for libcudart.so: set()
CUDA SETUP: PyTorch settings found: CUDA_VERSION=117, Highest Compute Capability: 5.2.
CUDA SETUP: To manually override the PyTorch CUDA version please see:https://github.com/TimDettmers/bitsandbytes/blob/main/how_to_use_nonpytorch_cuda.md
C:\Python312\lib\site-packages\bitsandbytes\cuda_setup\main.py:166: UserWarning: WARNING: Compute capability < 7.5 detected! Only slow 8-bit matmul is supported for your GPU!                     If you run into issues with 8-bit matmul, you can try 4-bit quantization: https://huggingface.co/blog/4bit-transformers-bitsandbytes
  warn(msg)
CUDA SETUP: Required library version not found: libbitsandbytes_cuda117_nocublaslt.so. Maybe you need to compile it from source?
CUDA SETUP: Defaulting to libbitsandbytes_cpu.so...

================================================ERROR=====================================
CUDA SETUP: CUDA detection failed! Possible reasons:
1. You need to manually override the PyTorch CUDA version. Please see: "https://github.com/TimDettmers/bitsandbytes/blob/main/how_to_use_nonpytorch_cuda.md
2. CUDA driver not installed
3. CUDA not installed
4. You have multiple conflicting CUDA libraries
5. Required library not pre-compiled for this bitsandbytes release!
CUDA SETUP: If you compiled from source, try again with `make CUDA_VERSION=DETECTED_CUDA_VERSION` for example, `make CUDA_VERSION=113`.
CUDA SETUP: The CUDA version for the compile might depend on your conda install. Inspect CUDA version via `conda list | grep cuda`.
================================================================================

CUDA SETUP: Problem: The main issue seems to be that the main CUDA runtime library was not detected.
CUDA SETUP: Solution 1: To solve the issue the libcudart.so location needs to be added to the LD_LIBRARY_PATH variable
CUDA SETUP: Solution 1a): Find the cuda runtime library via: find / -name libcudart.so 2>/dev/null
CUDA SETUP: Solution 1b): Once the library is found add it to the LD_LIBRARY_PATH: export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:FOUND_PATH_FROM_1a
CUDA SETUP: Solution 1c): For a permanent solution add the export from 1b into your .bashrc file, located at ~/.bashrc
CUDA SETUP: Solution 2: If no library was found in step 1a) you need to install CUDA.
install.sh
CUDA SETUP: Solution 2b): Install desired CUDA version to desired location. The syntax is bash cuda_install.sh CUDA_VERSION PATH_TO_INSTALL_INTO.
CUDA SETUP: Solution 2b): For example, "bash cuda_install.sh 113 ~/local/" will download CUDA 11.3 and install into the folder ~/local
CUDA SETUP: Setup Failed!
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Python312\lib\site-packages\bitsandbytes\__init__.py", line 6, in <module>
    from . import cuda_setup, utils, research
  File "C:\Python312\lib\site-packages\bitsandbytes\research\__init__.py", line 1, in <module>
    from . import nn
  File "C:\Python312\lib\site-packages\bitsandbytes\research\nn\__init__.py", line 1, in <module>
    from .modules import LinearFP8Mixed, LinearFP8Global
  File "C:\Python312\lib\site-packages\bitsandbytes\research\nn\modules.py", line 8, in <module>
    from bitsandbytes.optim import GlobalOptimManager
  File "C:\Python312\lib\site-packages\bitsandbytes\optim\__init__.py", line 6, in <module>
    from bitsandbytes.cextension import COMPILED_WITH_CUDA
  File "C:\Python312\lib\site-packages\bitsandbytes\cextension.py", line 20, in <module>
    raise RuntimeError('''
RuntimeError:
        CUDA Setup failed despite GPU being available. Please run the following command to get more information:

        python -m bitsandbytes

        Inspect the output of the command and see if you can locate CUDA libraries. You might need to add them
        to your LD_LIBRARY_PATH. If you suspect a bug, please take the information from python -m bitsandbytes
        and open an issue at: https://github.com/TimDettmers/bitsandbytes/issues
>>>
如果解决了可以帮我一下吗？ 我已经弄了好几天了，还是没有解决

**Comment by running-frog** [comment]
我也是类似的问题，CUDA安装正常，前几天也用的好好的，昨天重新更新了bitsandbyts就不行了：
D:\software\python\python-3.10.11.amd64\lib\site-packages\bitsandbytes\cuda_setup\main.py:166: UserWarning: Welcome to bitsandbytes. For bug reports, please run

python -m bitsandbytes


  warn(msg)
================================================================================
CUDA_SETUP: WARNING! libcudart.so not found in any environmental path. Searching in backup paths...
The following directories listed in your path were found to be non-existent: {WindowsPath('/usr/local/cuda/lib64')}
DEBUG: Possible options found for libcudart.so: set()
CUDA SETUP: PyTorch settings found: CUDA_VERSION=118, Highest Compute Capability: 8.6.
CUDA SETUP: To manually override the PyTorch CUDA version please see:https://github.com/TimDettmers/bitsandbytes/blob/main/how_to_use_nonpytorch_cuda.md
CUDA SETUP: Loading binary D:\software\python\python-3.10.11.amd64\lib\site-packages\bitsandbytes\libbitsandbytes_cuda118.so...
argument of type 'WindowsPath' is not iterable
CUDA SETUP: Problem: The main issue seems to be that the main CUDA runtime library was not detected.
CUDA SETUP: Solution 1: To solve the issue the libcudart.so location needs to be added to the LD_LIBRARY_PATH variable
CUDA SETUP: Solution 1a): Find the cuda runtime library via: find / -name libcudart.so 2>/dev/null
CUDA SETUP: Solution 1b): Once the library is found add it to the LD_LIBRARY_PATH: export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:FOUND_PATH_FROM_1a
CUDA SETUP: Solution 1c): For a permanent solution add the export from 1b into your .bashrc file, located at ~/.bashrc
CUDA SETUP: Solution 2: If no library was found in step 1a) you need to install CUDA.
CUDA SETUP: Solution 2a): Download CUDA install script: wget https://github.com/TimDettmers/bitsandbytes/blob/main/cuda_install.sh
CUDA SETUP: Solution 2b): Install desired CUDA version to desired location. The syntax is bash cuda_install.sh CUDA_VERSION PATH_TO_INSTALL_INTO.
CUDA SETUP: Solution 2b): For example, "bash cuda_install.sh 113 ~/local/" will download CUDA 11.3 and install into the folder ~/local
Traceback (most recent call last):
  File "D:\software\python\python-3.10.11.amd64\lib\runpy.py", line 187, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "D:\software\python\python-3.10.11.amd64\lib\runpy.py", line 146, in _get_module_details
    return _get_module_details(pkg_main_name, error)
  File "D:\software\python\python-3.10.11.amd64\lib\runpy.py", line 110, in _get_module_details
    __import__(pkg_name)
  File "D:\software\python\python-3.10.11.amd64\lib\site-packages\bitsandbytes\__init__.py", line 6, in <module>
    from . import cuda_setup, utils, research
  File "D:\software\python\python-3.10.11.amd64\lib\site-packages\bitsandbytes\research\__init__.py", line 1, in <module>
    from . import nn
  File "D:\software\python\python-3.10.11.amd64\lib\site-packages\bitsandbytes\research\nn\__init__.py", line 1, in <module>
    from .modules import LinearFP8Mixed, LinearFP8Global
  File "D:\software\python\python-3.10.11.amd64\lib\site-packages\bitsandbytes\research\nn\modules.py", line 8, in <module>
    from bitsandbytes.optim import GlobalOptimManager
  File "D:\software\python\python-3.10.11.amd64\lib\site-packages\bitsandbytes\optim\__init__.py", line 6, in <module>
    from bitsandbytes.cextension import COMPILED_WITH_CUDA
  File "D:\software\python\python-3.10.11.amd64\lib\site-packages\bitsandbytes\cextension.py", line 20, in <module>
    raise RuntimeError('''
RuntimeError:
        CUDA Setup failed despite GPU being available. Please run the following command to get more information:

        python -m bitsandbytes

        Inspect the output of the command and see if you can locate CUDA libraries. You might need to add them
        to your LD_LIBRARY_PATH. If you suspect a bug, please take the information from python -m bitsandbytes
        and open an issue at: https://github.com/TimDettmers/bitsandbytes/issues

**Comment by rmib200** [comment]
```
===================================BUG REPORT===================================
================================================================================
The following directories listed in your path were found to be non-existent: {WindowsPath('C')}
The following directories listed in your path were found to be non-existent: {WindowsPath('module'), WindowsPath('/matplotlib_inline.backend_inline')}
The following directories listed in your path were found to be non-existent: {WindowsPath('vs/workbench/api/node/extensionHostProcess')}
CUDA_SETUP: WARNING! libcudart.so not found in any environmental path. Searching in backup paths...
The following directories listed in your path were found to be non-existent: {WindowsPath('/usr/local/cuda/lib64')}
DEBUG: Possible options found for libcudart.so: set()
CUDA SETUP: PyTorch settings found: CUDA_VERSION=121, Highest Compute Capability: 8.6.
CUDA SETUP: To manually override the PyTorch CUDA version please see:https://github.com/TimDettmers/bitsandbytes/blob/main/how_to_use_nonpytorch_cuda.md
CUDA SETUP: Loading binary [c:\Users\rmib2\miniconda3\envs\llm-env\lib\site-packages\bitsandbytes\libbitsandbytes_cuda121.so...](file:///C:/Users/rmib2/miniconda3/envs/llm-env/lib/site-packages/bitsandbytes/libbitsandbytes_cuda121.so...)
argument of type 'WindowsPath' is not iterable
CUDA SETUP: Problem: The main issue seems to be that the main CUDA runtime library was not detected.
CUDA SETUP: Solution 1: To solve the issue the libcudart.so location needs to be added to the LD_LIBRARY_PATH variable
CUDA SETUP: Solution 1a): Find the cuda runtime library via: find / -name libcudart.so 2>/dev/null
CUDA SETUP: Solution 1b): Once the library is found add it to the LD_LIBRARY_PATH: export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:FOUND_PATH_FROM_1a
CUDA SETUP: Solution 1c): For a permanent solution add the export from 1b into your .bashrc file, located at [~/.bashrc](https://file+.vscode-resource.vscode-cdn.net/c%3A/AI-Stuff/LLM-finetuning/~/.bashrc)
CUDA SETUP: Solution 2: If no library was found in step 1a) you need to install CUDA.
CUDA SETUP: Solution 2a): Download CUDA install script: wget https://github.com/TimDettmers/bitsandbytes/blob/main/cuda_install.sh
CUDA SETUP: Solution 2b): Install desired CUDA version to desired location. The syntax is bash cuda_install.sh CUDA_VERSION PATH_TO_INSTALL_INTO.
CUDA SETUP: Solution 2b): For example, "bash cuda_install.sh 113 [~/local/](https://file+.vscode-resource.vscode-cdn.net/c%3A/AI-Stuff/LLM-finetuning/~/local/)" will download CUDA 11.3 and install into the folder [~/local](https://file+.vscode-resource.vscode-cdn.net/c%3A/AI-Stuff/LLM-finetuning/~/local)
[c:\Users\rmib2\miniconda3\envs\llm-env\lib\site-packages\bitsandbytes\cuda_setup\main.py:166](file:///C:/Users/rmib2/miniconda3/envs/llm-env/lib/site-packages/bitsandbytes/cuda_setup/main.py:166): UserWarning: Welcome to bitsandbytes. For bug reports, please run

python -m bitsandbytes

 warn(msg)
c:\Users\rmib2\miniconda3\envs\llm-env\lib\site-packages\bitsandbytes\cuda_setup\main.py:166: UserWarning: C:\Users\rmib2\miniconda3\envs\llm-env did not contain ['libcudart.so', 'libcudart.so.11.0', 'libcudart.so.12.0'] as expected! Searching further paths...
  warn(msg)
Traceback (most recent call last):
  File "c:\Users\rmib2\miniconda3\envs\llm-env\lib\runpy.py", line 187, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "c:\Users\rmib2\miniconda3\envs\llm-env\lib\runpy.py", line 146, in _get_module_details
    return _get_module_details(pkg_main_name, error)
  File "c:\Users\rmib2\miniconda3\envs\llm-env\lib\runpy.py", line 110, in _get_module_details
    __import__(pkg_name)
  File "c:\Users\rmib2\miniconda3\envs\llm-env\lib\site-packages\bitsandbytes\__init__.py", line 6, in <module>
    from . import cuda_setup, utils, research
  File "c:\Users\rmib2\miniconda3\envs\llm-env\lib\site-packages\bitsandbytes\research\__init__.py", line 1, in <module>
    from . import nn
  File "c:\Users\rmib2\miniconda3\envs\llm-env\lib\site-packages\bitsandbytes\research\nn\__init__.py", line 1, in <module>
    from .modules import LinearFP8Mixed, LinearFP8Global
  File "c:\Users\rmib2\miniconda3\envs\llm-env\lib\site-packages\bitsandbytes\research\nn\modules.py", line 8, in <module>
    from bitsandbytes.optim import GlobalOptimManager
  File "c:\Users\rmib2\miniconda3\envs\llm-env\lib\site-packages\bitsandbytes\optim\__init__.py", line 6, in <module>
    from bitsandbytes.cextension import COMPILED_WITH_CUDA
  File "c:\Users\rmib2\miniconda3\envs\llm-env\lib\site-packages\bitsandbytes\cextension.py", line 20, in <module>
    raise RuntimeError('''
RuntimeError: 
        CUDA Setup failed despite GPU being available. Please run the following command to get more information:

        python -m bitsandbytes

        Inspect the output of the command and see if you can locate CUDA libraries. You might need to add them
        to your LD_LIBRARY_PATH. If you suspect a bug, please take the information from python -m bitsandbytes
        and open an issue at: https://github.com/TimDettmers/bitsandbytes/issues
```
I am also attaching the whole Bug Report I get when I run `python -m bitsandbytes`

**Comment by Titus-von-Koeller** [comment]
Dear all,

Since the current release (last week, 8th of March) we now have official support for Windows 🎉 (which we did not have before) via

```
pip install bitsandbytes>=0.43.0
```

We're closing all old Windows issues and are asking everyone to try installing with this new version as outlined above and validate the install with `python -m bitsandbytes` which should spit out a bunch of stuff and then `SUCCESS`. Please let us know if everything worked correctly in [this new umbrella / catch-all issue](https://github.com/TimDettmers/bitsandbytes/issues/1131). Thanks 🤗
